### ISSUE TITLE
Sprites draw themselves in weird places when the origin isn't (0, 0)

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/scribble#10]
Scribble tries to center in-text sprites that it draws, but if the origin isn't in the upper-left - say, in the center, for example - it doesn't quite know what to do.

    [spr_xbox][spr_keyboard]Show Info

where `spr_xbox` originates at (0, 0) and `spr_keyboard` originates in the center, you get this:

![this is probably not intended behavior](https://i.imgur.com/AZjWCWv.png)

instead of this:

![much better](https://i.imgur.com/lbsrrni.png)

**Comment by JujuAdams** [comment]
Thanks for reporting this. Fixed in `dev` branch.
