### ISSUE TITLE
MSDF

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Scribble#103]
MSDF

Time for another look.

**Comment by LastLifeLeft** [comment]
ಠ_ಠ

**Comment by JujuAdams** [comment]
Implemented the basics of this today. I'll reflect on how many features I'd like to support at v7's launch

**Comment by LastLifeLeft** [comment]
(づ＾ 3＾)づ

**Comment by JujuAdams** [comment]
Feature complete for v7, including documentation
