### ISSUE TITLE
Whole string shaking instead of the individual characters

### ISSUE THREAD

**Issue by OmegaGamingHunters** [JujuAdams/scribble#106]
The whole string shakes when using the shake tag instead of the individual characters. I only noticed this after upgrading scribble from 5.50 to 6.08b. I don't know if this was intentional or not so I figured I ask...

**Comment by JujuAdams** [comment]
I've noticed this happens very occasionally but the issue seems intermittant. If you've got a project where this you can replicate it easily, please send it to me so I can fix it. To reassure you (somewhat) the behaviour of the `[shake]` tag is not intended to have changed and should shake each character individually.

**Comment by OmegaGamingHunters** [comment]
https://drive.google.com/file/d/1ughG7eL_Jad8Z8lY9DwGT3YGcmKisWeV/view?usp=sharing Would a local package of my project do? I don't know of any other way so sending it... On a side note: I also notice this happening in the sample project that I got from the download.

**Comment by JujuAdams** [comment]
What version of GM are you using at the moment?

**Comment by OmegaGamingHunters** [comment]
version 2.2.5.481

**Comment by JujuAdams** [comment]
Great, thank you. I'll look at this tomorrow hopefully

**Comment by JujuAdams** [comment]
Hiya @OmegaGamingHunters, sorry for being a bit slow here.

Could you please replace your entire vertex shader for `shd_scribble` with the vertex shader found here: https://pastebin.com/eeDjzmcg   Please ensure you're using version 6.0.8b.

After you've done that, clear the cache and re-run the game. Let me know if that does/doesn't fix your problem.

**Comment by JujuAdams** [comment]
I tihnk we may have a solution for this. Some graphics cards (and I think PS4 as well perhaps) are struggling with using high numbers as an input to `sin()` in the main Scribble shader.

**Comment by JujuAdams** [comment]
Turns out it was floating point accuracy all along! This is fixed now, will be available in v6.0.10
