### ISSUE TITLE
Changing typing speed mid way through the text.

### ISSUE THREAD

**Issue by OmegaGamingHunters** [JujuAdams/Scribble#107]
Changing the typing speed of the text would help a lot instead of doing "[delay,500].[delay,500].[delay,500]".  It would save more time (even if it's only a few seconds) when writing the text and makes string look more cleaner. So instead of this: "[delay,500].[delay,500].[delay,500]", we would have this: "[speed,0.2]...". I tried doing this with the events scripts but it gave me a DoAdd Execution Error (at least that's what I remembered, its been awhile since I last tried so idk.)

**Comment by JujuAdams** [comment]
This will be implemented for Scribble 7, at some point in the future.

**Comment by JujuAdams** [comment]
Implemented for v7. Needs testing
