### ISSUE TITLE
Custom autotype effects

### ISSUE THREAD

**Issue by anonyore** [JujuAdams/Scribble#108]
A way to add autotype appearance and disappearance effects (a-la [Super Text Mesh](https://youtu.be/TXmxbUy4o3s)) would be super cool.

**Comment by JujuAdams** [comment]
This is already *sort* of possible by editing the shader. I'll consider how much flexibility I can support with uniforms etc.

What appearance/disappearence effects would you find most attractive/useful?

**Comment by anonyore** [comment]
Slamming and sliding effects like the ones in [this](https://www.youtube.com/watch?v=7lEUkOvaYbo) and [this](https://youtu.be/1LeHFHa_JP0) are mostly what I'm looking for, haha. I'm planning to get more familiar with the internals of scribble so I can implement more custom stuff like this for sure.

**Comment by JujuAdams** [comment]
I'm not gonna say it's easy cos it's not 😅 I've done my best to make the shader clear but it's hard work because shader code is very different to GML. See https://github.com/JujuAdams/scribble/issues/41

Thanks for the suggestion(s), I'll work on this when I get a chance.

**Comment by JujuAdams** [comment]
Implemented for v7

![image](https://user-images.githubusercontent.com/3970480/98045759-e5e97080-1e20-11eb-966c-2305dd37877e.png)
