### ISSUE TITLE
Typewriter position off by one

### ISSUE THREAD

**Issue by glitchroy** [JujuAdams/scribble#11]
Hey,
maybe this problem only affects me, but after updating from scribble v4.5.1 to v4.7.3, the typewriter seemed to be shifted to the right by one character.  
More specifically, I implement a [pause] custom event which halts the typewriter by setting `json[| __SCRIBBLE.TW_SPEED]` to 0 temporarily (ugly, I know). After the update, even though `__SCRIBBLE.TW_POSITION` seemed unaffected, the pause happened one character too late.  
After multiple days, I tracked the change down to the shader, specifically this line:  
https://github.com/JujuAdams/scribble/blob/ca1a6d1523171883f9c19b72dfbaf577ab8e32c1/shaders/shScribble/shScribble.vsh#L141

Changing the `param` argument to `(in_Normal.x+1.0)/u_fCharFadeCount` seems to fix my issue. Since I'm not really a shader expert and `in_Normal` is some kind of default parameter, I can't really trace the root cause back. Maybe someone knows what's causing this behaviour? I compared `scribble_step()` and other scripts between the versions, but I do think it's because of the shader and the corresponding call from `scribble_draw()`.

Thanks!

PS: I'm only using the "per character" draw setting for the typewriter, so I'm not sure how this would affect drawing by line.

**Comment by JujuAdams** [comment]
Hiya, thank you for reporting this bug (as always!)

I'm super busy right now, but I'll hopefully be able to make time for this on Sunday. I'll keep you posted.

**Comment by JujuAdams** [comment]
Ok so I didn't get time for this on Sunday (clearly) but I'm looking at it now.

**Comment by JujuAdams** [comment]
Turns out that this wasn't a rendering issue but an event system issue. Version 4.8.0 should address these problems (currently on `dev-4-x-x` branch).
