### ISSUE TITLE
Getter for the bounding box of revealed text

### ISSUE THREAD

**Issue by sohomsahaun** [JujuAdams/Scribble#112]
<p align="center">
<img src="https://user-images.githubusercontent.com/27750907/90142474-3a3f0000-dd9e-11ea-8624-a9bc56719f2f.png">
</p>
<p align="center">
The red box
</p>

Additional request(s):

- Getting the number of lines typed

**Comment by JujuAdams** [comment]
Will require `SCRIBBLE_ALLOW_GLYPH_DATA_GETTER` to be set to `true`

**Comment by JujuAdams** [comment]
Implemented for v8
