### ISSUE TITLE
[delay] delaying a character too early when autotype is at certain speed

### ISSUE THREAD

**Issue by glitchroy** [JujuAdams/Scribble#115]
I seem to be the bringer of bad news again, and it's always about pausing the autotyper!  
Using the string `"abcdefg[delay]hijklmnop"`, the following happens:

![default1](https://user-images.githubusercontent.com/31043192/90830232-988d5500-e341-11ea-972f-bffe294345ac.gif)

As you can see, the delay happens one character too early. I'm using scribble v6.0.11 and GMS 2.3.0.529.

This **only** happens at certain autotype speeds, using the command `scribble_autotype_fade_in(content, <speed>, 0, false)`, I gathered the following:

| speed | character delay offset |
| --- | ---|
| 0.1 | 0 |
| 0.2 | -1 |
| 0.24 | -1 |
| 0.25 | 0 |
| 0.26 | -1 |
| 0.3 | -1 |
| 0.34 | -1 |
| 0.35 | 0 |
| 0.36 | -1 |
| 0.4 | -1 |
| 0.44 | -1 |
| 0.45 | -1 |
| 0.46 | -1 |
| 0.5 | 0 |
| 0.75 | -1 |
| 0.9 | - 1|
| 0.99 | -1 |
| 1 | 0 |
| 2 | 0 |

I tried this on the master branch "dialogue" demo @ b1312ea376f9cf5583172af40e2d201be3103961 and delay seems to break in the same way when changing the speed on line 38 in `obj_example_dialogue`. Seems to be some kind of rounding thing? I'm not sure.

EDIT: To complicate everything, the input string seems to have an effect, too. I tested with `"This is cu[delay]rious!"` at speed 0.35 where it delayed too early, while on speed 0.25 it didn't. With the string `"abcdefg[delay]hijklmnop"` it delayed correctly on both speeds.

**Comment by JujuAdams** [comment]
Known issue. Use a speed of 1 for now

**Comment by JujuAdams** [comment]
Fixed for v6.0.13
