### ISSUE TITLE
Imported unrelated sprites to my game, and now Scribble's glyphs are jumbled/broken

### ISSUE THREAD

**Issue by ahp275** [JujuAdams/Scribble#118]
I just imported some (relatively large) sprites into my game. I didn't touch any Scribble components at all, and as of my previous test everything was working fine. However, when I draw dialogue to the screen it now looks like this:

![scribble font messed up](https://user-images.githubusercontent.com/47668326/91243477-c0006b00-e70f-11ea-8b2e-7ea240b3b8b8.png)

Besides the upside-down letters and such, some of the glyphs seem to be fragments of other unrelated sprites in the project. My only thought is that perhaps adding large sprites caused GMS (2.3) to drastically rearrange its texture pages, and Scribble is looking in the wrong place for the spritefont, or something like that?

FWIW, the built-in draw_text functions use the same font as Scribble and are working fine.

**Comment by DragoniteSpam** [comment]
Clear the texture cache and replace the font.yy files in your included files. Would highly recommend putting your fonts on their own separate texture page from everything else so that you don't have to do this every time you add or edit a sprite.

**Comment by JujuAdams** [comment]
What version of Scribble are you using? Please use the latest version as some versions ago I fixed some bugs with spritefonts.

1) If you're using a normal font then follow the instructions DragoniteSpam kindly suggested. You may also need to regenerate the font (there's a button on the font asset window inside the IDE for that)
2) If you're using a spritefont, try clearing the cache. If that doesn't work, put your spritefont in a separate texture group

This issue may also be related to https://github.com/JujuAdams/Scribble/issues/97

**Comment by ahp275** [comment]
Hey guys, thank you both for the quick replies. I did as Dragonite suggested and cleared the cache, and then I gave the spritefont its own texture group. Fixed it right up! Going forward I'll have to be more mindful about how I allocate textures.

Thanks again to both of you for the support.
