### ISSUE TITLE
[rainbow] tag does not respect SCRIBBLE_COLORIZE_SPRITES

### ISSUE THREAD

**Issue by RAMclauglin** [JujuAdams/Scribble#121]
When SCRIBBLE_COLORIZE_SPRITES is set to false, the rainbow tag will still apply to the sprites, while [cycle] appropriately respects it.

![rainbow_does_not_respect_colorize_sprite](https://user-images.githubusercontent.com/6496473/91749325-50ff9800-eb8f-11ea-9da6-1d07756b486a.png)

Tested version: 6.0.11

**Comment by JujuAdams** [comment]
Fixed for v6.0.13
