### ISSUE TITLE
scribble_set_blend() crashes next draw call

### ISSUE THREAD

**Issue by RAMclauglin** [JujuAdams/Scribble#122]
If scribble_set_blend() is called with no arguments (or with explicit "undefined" arguments), the next scribble_draw call will crash due to undefined color global: 

`
colour_get_blue argument 1 incorrect type (undefined) expecting a Number (YYGI32)
 at gml_Script_scribble_draw (line 380) -                                                                         colour_get_blue( global.scribble_state_colour)/255,
`

**Comment by JujuAdams** [comment]
What would the expected behaviour be? `scribble_set_blend()` doesn't support `undefined` arguments.
