### ISSUE TITLE
[fa_center] tag centers lines incorrectly with word wrap

### ISSUE THREAD

**Issue by RAMclauglin** [JujuAdams/Scribble#123]
When scribble_set_wrap is used with text that has the [fa_center] tag, it will center the text before wrapping, creating large gaps where the last word on the wrapped line should have been. See screen shot, third line of text.

![image](https://user-images.githubusercontent.com/6496473/92007551-18d59200-ed14-11ea-98e4-0a8c77a48342.png)

Tested in version 6.0.11

**Comment by JujuAdams** [comment]
Fixed for v6.0.13
