### ISSUE TITLE
Autotype fade in flashing finished text.

### ISSUE THREAD

**Issue by DitDitGitHub** [JujuAdams/Scribble#126]
Hi, so I'm new to Scribble. I don't know if it's me being stupid or if it's a bug, so I thought I'd ask here.
My code:
`		scribble_autotype_fade_in("START",5,3,false);
		scribble_draw(350,400,"START");`

Sorry if it's a simple fix, I'm just confused. Once the text is finished typing (if it finishes, on some speeds it doesn't reach the end), it will flicker. Also, the text doesn't _really_ look animated or fade, it just appears. All help is appreciated!

(also, any chance of a discord server soon?)

**Comment by DitDitGitHub** [comment]
Alright, so after following a tutorial the problem is fixed, but, there is a new one. Just before the Autotype happens, the finished text momentarily flashes up on screen before disappearing and the animation happens.

**Comment by DitDitGitHub** [comment]
My code:
`switch(room){
	case MainMenu_RM:
		scribble_set_transform(5,3.25,0);
		scribble_set_box_align(fa_center,fa_middle);
		StartElement = scribble_draw(375,400,"START");
		
		if(ScribbleCreated == false || keyboard_check(vk_home)){
			scribble_autotype_fade_in(StartElement,0.065,1,false);
			ScribbleCreated = true;
		}
		break;
}`

**Comment by DitDitGitHub** [comment]
Alright, nevermind. I've fixed it. If you need help with Autotype, I highly recommend this tutorial: [Video](https://www.youtube.com/watch?v=TDxlwFQo2F4&t=538s)

**Comment by JujuAdams** [comment]
Congratulations on opening and closing the 100th issue for the repo!!

We have a Discord server here: https://discord.gg/8krYCqr
