### ISSUE TITLE
Option to make the Autotype fade in and out in the opposite direction.

### ISSUE THREAD

**Issue by DitDitGitHub** [JujuAdams/Scribble#127]
It would be cool if there was an option to fade in the opposite direction, so instead of fading out to the right, it would fade out from the left.

**Comment by JujuAdams** [comment]
Related to #108

**Comment by JujuAdams** [comment]
Backwards fade out implemented for v7. Backwards fade in breaks the event system so I won't be implementing that right now unless someone really wants it
