### ISSUE TITLE
scribble_get_bbox not returning correct coordinates when alignment different than fa_top

### ISSUE THREAD

**Issue by biyectivo** [JujuAdams/Scribble#130]
When using scribble_get_bbox to get the coordinates of the bounding box of a previously initialized scribble "object", the coordinates are not adjusting to alignment. This happens when using fa_bottom and fa_middle on the scribble text string:

test = "[fa_middle][c_red]Hi world";
bbox = scribble_get_bbox(30, 30, test);
draw_rectangle(bbox[0], bbox[1], bbox[2], bbox[3], false);
scribble_draw(30, 30, test);

The coordinates for bbox are being returned as if the alignment was fa_top (or default).

**Comment by JujuAdams** [comment]
Fixed for [v6.0.13f](https://github.com/JujuAdams/Scribble/releases/download/6.0.13/scribble_gms230_6_0_13f.yymps)
