### ISSUE TITLE
Randomize the fonts used by each character

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/Scribble#131]
I can't actually think of a use for this besides making a ransom note or something but it's apparently my life mission to see how often I can make you shake your head at me.

I'm thinking of something like this.

    [randomize,fnt_comicSans,fnt_consolas,fnt_wingdings,fnt_screaming]IF YOU WANT TO SEE YOUR NINTENDO AGAIN, LEAVE $50 UNDER THE TRASH BIN BEHIND THE SUPERMARKET

**Comment by JujuAdams** [comment]
It took a few months but... I am shaking my head
