### ISSUE TITLE
Reinitializing Scribble

### ISSUE THREAD

**Issue by Zuurix** [JujuAdams/Scribble#133]
Hey, I keep getting "SCRIBBLE_WARNING_REINITIALIZE" - I run scribble_init once in an object's Create event, it happens after game_restart() - should I just disable warning?

**Comment by JujuAdams** [comment]
Ideally, you should not be using `game_restart()` at all. It is a function that can cause any number of problems throughout your game.

If you want to shoot yourself in the foot by continuing to use `game_restart()`, then you're welcome to turn set `SCRIBBLE_WARNING_REINITIALIZE` to `false`. Scribble **should** continue functioning appropriately, but I cannot guarantee that.
