### ISSUE TITLE
Shader not compiling on Mac

### ISSUE THREAD

**Issue by madthijs** [JujuAdams/Scribble#140]
None of the examples worked on my Mac (GameMaker 2.3), but basic text was still being (partly) rendered. I noticed an error in the GameMaker output window. It was unable to compile the main shader (shd_scribble.vsh), comparing 'vec2 to float' is not allowed.

Line 326:
`if (u_aBezier[2] != 0.0)`

I replace it with: 
`if (u_aBezier[2].y != 0.0 || u_aBezier[2].x != 0.0)`

And everything came to life! Not sure if this breaks anything on other platforms, maybe you could test and update the shader.

PS: I don't have any knowledge about shaders or why the compiler behaves differently on my Mac (seems to strictly type check)

**Comment by JujuAdams** [comment]
Thanks for reporting this bug Thijs. Hotfixed it in v[6.0.14a](https://github.com/JujuAdams/Scribble/releases/tag/6.0.14)
