### ISSUE TITLE
Add scribble_volatile() to handle rapidly changing text?

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Scribble#141]

**Comment by DragoniteSpam** [comment]
By this do you mean something like a more robust solution to scribble-ing something like `format("Current HP: %0 / %1", hp_current, hp_max)`?

**Comment by JujuAdams** [comment]
Nope, this would be for non-cached text that doesn't need the more complex layout rules, but could still benefit from Scribble's rendering. Features such as pages and line wrapping would be disabled.

**Comment by JujuAdams** [comment]
Don't see much point in this now since text layout is far less expensive then the vertex buffer building step. No amount of crafty trimming ia going to get around that!
