### ISSUE TITLE
Add functionality to cache vertex buffers on the hard drive

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Scribble#146]
Some Scribble operations are quite slow (especially the new `.fit_to_box()` method). In a lot of cases, the text shown between runs of the game is identical. It makes sense for the developer to be able to cache vertex buffers to disk to avoid having to regenerate text models at runtime.
This system would likely only be of benefit on desktop and mobile devices as consoles have specific requirements when it comes to saving data.

**Comment by JujuAdams** [comment]
Sacking this off for another time. Not an urgent must-have feature by any stretch of the imagination

**Comment by DragoniteSpam** [comment]
if nothing else, the user could just foreach over the scribble cache and save each of the buffers themselves

**Comment by JujuAdams** [comment]
Can't think of a time when this would actually be useful

**Comment by DragoniteSpam** [comment]
I can admittedly think of times when this would be useful, but right now you're adding/removing/changing stuff so fast I'm sure it would constantly break with each update :p

**Comment by JujuAdams** [comment]
Convince me...
