### ISSUE TITLE
(Scribble 7) Default alignment options

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/Scribble#152]
I'm pretty sure there was a feature somewhere like this in Scribble 6 and I don't know if you removed it on purpose in 7 or if text alignment is just eternally cursed - but anyway, it would be handy to have a macro (or otherwise global variable) to set the default element alignment for new scribbles.

Right now I'm managing this by setting `halign` equal to something else on Line 8 of `__scribble_class_line` and `valign` equal to something else on Line 1645 in `__scribble_generate_model`, but those are scripts I'm not really supposed to touch and I don't want to give you any reasons to put coal in my christmas stocking (again).

**Comment by JujuAdams** [comment]
Edit `__scribble_config_default_template()`

**Comment by DragoniteSpam** [comment]
Juju stop moving options around >:^(
