### ISSUE TITLE
[line-break] tag just in case if someone uses this with chatterbox instead of using \n or #

### ISSUE THREAD

**Issue by OmegaGamingHunters** [JujuAdams/Scribble#153]
I recently put chatterbox into my dialog system and normal \n line break tags don't work, it just shows "\n". # is apparently used as a Localisation tag in yarn so a special [line break] tag might be useful just in case if someone where to use it (unless chatterbox doesn't support it). https://yarnspinner.dev/docs/syntax/

**Comment by JujuAdams** [comment]
You can set `SCRIBBLE_FIX_ESCAPED_NEWLINES` to `true` to fix `\n` literals not being handled as actual newline characters. Additionally, I'll make a note to make a similar feature for Chatterbox
