### ISSUE TITLE
Global scribble_flush (and / or scribble_reset) function

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/Scribble#154]
Some way to reset the scribble system, nuking all scribbles and effectively restarting the system from the beginning.

*you have brought this upon yourself, Mister Adams*

![image](https://user-images.githubusercontent.com/7087495/100164976-17d17e00-2e87-11eb-8837-2942f34d4f2a.png)

edit: mine looks like this, you may or may not want an official version to work the same way.

    function scribble_reset() {
        for (var key = ds_map_find_first(global.__scribble_element_cache); key != undefined; key = ds_map_find_next(global.__scribble_element_cache, key)) {
            global.__scribble_element_cache[? key].flush();
        }
        ds_map_clear(global.__scribble_element_cache);
    }

**Comment by JujuAdams** [comment]
Implemented for alpha 3
