### ISSUE TITLE
Sprites draw themselves in weird places when the origin isn't (0, 0) (again)

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/scribble#16]
Seems to be similar to #10, I don't know if it's the same problem that's come back or if it's a shiny new one.

If a sprite's origin is set to the upper-left, it looks fine.

![image](https://user-images.githubusercontent.com/7087495/66663427-b9acf180-ec18-11e9-8624-998a9b0ef540.png)

Yes I spelled "aperture" wrong, don't judge me.

If it's in the center, it starts looking a bit off.

![image](https://user-images.githubusercontent.com/7087495/66663456-c5001d00-ec18-11e9-9aba-50457c1bd84c.png)

If it's all the way at the bottom-right, it's way out in deep right field.

![image](https://user-images.githubusercontent.com/7087495/66663401-ae59c600-ec18-11e9-8a69-3fee0896256f.png)

Code:

    scribble_draw_set_wrap(32, 1200);
    scribble_draw_set_cache_group(0, false, true);
    scribble_draw(32, 32, "Apeture Science (sic), we do what we must because we can.\n\nFor the good of all of us, except the ones who are [spr_dead]");
    scribble_autotype_fade_in(scribble, SCRIBBLE_TYPEWRITER_PER_CHARACTER, 0.125, 1);
    scribble_draw_reset();

Keeping the sprite origin in the upper-left *seems* to align it correctly in all conceivable real-world use cases, which is to say it's automatically centered with the text, but if you have a sprite that you want to use both in Scribble and somewhere else in the project and you want it to have a different sprite origin, problems might start occurring.

**Comment by JujuAdams** [comment]
Thanks for the bug report.

Looks like I got a sign the wrong way round here! Hopefully an easy fix.

**Comment by JujuAdams** [comment]
Yep, had a sign the wrong way round. Also added a macro to ignore sprite origins (sprite origins are ignored by default).
