### ISSUE TITLE
Find cross-platform MSDF workaround

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Scribble#176]
Mac unfortunately doesn't like the standard derivatives extension (at least not on our version of GLSL) so I need to find a workaround. Hopefully YYG provide us with a way to force the GLSL version + add extensions soon <_<

**Comment by DragoniteSpam** [comment]
Get your shader stuff together, Yoyo >:(

**Comment by JujuAdams** [comment]
I belieeeeve I've found a solution for this, but YYG are apparently upgrading to Metal at some point in the future so I'll hold off on making Mac-related changes until the dust settles there.

**Comment by JujuAdams** [comment]
Bumped up the priority queue as this impacts more platforms than I was initially aware of.

**Comment by ZigZaggh** [comment]
Sounds great, I'm looking forward to be able to use Scribble with MSDF Fonts in my project, as this solves some annoying issues I have with scaling and the standard text rendering.

**Comment by JujuAdams** [comment]
Fix open for testing in [7.1.2pre001](https://github.com/JujuAdams/Scribble/releases/tag/7.1.2pre001)

**Comment by ZigZaggh** [comment]
So I have been testing with the new version, and I have done all the previous mentioned test both on Android and iOS, and so far everything looks good just as on Windows, so absolutely perfect :+1: 

Thank you so much for looking in to this issue so fast Juju, very much appreciated :)

A question regarding performance, I would love to use this in an app both for Android and iOS, and my question is regarding lower end devices mostly on Android, how is the MSDF font performance there, or is there not a difference to the "normal" way of drawing fonts?

**Comment by JujuAdams** [comment]
There's marginally more work being done for MSDF fonts, but they're basically the same speed as a standard font rendered through Scribble.

As for performance versus GM's native text drawing? I've not tested it recently. I'd imagine Scribble is slower for simple strings, but simple strings don't have all the fun bits that make Scribble useful!

**Comment by ZigZaggh** [comment]
Sounds good, I must admit I have not looked too deep in to Scribble, I just saw there where some shaders and thought of some lower end devices not being too happy about them, but I guess these are used to render the font initially and not draw the font in the end?

**Comment by JujuAdams** [comment]
Bulk of the shader burden is in the vertex shader so that's orders of magnitude less stressful than heavy fragment shaders. The work that's being done in there is for all the effects (rainbow, wave, typewriter easing etc.). MSDF fonts, like standard fonts, only require a single texture sample so memory bandwidth is rarely a problem.

GM dynamically builds vertex buffers every frame for every piece of text you render, but Scribble caches vertex buffers. This vertex buffer caching offsets the extra cost of running a custom shader.

**Comment by ZigZaggh** [comment]
Sounds great, thank you for the explanation, I'm looking very much forward to working with Scribble :)

**Comment by JujuAdams** [comment]
Implemented in v7.1.2
