### ISSUE TITLE
Year in version date is referenced as 2020 

### ISSUE THREAD

**Issue by glitchroy** [JujuAdams/Scribble#178]
I'm sorry to open an issue for this, but I noticed the date in scribble files is referenced as `2020-01-02` multiple times (for version 7.0.3) and thankfully, it's 2021 by now. 
(Also the `Download the .yymps` link in the README links to the wrong tag)

To not completely waste your time, let me jut say thanks for your continued work on scribble and especially the new v7, which is again very revolutionary. Can't wait to use it more often!

**Comment by JujuAdams** [comment]
glitchroy, are you ok? You bumped your head last night. then you spent all night mumbling about "coronavirus". It's still 2020, I think it was all just a dream!
