### ISSUE TITLE
Trouble with skipping dialogue and animations

### ISSUE THREAD

**Issue by bcf513** [JujuAdams/Scribble#183]
I've been using Scribble for a while and it's really great, but had faced some small problems:

- When i try to use some animation effect in words, it work perfectly, at least when i just started the .exe, but if I leave the game open, and try it again after like 5 minutes the animations constantly resets, while still being displayed.

(This second thing could be me only using it wrong, but still)

Trying to fix that, I changed the way my text was updated (before was element = scribble(texto[pag]).template(padrao_fala)) to (element.overwrite(texto[pag])), but using it this way I had other problem:

- I programmed to when there's some text of the page undisplayed and the player press the dialogue button, it shows the full text of the message, by calling element.typewriter_skip(); the problem with this is that when the other pages are displayed, the typewritter don't start from the first character, even with the code calling element.typewriter_reset() (it functions perfectly if the player waits until all text is displayed in the page and then go to next page tho)

It's worth mentioning that I'm not using the page system inherent in Scribble, but rather using arrays and variables (here's why):

- In my game, the dialogues between characters will be presented as baloons near their bodies (just link in comics), and each baloon size is calculated to match the width and height of each page (with element.get_width() and element.get_height()), but it won't work properly if using Scribble's page system, cause this functions consider all pages dimensions, not of each individual page.

I'm sorry for all this text, that probably have some writing errors (I'm brazilian), but hope that you at least can read it, and I'dlike to thank you for sharing this incredible tool with everyone.

**Comment by JujuAdams** [comment]
Could you send me your project file if possible please? You can add me on Discord if you'd like and we can chat there.

> cause this functions consider all pages dimensions, not of each individual page.

We added two new functions recently that haven't made it into documentation yet - `.get_page_width()` and `.get_page_height()`. These functions are availble in version 7.1.0+

**Comment by JujuAdams** [comment]
Fixed in v7.1.1

Issue was related to limited GPU floating point accuracy on certain integrated graphics hardware
