### ISSUE TITLE
.typewriter_skip() doesn't appear to reset speed when changing page

### ISSUE THREAD

**Issue by JacobJacobEtc** [JujuAdams/Scribble#186]
In other words, using the skip function makes all text in one dialogue appear instantly.
This is obviously an issue if you have dialogue with multiple pages, or if you want to write out the same dialogue multiple times.

**Comment by JujuAdams** [comment]
Thanks for making this bug report, I'll look at it as soon as I'm able to.

**Comment by JujuAdams** [comment]
Fixed v7.1.1pre001 - sent you a message on Discord to confirm the fix
