### ISSUE TITLE
The typewriter stops working the second time I use it

### ISSUE THREAD

**Issue by Alemar5** [JujuAdams/Scribble#187]
I was trying to adapt scribble to a textbox rpg, and at first everything seemed to fit, at the end of the text the textbox was eliminated, but when reading it a second time, it was simply drawn and did not put the effect of writing letter by letter, someone do you know a solution?

Example ._.  (Sorry if the text is in Spanish, it has nothing to do with the code but ignore it hehe)
https://www.youtube.com/watch?v=wUExs6NVL84&feature=youtu.be

**Comment by JujuAdams** [comment]
What version of Scribble are you using?

**Comment by Alemar5** [comment]
the latest version of scribble, 7.1.0

**Comment by JujuAdams** [comment]
mmok, I suspect this might be a bug solved in v7.1.1. Could you try updating to [7.1.1pre001](https://github.com/JujuAdams/Scribble/releases/tag/7.1.1pre001) and then tell me if that fixes it?

**Comment by Alemar5** [comment]
ok, i will try, thanks!

**Comment by Alemar5** [comment]
I already update the scribble, but the problem continues to occur, try to draw the state of the typewriter and when the error happens it automatically appears at 1, that is, when the typewriter works it should start at 0 and gradually go up until it reaches to 1, but it automatically appears in 1, could that be that?

**Comment by JujuAdams** [comment]
How are you creating your text elements? Are you creating them in a Create event etc.? Are you holding a reference to the text element permanently?

**Comment by Alemar5** [comment]
Well, basically I have the doodle, with the typewriter both in the create and in the step, since if I have it only in the step, it marks an error, The text is temporary and comes from elements that when colliding with them and pressing The X key will generate a different message, a separate object is the one who gives the message, this is sent to the textbox through the player, so my code is structured:

[OBJ_TEXTBOX]
[CREATE]
indice = 0;

mensaje = "";

msage = scribble(mensaje)
	.typewriter_in(0.5, 1)
		.typewriter_sound(snd_letras, 999, 1.0, 1.0)


paus = false;

[STEP]
if (string_length(mensaje) < string_length(referencia.msg[indice])){
    mensaje += referencia.msg[indice]
}

msage = scribble(mensaje)
	.typewriter_in(0.5, 1)
		.typewriter_sound(snd_letras, 999, 1.0, 1.0)
		
		
if msage.get_typewriter_state() = 1 && (indice <= referencia.final)
{

	if keyboard_check_pressed(ord("X")) && (mensaje == referencia.msg[indice])
	{
		indice +=1;
		global.mensaje +=1
		if (indice > referencia.final) {obj_prota.stop = false; global.mensaje = 0; instance_destroy(); }
		mensaje = "";
	}	else
	{
		mensaje = referencia.msg[indice];		
	}

}


if (msage.get_typewriter_state() < 1) && paus = false
{

	if keyboard_check_pressed(ord("X"))
	{
		msage.typewriter_skip();
	}
	
}

if (msage.get_typewriter_paused()){
	
	paus = true
	if keyboard_check_pressed(ord("X"))
	{
		msage.typewriter_unpause();	
	}

}

[DRAW]
draw_self(); //allow to see the sprite of the object

msage.draw(x + 20, y + 7)

[OBJ_PROTA]

[STEP]
///Bed

if (stop == true) { exit; }

var  bloque;
bloque = collision_circle(x,y,32,obj_cama,false,false);

if (keyboard_check_pressed(ord("X")) and bloque){
    var msg;
    msg = instance_create(0,0,obj_textbox);
    msg.referencia = bloque;
    stop = true;
    
}

[OBJ_BED]

[CREATE]
msg[0] = "[wave]Aaaaaahh...[/wave] es tu bañera.";
msg[1] = "Con ella te das unos deliciosos\nbaños de tina.";
msg[2] = "A veces tu madre te regaña por\npasar mucho tiempo ahi.";
msg[3] = "Pero el agua caliente es lo\nmejor del mundo.";

final = 3;

global.mensaje = 0;

I hope this is more or less understandable 😅

**Comment by Yeasteroni** [comment]
I didn't read your code too carefully, so I apologize if you already know this, but the typewriter's progress in a text is stored in the text element generated by scribble(), so it isn't reset once the textbox disappears. You have to manually call the .typewriter_reset() method to reset the typewriter's position on that page.

**Comment by Anapsys** [comment]
> 
> 
> I didn't read your code too carefully, so I apologize if you already know this, but the typewriter's progress in a text is stored in the text element generated by scribble(), so it isn't reset once the textbox disappears. You have to manually call the .typewriter_reset() method to reset the typewriter's position on that page.

I was having this same issue. Adding this call whenever I made a new scribble element is what seems to have fixed it for me.
