### ISSUE TITLE
Issue with Pages

### ISSUE THREAD

**Issue by mattaylo** [JujuAdams/Scribble#188]
Greetings, 

I have looked everywhere for a deeper explanation of how to properly use pages, and I was hoping you could help.
I use the typewriter_ease function and the pages function. 
However, when I tell it to begin drawing the next page, it removes the ease effect from the text and has some ordinary typewriting effect.
I tried adding typewriter_ease immediately after the page change, and nothing happens...still the generic typewriter effect after anything from the 1st page. 
I did notice that when I reloaded the first page, it reapplied the ease effect correctly!

Here's my code:

/////step
if (keyboard_check_pressed(ord("X")))
{
if (element.get_typewriter_state() > 0) and (element.get_typewriter_state() < 1)
	{
	element.typewriter_in(1.5,10)
	}
if (element.on_last_page()=false and element.get_typewriter_state() == 1)
	{
	element.typewriter_in(0.4, 10);
	element.typewriter_ease(SCRIBBLE_EASE.ELASTIC, 0, -40, 1, 1, 20, 1);
	element.page(element.get_page() + 1)	
	}
if (element.on_last_page()=true and element.get_typewriter_state() == 1)
	{
	element.typewriter_out(2, 10, false);
    element.typewriter_ease(SCRIBBLE_EASE.ELASTIC, 0, 30, 1, 1, 0, 1);
	}
if (element.get_typewriter_state() == 2)
	{
	element.typewriter_in(0.4, 10);
	element.typewriter_ease(SCRIBBLE_EASE.ELASTIC, 0, -40, 1, 1, 20, 1);
	element.typewriter_reset()
	element.page(0)	
	}
}
///draw GUI
element.draw(x, y);

**Comment by mattaylo** [comment]
Also, I am using the previous full version (7.1.0)

**Comment by JujuAdams** [comment]
I believe this issue is fixed in [7.1.1pre002](https://github.com/JujuAdams/Scribble/releases/tag/7.1.1pre002). Please update and let me know if that fixes the issue for you.

**Comment by mattaylo** [comment]
I updated to 7.1.1.pre002 and it did not fix the issue.

**Comment by mattaylo** [comment]
I will just add that bizarrely, if I hit "X"  (the continue button) at just the right time, the ease effect applies to the next page, but I have to hit it at some very precise time oddly enough.

**Comment by JujuAdams** [comment]
Does it still type out characters properly? If you increase the smoothness value to something very high do you see characters fade in, albeit without the easing effect?

**Comment by mattaylo** [comment]
It types them out normally just fine. What it doesn't do is animate them using ease. Also changing smootheness from 10 to 50 did nothing. They instantly pop in.

**Comment by JujuAdams** [comment]
Page feature has been rewritten for v7.2.0pre002 (in beta at time of writing) and should fix this issue.
