### ISSUE TITLE
Typewriter events placed after page break run before the next page

### ISSUE THREAD

**Issue by Jakeybobble** [JujuAdams/Scribble#191]
Example:
`"Wow! Let me do a flip when you press Z![/page][doflip]Woo!"`
In this case, our character would do a flip as soon as the typewriter finishes the first page, when the event is supposed to run at the start of the next page.  This leaves us with a premature backflip :-(

**Comment by JujuAdams** [comment]
Man, I hate it when I prematurely backflip. All the clowns at the circus laugh at me :(  :(

I also thought I solved this in a previous update! I was clearly wrong. I'll give this a look when I can.

**Comment by JujuAdams** [comment]
Fixed in v7.2.0pre002
