### ISSUE TITLE
Make msdf_border thickness responsive with current scale

### ISSUE THREAD

**Issue by morphonet** [JujuAdams/Scribble#192]
When setting a template for msdf font, we can set a msdf_border of X px thickness.
When i write text at scale,1, everything looks good,
But once i change my scale, the msdf border of my font is still X px thickness.
It should/could be updated with current scale (ex: scale,5>thickness=5X ; scale,0.2 > thickness = 0.2X)

**Comment by JujuAdams** [comment]
Bit the bullet and extended the vertex format that Scribble uses. Feature open for testing in [7.1.2pre001](https://github.com/JujuAdams/Scribble/releases/tag/7.1.2pre001)

**Comment by JujuAdams** [comment]
Should be fully implemented for v7.1.2
