### ISSUE TITLE
scribble_font_scale + fit_to_box + origin/transform bug

### ISSUE THREAD

**Issue by morphonet** [JujuAdams/Scribble#193]
Hi dear Pug Master,

With this code : 
scribble_font_add_msdf("fnt", sAtlasVinque36Regular, "atlasVinqueRegular.json");
scribble_font_scale("fnt", 5, 5);

txt = scribble("UU SS XX aa").fit_to_box(220, 70);
txt.origin(txt.get_width()/2, txt.get_height()/2);
txt.transform(1,1,45);

txt2 = scribble("[scale,0.2]Mon Text");
txt2.origin(txt2.get_width()/2, txt2.get_height()/2);
txt2.transform(1,1,45);

txt is not rotating properly around the draw(x,y) point.
txt2 is rotating properly.

If I remove scribble_font_scale, then txt & txt2 works well,
If I let fit to box but no scribble_font_scale, it's working well too.

Sample project here : https://drive.google.com/file/d/1-wOJ3HF6NIvK6xaBIULFi355ZsT1Rqn8/view?usp=sharing

**Comment by JujuAdams** [comment]
(Note to self: see `scribble7_font_scale_fit_to_box.yyz`)

**Comment by DragoniteSpam** [comment]
PUG MASTER?

**Comment by JujuAdams** [comment]
Fixed for v8
