### ISSUE TITLE
MSDF Fonts bugged on Android?

### ISSUE THREAD

**Issue by ZigZaggh** [JujuAdams/Scribble#194]
Hi first thank you for an amazing tool :)

I ran in to an issue with MSDF fonts on Android, on windows they look great, on android they look like in the atlas file, and at some point stop drawing.

Have I overlooked something or is this a bug?

I have added a test pictures with windows(correct) and android(bugged).

Sincerely

![test](https://user-images.githubusercontent.com/43120666/111084575-5b71f580-8513-11eb-93e8-d0f491d6fb87.png)

**Comment by JujuAdams** [comment]
Looks like a general shader-related issue. What version are you using?

**Comment by ZigZaggh** [comment]
Hi Juju, thank you for getting back to me so fast.

I tested with Scribble version 7.1.1
Phone is a Samsung Galaxy s20+
GMS:
IDE v2.3.1.542
Runtime v2.3.1.409
I do not see anything out of the ordinary in the compiler output.

What I mean by "at some point stop drawing", is that I try to draw exactly the same strings on all 4 lines, both on windows and on android, and it looks like on android that the strings are cut off after the 16th character, the strings should be drawn to the edge and out of the screen as on the windows example. The first two strings are cut off at the "c" from could, and the the last two after the space from MSDF, but before the "font", looks weird on this string because it is cutting off right at the space I guess.

**Comment by JujuAdams** [comment]
Hmm... that's a bit concerning. That sounds like a vertex format issue which might not be solvable my end in a timely fashion. I'll look into this this week.

**Comment by ZigZaggh** [comment]
Thank you for looking in to this.

I do not know if this matters, but I also tested on an old Nexus 4 phone with Android 5.1.1 with the same result, I have not tested on an iPhone yet, I could do that too if you like that?

**Comment by JujuAdams** [comment]
Testing on an iPhone would be helpful, yep.

**Comment by ZigZaggh** [comment]
No problem, I just tested it with an actual iPhone 5s and a virtual machine iPhone 12Pro, and both had exactly the same result as on android and shown in the picture.

**Comment by JujuAdams** [comment]
Interesting, because I'm using Scribble for a commercial project and we regularly test on multiple iPhones (including a 5S) and have seen no issues whatsoever. This makes me think there's something else going on. Could you package up your project (.zip the entire project directory, don't use .yyz) and send it to me please?

**Comment by ZigZaggh** [comment]
Interesting, I cleaned up the project and tried to make it as simple as possible but still the same, I have added it as a zip.
[scribble text engine.zip](https://github.com/JujuAdams/Scribble/files/6141053/scribble.text.engine.zip)

**Comment by JujuAdams** [comment]
Thanks, I'll take a quick look now

**Comment by JujuAdams** [comment]
OH! Duh, I had to build a workaround for MSDF fonts because shader derivatives (which is what MSDF relies upon) aren't supported cross-platform by GM's GLSL ES version.

Anyway, this is a known issue. I'm going to look into it this week along with some other bugs.

**Comment by JujuAdams** [comment]
(Existing bug: https://github.com/JujuAdams/Scribble/issues/176)
