### ISSUE TITLE
MSDF Fonts -> single string with different border colors

### ISSUE THREAD

**Issue by morphonet** [JujuAdams/Scribble#195]
Heya,

I'd like to be able to write a string with an MSDF font that allows me to write a string with different text/border colors.

Something like :
scribble("[template_white]A white text with black borders [template_red]a red text with red borders").draw(x,  y)
or maybe
scribble("[#FFFFFF, #00000]My white text with black borders, [#0000FF, #FFFFFF]a red text with black borders").draw(x, y)
or anything that can suit the need =)

Kind of result i'd like (coming from scribble v6 with baked fonts) :
https://cdn.discordapp.com/attachments/724320324375806123/821477869313196073/unknown.png

Thanks a lot Juju!

**Comment by JujuAdams** [comment]
Can repurpose the sprite data field perhaps?

**Comment by JujuAdams** [comment]
Going to be prohibitively expensive to implement this unfortunately
