### ISSUE TITLE
Typewriter Sound

### ISSUE THREAD

**Issue by AlexInCube** [JujuAdams/Scribble#196]
I have a problem with the sound, when I set the typewriter sound, it sounds like every frame is being played. The sound itself is fine if use audio_play_sound 
I call this in Draw GUI:
element = scribble(text_NE)
element.align(fa_left,fa_top)
element.starting_format(dialogue_font, "c_black")
element.wrap(txtwidth)
element.typewriter_in(0.5, 0)
element.typewriter_sound(voice[page],-100,global.settings.audio.soundvolume,global.settings.audio.soundvolume)
element.draw(xx,yy)

**Comment by JujuAdams** [comment]
Could you verify that you mean to use `global.settings.audio.soundvolume` in your last two arguments? The last two arguments for `.typewriter_sound()` are `pitchMin` and `pitchMax`. If in doubt, set the last two arguments to `1`.

**Comment by AlexInCube** [comment]
> Could you verify that you mean to use `global.settings.audio.soundvolume` in your last two arguments? The last two arguments for `.typewriter_sound()` are `pitchMin` and `pitchMax`. If in doubt, set the last two arguments to `1`.

Sorry, I was thinking that pitch is the same as volume. But I have another problem, when I first start a dialogue in a location, the typewriter effect works correctly, but if I start the same dialogue again, the text is written all at once.

**Comment by AlexInCube** [comment]
If I start a dialogue with a different text, what I have described does not happen.

**Comment by JujuAdams** [comment]
This issue is due to caching. With the introduction of the new "typist" feature in v7.2.0 (in beta at time of writing) these sorts of issues should become a thing of the past.
