### ISSUE TITLE
Add text preview tool

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#20]
A text preview tool would be useful to test features during development, to act as a demo, and to allow for quicker production of text. It may also be useful for localisation work.

**Comment by DragoniteSpam** [comment]
Oh right, I wanted to do something like this a while ago and forgot. Mind if I work one out later today and submit a pull request?

**Comment by JujuAdams** [comment]
Not sure what form it should take yet, whether it should be an example within the project or a separate thing. I'd be keen to see what you'd suggest!

**Comment by JujuAdams** [comment]
He only went and did it the madman: https://dragonite.itch.io/scribble-text-preview-tool
