### ISSUE TITLE
Changing default font color

### ISSUE THREAD

**Issue by ZigZaggh** [JujuAdams/Scribble#201]
Hi Juju

I was wondering if it is possible to change the default font color, my application supports day/night themes, and since all font color configurations would be the same as before, just with different colors, I just want to set the "new" default color.

I know I can set the initial default color in "scribble_default_template()", and I guess I should use ".starting_format(fontName, colour)" to change the default color on command, but somehow I'm unable to understand how to use it correctly right now hehe 😅 

Sincerely

**Comment by JujuAdams** [comment]
You're almost there - change `starting_format(SCRIBBLE_DEFAULT_FONT, c_white)` to `starting_format(SCRIBBLE_DEFAULT_FONT, global.defaultColour)` and then make `global.defaultColour` whatever colour you want. Existing Scribble text elements won't be affected by this change (the default template is only set when a text element is first created) so you may need to regenerate text elements that you have stored e.g. typewriter text.

**Comment by ZigZaggh** [comment]
Thank you for the fast reply, I don't know why, but I tried it before and it crashed all the time, and got to the conclusion Scribble maybe wanted this to be done in a different way, but I'm just making sure the global.colors are initialized before the script and nothing crashes then.... of course.

Sorry about that 😄 But thank you for the help 👍

**Comment by JujuAdams** [comment]
You're welcome. Good luck with your project 😃
