### ISSUE TITLE
Checking for missing character in font

### ISSUE THREAD

**Issue by ZigZaggh** [JujuAdams/Scribble#202]
Hi Juju

Is there any way to check if a character will not be available in the font? I can see it is possible to set what character to draw in that case with "SCRIBBLE_MISSING_CHARACTER", but I want to be able to check for this.

I tried to check the scribble struct to see if there is anything I can use for this, but I did not find anything useful.

My case is that I check for the price of an IAP at Google/Apple, and get a string back with the amount and the currency symbol, I can see my font supports most currency symbols, but most likely not all.

So I would love to be able to control this scenario where the font does not support the actual symbol(or I forgot to add it), maybe there is an easy way I overlooked? 

This could also be very helpful for automatic testing.

Sincerely

**Comment by JujuAdams** [comment]
Great suggestion, I'll get that up and running now

**Comment by JujuAdams** [comment]
Implemeneted for v7,1.2

**Comment by ZigZaggh** [comment]
Wow that was fast, sounds awesome looking forward to v7.1.2, thank you for considering this feature 😃
