### ISSUE TITLE
"\n" make the double break

### ISSUE THREAD

**Issue by AlexInCube** [JujuAdams/Scribble#204]
https://cdn.discordapp.com/attachments/296278066223644683/831812629240086569/unknown.png
String:
"[c_lime]Справка о горячих клавишах\n[/c]Удалить кусок [c_aqua]Delete[/c]\nОчистить сетку [c_aqua]Ctrl + Shift + Delete[/c]\nПодвинуть сетку [c_aqua]Ctrl + Стрелочки[/c]"

I want single break instead of double, but i don`t know now do it.

**Comment by JujuAdams** [comment]
Can you recreate this in a separate project and share that with me please? I'm not able to reproduce this my end.

**Comment by AlexInCube** [comment]
download this project and in main menu you can see that https://github.com/AlexInCube/myquest

**Comment by JujuAdams** [comment]
Your font has a wide line spacing. You can see the size of your line spacing in the font window within the IDE (and if you want numbers then you can check the .yy file that GameMaker creates).

If you don't want to fix your font then you can modify the line height by using the following code:
```
scribble_glyph_set("fnt_verysmall", " ", SCRIBBLE_GLYPH.HEIGHT,  -4, true);
scribble_glyph_set("fnt_small",     " ", SCRIBBLE_GLYPH.HEIGHT, -10, true);
scribble_glyph_set("fnt_large",     " ", SCRIBBLE_GLYPH.HEIGHT, -20, true);
scribble_glyph_set("fnt_verylarge", " ", SCRIBBLE_GLYPH.HEIGHT, -20, true);
```

![image](https://user-images.githubusercontent.com/3970480/115141284-46691480-a033-11eb-85d3-8285e4ca014d.png)

**Comment by AlexInCube** [comment]
thanks
