### ISSUE TITLE
Freezing 

### ISSUE THREAD

**Issue by AeronAllen** [JujuAdams/Scribble#205]
Hey,

Firstly, thanks so much for making this! Been using it awhile and its wonderful. 

I just updated GMS2 to Version 2.3.2.558 and now every time scribble (latest version) is drawn the game will freeze for between 10-30 seconds. The game will then continue. Any advice would be hugely appreciated! 

Many Thanks,
Aeron

**Comment by JujuAdams** [comment]
This is a known issue with runtime 2.3.2.423 (packaged with IDE 2.3.2.558). YoYoGames released a hotfix today (IDE 2.3.2.560 / 2.3.2.426) runtime that addresses the problem.
