### ISSUE TITLE
7.2.0pre001 doesn't like typewriter_reset and typewriter_off

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/Scribble#209]
These functions are probably on their way out anyway, but in the meantime:

### typewriter_off

This error is thrown:

    ERROR!!! :: ############################################################################################
    ERROR in
    action number 1
    of Draw Event
    for object Object1:
    
    
    Unable to find instance for object index 1
     at gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_33954___scribble_class_element_gml_GlobalScript___scribble_class_element (line 1009) -         if (__tw_legacy_typist_use) __tw_legacy_typist_use.reset();
    ############################################################################################
    gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_33954___scribble_class_element_gml_GlobalScript___scribble_class_element (line 1009)
    gml_Object_Object1_Draw_0 (line 6) -     scrib.typewriter_off();

I notice `__tw_legacy_typist_use` is a boolean but scribble wants to call a method on it. Changing line `1009` in `__scribble_class_element` from

     if (__tw_legacy_typist_use) __tw_legacy_typist_use.reset();

to

     if (__tw_legacy_typist_use) __tw_legacy_typist.reset();

fixes it.

### typewriter_reset

is similar, but it's on line 1019 instead. It also uses the `__tw_legacy_typist_use` bool instead of the struct reference.

     __tw_legacy_typist_use.reset();

to

     __tw_legacy_typist.reset();

Not sure if you intend to wrap that in the if statement as well... or if it even matters, since it looks this is on its way out anyway. ¯\\\_(ツ)_/¯

**Comment by DragoniteSpam** [comment]
(Apparently I forgot to specify this: this is 7.2.0pre001)

**Comment by JujuAdams** [comment]
Whoops, those are just typos I think

**Comment by JujuAdams** [comment]
Will be fixed in 7.2.0pre002
