### ISSUE TITLE
Can't run the game (TwT) [I'm very new]

### ISSUE THREAD

**Issue by MarSterGames** [JujuAdams/Scribble#213]
Hellooo, I have no idea why I can't run the game. I have followed this video every step [ https://www.youtube.com/watch?v=-tnq6zo958M&t=477s ]

This is the error message I got T T
![Desktop Screenshot 2021 04 29 - 21 26 14 84](https://user-images.githubusercontent.com/83412462/116567348-be87e200-a931-11eb-89a7-e06c88d55bca.png)

I'm very thanks for your all help <3

**Comment by JujuAdams** [comment]
What version of GameMaker are you using? You can see this information in the top-right hand corner of the IDE.

**Comment by MarSterGames** [comment]
AHH, I just updated GML2 and now It's work! Thank you so much! <3

**Comment by JujuAdams** [comment]
You're welcome. Have fun!
