### ISSUE TITLE
typewriter_out causes a crash

### ISSUE THREAD

**Issue by AlexQ3D** [JujuAdams/Scribble#215]
Can be triggered in the test project, typewriter_out seems to crash the game.
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_test_typewriter:

Variable __scribble_class_element.last_char(100281, -2147483648) not set before reading it.
 at gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_26429___scribble_class_element_gml_GlobalScript___scribble_class_element (line 929) -             if (tw_backwards) _tw_char_max = 1 + last_char - start_char;
############################################################################################
gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_26429___scribble_class_element_gml_GlobalScript___scribble_class_element (line 929)
gml_Object_obj_test_typewriter_Draw_0 (line 1) - element.draw(x, y);

**Comment by JujuAdams** [comment]
Typewriter is undergoing a rewrite at the moment so this bug will likely be closed with the advice to upgrade to v7.2.0. If you'd like to try an alpha version of 7.2, please use the .yymps found [here](https://github.com/JujuAdams/Scribble/releases/tag/7.2.0pre001).

**Comment by JujuAdams** [comment]
Closing as this is no longer an issue in v7.2.0
