### ISSUE TITLE
7.2.0 - Previous typewriter events from the same text element repeat after each page break

### ISSUE THREAD

**Issue by Jakeybobble** [JujuAdams/Scribble#218]
(7.2.0 preview 001)
Example:
`"[drink,1]I am a drinker...[burp,1] [\page]I just keep drinking...[\page]And I can't stop drinking...[\page]Darn."`
The drink and burp events would run after each page break with the same delay between eachother (together with initial page delay caused by another bug?).

**Comment by JujuAdams** [comment]
Fixed in next release, probably v7.2.0pre002
