### ISSUE TITLE
[Feature Request] in-line sprites referenced from a variable

### ISSUE THREAD

**Issue by Jeremiah-DigitOwl** [JujuAdams/Scribble#220]
Example: `scribble("This: [global.sprite,0] is an in-line sprite from a variable!").draw();`

Some usecases:
`scribble("Wizard uses [current_element,0] spell on you!");`
`scribble("Use [global.button_sprite,0] to jump.");`

Could be handy I think!

EDIT: 
We can do `scribble("This: [" + sprite_get_name(global.sprite) + ",0] is an in-line sprite from a variable!");`
But that doesn't feel as natural. So this would be more of a convenience feature.

**Comment by JujuAdams** [comment]
Not gonna happen in this form. I'd like to introduce macros that'll achieve similar things, but it won't ever be direct access to variables
