### ISSUE TITLE
Add 'count' parameter to [nbsp]

### ISSUE THREAD

**Issue by shdwcat** [JujuAdams/Scribble#221]
E.g.: `[nbsp,7]` to insert 7 non-breaking spaces

**Comment by JujuAdams** [comment]
I'm very curious what the use-case is here, but there's no harm in wedging this in

**Comment by shdwcat** [comment]
Dragonite's suggestion is actually maybe more reasonable than my case 🤣

Basically, what I've got is a UI screen that displays any text in a rectangle. This particular text (which comes from a yarn script), I would like to be centered* in the rectangle, so I use `[pin_center]`. Except, actually, the text has a symbol in the middle like: the `|` here: `this|is an example` . So what I *actually* want is to offset the text to the right a bit, so that the `|` is centered in the rectangle.

So right now, I'm actually using 17 `[nbsp]`s to achieve that :P

On reflection, a more generally useful solution would be for something like `[offset_x,200]` to be able to arbitrarily position text fragments on the screen from my Yarn files. I don't know if that's too much for the shader though.

**Comment by JujuAdams** [comment]
I did write that feature into a fork of Scribble for a commercial game this time last year. With the new parser I'm not sure this is possible any more... but I will look into it regardless as it has been useful in the past.

**Comment by JujuAdams** [comment]
Implemented for v7.2.0pre003, also opened up #228 for the general solution using manual x/y positioning
