### ISSUE TITLE
Divide by zero error when first two arguments of .animation_blink are zero

### ISSUE THREAD

**Issue by chesrowe** [JujuAdams/Scribble#223]
Obviously these values should never be zero together but the code should prevent the crash in the event someone was to accidentally set it that way.

version 7.1.2, 2021-04-16
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_conUi:

DoMod :: Divide by zero
 at gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_27331___scribble_class_element_gml_GlobalScript___scribble_class_element (line 919) -         animation_blink_state = (((animation_time + animation_blink_time_offset) mod (animation_blink_on_duration + animation_blink_off_duration)) < animation_blink_on_duration);
############################################################################################
gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_27331___scribble_class_element_gml_GlobalScript___scribble_class_element (line 919)
gml_Object_obj_conUi_Draw_64 (line 62) -                                                         _element.text.draw(_textX, _textY);

**Comment by JujuAdams** [comment]
Thanks Ches! I'll take a look at this when I can

**Comment by JujuAdams** [comment]
Fixed for the next release, probably v7.2.0pre002
