### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Spectralniy** [JujuAdams/Scribble#225]
![error](https://user-images.githubusercontent.com/39821657/122779145-48ab5180-d2b6-11eb-9218-2ecde4339485.png)
I was following this video https://youtu.be/-tnq6zo958M step by step, but when i try to launch my game it just crashes.

Code:
Create:
**scribble_font_add("basicFont");**
Draw:
**scribble("some text is here").draw(x-10, y-10);**

Adding "scribble_font_add_all();" or "scribble_font_set_default();" doesn't help.
Changing instance creation order doesn't help.
Regenerating the font doesn't help.
Adding any more Included files doesn't help.
Version is up to date - v2.3.2.560

Thanks in advance.

**Comment by JujuAdams** [comment]
What version of Scribble are you using?

**Comment by Spectralniy** [comment]
> What version of Scribble are you using?

7.2.0 preview 001 https://github.com/JujuAdams/Scribble/releases/tag/7.2.0pre001

**Comment by JujuAdams** [comment]
Could you check what the debug output says please? You should see some messages that Scribble has created, these might offer a clue as to what's happening

**Comment by Spectralniy** [comment]
Okay
**Debug mode:**
![Screenshot_1](https://user-images.githubusercontent.com/39821657/122896111-6b3e7880-d351-11eb-96da-f3a9fe839e6a.png)


**Just a normal output:**
`"cmd"  /c subst Z: "D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE"

elapsed time 00:00:00.1801115s for command "cmd" /c subst Z: "D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE" started at 06/22/2021 11:55:24
"cmd"  /c subst Y: "D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP"

elapsed time 00:00:00.0496900s for command "cmd" /c subst Y: "D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP" started at 06/22/2021 11:55:25
"cmd"  /c subst X: "D:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2.3.2.426"

elapsed time 00:00:00.0501871s for command "cmd" /c subst X: "D:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2.3.2.426" started at 06/22/2021 11:55:25
"D:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2.3.2.426/bin/Igor.exe"  -j=8 -options="D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run

Loaded Macros from D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Blueprints_DB57C448\macros.json
Options: X:/bin\platform_setting_defaults.json
Options: D:\Users\Spectralniy\AppData\Roaming/GameMakerStudio2\lev.batman_2781586\local_settings.json
Options: D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Blueprints_DB57C448\targetoptions.json
Setting up the Asset compiler
X://bin/GMAssetCompiler.exe  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="Blueprints" /td="Y:/" /cd="Z:/Blueprints_DB57C448" /zpuf="D:\Users\Spectralniy\AppData\Roaming/GameMakerStudio2\lev.batman_2781586" /m=windows /tgt=64 /nodnd /cfg="Default" /o="Y:/Blueprints_6DC15D2C_VM" /sh=True /optionsini="Y:/Blueprints_6DC15D2C_VM\options.ini"  /cvm /baseproject="X:/BaseProject\BaseProject.yyp" "D:\Users\Spectralniy\Documents\GameMakerStudio2\Blueprints\Blueprints.yyp" /preprocess="Z:/Blueprints_DB57C448"
We have a Zeus Project!
Found Project Format 2
ProjectFileWatcher:StartWatching:D:\Users\Spectralniy\Documents\GameMakerStudio2\Blueprints
Started: 6/22/2021 11:55:29 AM
Finished: 6/22/2021 11:55:30 AM
Diff: 00:00:01.4099182
Loaded Project: Blueprints
finished.
Release build
Options: Z:/Blueprints_DB57C448\ExtensionOptions.json
OptionsIni
Options: Z:/Blueprints_DB57C448\PlatformOptions.json
[Compile] Run asset compiler
X://bin/GMAssetCompiler.exe  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="Blueprints" /td="Y:/" /cd="Z:/Blueprints_DB57C448" /zpuf="D:\Users\Spectralniy\AppData\Roaming/GameMakerStudio2\lev.batman_2781586" /m=windows /tgt=64 /nodnd /cfg="Default" /o="Y:/Blueprints_6DC15D2C_VM" /sh=True /optionsini="Y:/Blueprints_6DC15D2C_VM\options.ini"  /cvm /baseproject="X:/BaseProject\BaseProject.yyp" "D:\Users\Spectralniy\Documents\GameMakerStudio2\Blueprints\Blueprints.yyp" /bt=run /rt=vm /64bitgame=false
Compile Constants...finished.
Remove DnD...finished.
Compile Scripts...finished.
Compile Rooms...finished.
Compile Objects...finished.
Compile Timelines...finished.
Compile Triggers...finished.
Compile Extensions...finished.
Global scripts...finished.
finished.
collapsing enums.
Final Compile...finished.
Saving IFF file... Y:/Blueprints_6DC15D2C_VM\Blueprints.win
Writing Chunk... GEN8
option_game_speed=60
Writing Chunk... OPTN
Writing Chunk... LANG
Writing Chunk... EXTN
Writing Chunk... SOND
Writing Chunk... AGRP
Writing Chunk... SPRT
Writing Chunk... BGND
Writing Chunk... PATH
Writing Chunk... SCPT
Writing Chunk... GLOB
Writing Chunk... SHDR
Writing Chunk... FONT
Writing Chunk... TMLN
Writing Chunk... OBJT
Writing Chunk... ACRV
Writing Chunk... SEQN
Writing Chunk... TAGS
Writing Chunk... ROOM
Writing Chunk... DAFL
Writing Chunk... EMBI
Writing Chunk... TPAGE
Texture Group - Default
Writing Chunk... TGIN
Writing Chunk... CODE
Writing Chunk... VARI
Writing Chunk... FUNC
Writing Chunk... STRG
Writing Chunk... TXTR
0 Compressing texture... writing texture texture_0.png... 
1 Compressing texture... writing texture texture_1.png... 
2 Compressing texture... writing texture texture_2.png... 
3 Compressing texture... writing texture texture_3.png... 
4 Compressing texture... writing texture texture_4.png... 
5 Compressing texture... writing texture texture_5.png... 
Writing Chunk... AUDO
Writing Chunk... SCPT
Writing Chunk... DBGI
Writing Chunk... INST
Writing Chunk... LOCL
Writing Chunk... DFNC
Writing Chunk... STRG
Stats : GMA : Elapsed=5280.8102
Stats : GMA : sp=62,au=8,bk=4,pt=0,sc=354,sh=6,fo=1,tl=0,ob=31,ro=10,da=1,ex=0,ma=375,fm=0xD000329D7CFE22A0
DoSteam
Igor complete.
[Run] Run game
Options: Z:/Blueprints_DB57C448\MainOptions.json
Y:\Blueprints_6DC15D2C_VM\Runner.exe  -game "Y:/Blueprints_6DC15D2C_VM\Blueprints.win"
Setting scheduler resolution to 1
Attempting to set gamepadcount to 12
DirectX11: Using hardware device
Collision Event time(microsecs)=6
Scribble: Welcome to Scribble by @jujuadams! This is version 7.2.0pre001, 2021-04-19
Total memory used = 24310489(0x0172f2d9) bytes
**********************************.
Entering main loop.
**********************************.
ERROR!!! :: ############################################################################################
ERROR in
action number 1
of Draw Event
for object oText:


Push :: Execution Error - Variable Index [0] out of range [0] - -1.pages_array(100805,0)
 at gml_Script_anon___scribble_class_model_gml_GlobalScript___scribble_class_model_1726___scribble_class_model_gml_GlobalScript___scribble_class_model (line 61) -         var _page_data = pages_array[_element.__page];
############################################################################################
gml_Script_anon___scribble_class_model_gml_GlobalScript___scribble_class_model_1726___scribble_class_model_gml_GlobalScript___scribble_class_model (line 61)
gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_22542___scribble_class_element_gml_GlobalScript___scribble_class_element (line 909) -         _model.draw(_x, _y, self);
gml_Object_oText_Draw_0 (line 2) - scribble("some text is here").draw(x-10, y-10);



Y:\Blueprints_6DC15D2C_VM\Runner.exe exited with non-zero status (1)
elapsed time 00:00:17.4902264s for command "D:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2.3.2.426/bin/Igor.exe" -j=8 -options="D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 06/22/2021 11:55:25
"cmd"  /c subst Z: /d

elapsed time 00:00:00.0952000s for command "cmd" /c subst Z: /d started at 06/22/2021 11:55:43
"cmd"  /c subst Y: /d

elapsed time 00:00:00.0946881s for command "cmd" /c subst Y: /d started at 06/22/2021 11:55:43
"cmd"  /c subst X: /d

elapsed time 00:00:00.1838251s for command "cmd" /c subst X: /d started at 06/22/2021 11:55:43
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.`

**Comment by JujuAdams** [comment]
Fascinating! I have no idea why this is happening! I'm about to release another beta build of 7.2.0 so I'll put in some debug stuff to try to figure this out.

**Comment by Spectralniy** [comment]
> Fascinating! I have no idea why this is happening! I'm about to release another beta build of 7.2.0 so I'll put in some debug stuff to try to figure this out.

Hahahahah. You're welcome. Don't rush yourself too much, i can wait for as long as needed, it's not much of a problem.

**Comment by JujuAdams** [comment]
Released preview 002 - https://github.com/JujuAdams/Scribble/releases/tag/7.2.0pre002

I've left some debug behaviours on which should help narrow down the cause of the problem. Please update to 7.2.0pre002 (best option is to completely wipe the existing library and reimport), re-run your project, and see what happens. If you get a crash again, please copy-paste your debug log again

If we can't figure out what's going on then I might have to take a look at your project specifically to see what's up

**Comment by Spectralniy** [comment]
> Released preview 002 - https://github.com/JujuAdams/Scribble/releases/tag/7.2.0pre002
> 
> I've left some debug behaviours on which should help narrow down the cause of the problem. Please update to 7.2.0pre002 (best option is to completely wipe the existing library and reimport), re-run your project, and see what happens. If you get a crash again, please copy-paste your debug log again
> 
> If we can't figure out what's going on then I might have to take a look at your project specifically to see what's up

Seems that "global.__scribble_font_data" is broken.

![Debug text](https://user-images.githubusercontent.com/39821657/122931670-c5513500-d375-11eb-8a33-a1870c242255.png)
![Error at the start of the game](https://user-images.githubusercontent.com/39821657/122931673-c5e9cb80-d375-11eb-90fd-aad917ed458d.png)

**Output:**
"cmd"  /c subst Z: "D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE"

elapsed time 00:00:00.0495313s for command "cmd" /c subst Z: "D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE" started at 06/22/2021 16:07:56
"cmd"  /c subst Y: "D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP"

elapsed time 00:00:00.0406208s for command "cmd" /c subst Y: "D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP" started at 06/22/2021 16:07:56
"cmd"  /c subst X: "D:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2.3.2.426"

elapsed time 00:00:00.0398208s for command "cmd" /c subst X: "D:\ProgramData\GameMakerStudio2\Cache\runtimes\runtime-2.3.2.426" started at 06/22/2021 16:07:56
"D:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2.3.2.426/bin/Igor.exe"  -j=8 -options="D:\Users\Spectralniy\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run

Loaded Macros from D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Blueprints_DB57C448\macros.json
Options: X:/bin\platform_setting_defaults.json
Options: D:\Users\Spectralniy\AppData\Roaming/GameMakerStudio2\lev.batman_2781586\local_settings.json
Options: D:\Users\Spectralniy\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Blueprints_DB57C448\targetoptions.json
Setting up the Asset compiler
X://bin/GMAssetCompiler.exe  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="Blueprints" /td="Y:/" /cd="Z:/Blueprints_DB57C448" /zpuf="D:\Users\Spectralniy\AppData\Roaming/GameMakerStudio2\lev.batman_2781586" /m=windows /tgt=64 /nodnd /cfg="Default" /o="Y:/Blueprints_53BF9B48_VM" /sh=True /optionsini="Y:/Blueprints_53BF9B48_VM\options.ini"  /cvm /baseproject="X:/BaseProject\BaseProject.yyp" "D:\Users\Spectralniy\Documents\GameMakerStudio2\Blueprints\Blueprints.yyp" /preprocess="Z:/Blueprints_DB57C448"
We have a Zeus Project!
Found Project Format 2
ProjectFileWatcher:StartWatching:D:\Users\Spectralniy\Documents\GameMakerStudio2\Blueprints
Started: 6/22/2021 4:07:58 PM
Finished: 6/22/2021 4:07:59 PM
Diff: 00:00:01.0424107
Loaded Project: Blueprints
finished.
Release build
Options: Z:/Blueprints_DB57C448\ExtensionOptions.json
OptionsIni
Options: Z:/Blueprints_DB57C448\PlatformOptions.json
[Compile] Run asset compiler
X://bin/GMAssetCompiler.exe  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="Blueprints" /td="Y:/" /cd="Z:/Blueprints_DB57C448" /zpuf="D:\Users\Spectralniy\AppData\Roaming/GameMakerStudio2\lev.batman_2781586" /m=windows /tgt=64 /nodnd /cfg="Default" /o="Y:/Blueprints_53BF9B48_VM" /sh=True /optionsini="Y:/Blueprints_53BF9B48_VM\options.ini"  /cvm /baseproject="X:/BaseProject\BaseProject.yyp" "D:\Users\Spectralniy\Documents\GameMakerStudio2\Blueprints\Blueprints.yyp" /bt=run /rt=vm /64bitgame=false
Compiling Shader Shader___shd_scribble_bake_outline... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_outline... compiled with ps_4_0 (optimised)
Compiling Shader Shader___shd_scribble... compiled with vs_4_0 (optimised)
Compiling Shader Shader___shd_scribble... compiled with ps_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_test... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_test... compiled with ps_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_msdf... compiled with vs_4_0 (optimised)
Compiling Shader Shader___shd_scribble_msdf... compiled with ps_4_0_level_9_1 (optimised)
Compile Constants...finished.
Remove DnD...finished.
Compile Scripts...finished.
Compile Rooms...finished.
Compile Objects...finished.
Compile Timelines...finished.
Compile Triggers...finished.
Compile Extensions...finished.
Global scripts...finished.
finished.
collapsing enums.
Final Compile...finished.
Saving IFF file... Y:/Blueprints_53BF9B48_VM\Blueprints.win
Writing Chunk... GEN8
option_game_speed=60
Writing Chunk... OPTN
Writing Chunk... LANG
Writing Chunk... EXTN
Writing Chunk... SOND
Writing Chunk... AGRP
Writing Chunk... SPRT
Writing Chunk... BGND
Writing Chunk... PATH
Writing Chunk... SCPT
Writing Chunk... GLOB
Writing Chunk... SHDR
Writing Chunk... FONT
Writing Chunk... TMLN
Writing Chunk... OBJT
Writing Chunk... ACRV
Writing Chunk... SEQN
Writing Chunk... TAGS
Writing Chunk... ROOM
Writing Chunk... DAFL
Writing Chunk... EMBI
Writing Chunk... TPAGE
Texture Group - Default
Writing Chunk... TGIN
Writing Chunk... CODE
Writing Chunk... VARI
Writing Chunk... FUNC
Writing Chunk... STRG
Writing Chunk... TXTR
0 Compressing texture... writing texture texture_0.png... 
1 Compressing texture... writing texture texture_1.png... 
2 Compressing texture... writing texture texture_2.png... 
3 Compressing texture... writing texture texture_3.png... 
4 Compressing texture... writing texture texture_4.png... 
5 Compressing texture... writing texture texture_5.png... 
Writing Chunk... AUDO
Writing Chunk... SCPT
Writing Chunk... DBGI
Writing Chunk... INST
Writing Chunk... LOCL
Writing Chunk... DFNC
Writing Chunk... STRG
Stats : GMA : Elapsed=25637.7913
Stats : GMA : sp=62,au=8,bk=4,pt=0,sc=344,sh=7,fo=1,tl=0,ob=31,ro=10,da=1,ex=0,ma=367,fm=0xD000329D7CFE22B0
DoSteam
Igor complete.
[Run] Run game
Options: Z:/Blueprints_DB57C448\MainOptions.json
Y:\Blueprints_53BF9B48_VM\Runner.exe  -game "Y:/Blueprints_53BF9B48_VM\Blueprints.win"
Setting scheduler resolution to 1
Attempting to set gamepadcount to 12
DirectX11: Using hardware device
Collision Event time(microsecs)=9

**Comment by JujuAdams** [comment]
That looks like an import issue - `global.__scribble_font_data` is created on boot by `__scribble_init()`. I bet if you check that script then it'll be blank. GMS2 sometimes has problems importing local packages for some reason. Please re-import and try again (and cross your fingers!)

**Comment by Spectralniy** [comment]
Yooooooo. It works. Crossed fingers helped :D
![image](https://user-images.githubusercontent.com/39821657/122974326-db252100-d39a-11eb-858c-01b66b05e074.png)
Thank you. I cannot even express, how much you helped.

**Comment by JujuAdams** [comment]
eyyy nice one! Have fun making your game!
