### ISSUE TITLE
why glyph not affect to a sprite in text

### ISSUE THREAD

**Issue by AlexInCube** [JujuAdams/Scribble#229]
why glyph not affect to a sprite in text
i use this in init:
scribble_glyph_set("fnt_small",     " ", SCRIBBLE_GLYPH.HEIGHT, -10, true);
and this in text:
#macro DIALOGUE_MACRO_TRADE "{"+find_keyword("trading")+"[spr_dialogue_icon_trade]"+"} "

but sprite drawed above the text, how to fix this?

**Comment by JujuAdams** [comment]
How are you drawing this string? What is the specific Scribble command you're using? Are you changing the minimum/maximum line height in any other way?

**Comment by AlexInCube** [comment]
i use this scribble(txt).draw(0,0). i not changed minimum and maximum height. if I remove scribble_glyph_set, the sprites will be drawn normally.

**Comment by JujuAdams** [comment]
Closed due to inactivity.
