### ISSUE TITLE
Shadow without MSDF

### ISSUE THREAD

**Issue by batblaster** [JujuAdams/Scribble#236]
Is possible to make a shadow using a command like for MSDF fonts but with normal fonts, with a shader should be same.
There is already a command?

**Comment by OminousGiggle** [comment]
I wasn't able to find a command, but I did find a method of doing this.
Essentially you draw the same text twice, but with an offset.
My draw text ended up looking like this.
I used the .fog to create the black drop shadow.
`
//Draw main text body
textbox_element.draw(x1+2, y1+2)
textbox_element.fog(c_black,0)
textbox_element.draw(x1, y1)
textbox_element.fog(c_black,1)
`

**Comment by batblaster** [comment]
Oh i know it, i did but you print 2 times and it uses resources, if you add a shader and considered almost all part of the engine works with shader could be pretty easy to add a shadow option without need to print 2 times or more.
Anyway thanks for the help.

**Comment by JujuAdams** [comment]
Implemented for v8
