### ISSUE TITLE
Scaled text is always fa_top

### ISSUE THREAD

**Issue by AvioxArcade** [JujuAdams/scribble#24]
First off, scribble is awesome!
I was messing around with the features, and I noticed scaling text in the middle of a line always results in vertical alignment to be "fa_top", regardless of any align settings provided.
![image](https://user-images.githubusercontent.com/61194078/74743062-c2987a00-522d-11ea-9ce0-4ce12f583df8.png)

Is there any way to fix this?

**Comment by JujuAdams** [comment]
Hiya, I'll take a look at this tonight.

**Comment by JujuAdams** [comment]
This has been fixed on `master` in version 5.3.3b. You can download the [.yymp here](https://github.com/JujuAdams/scribble/releases/tag/5.3.3b).
