### ISSUE TITLE
Custom Scribble typewriter events are called twice if they immediately follow a manual page break tag

### ISSUE THREAD

**Issue by maxjmcintyre** [JujuAdams/Scribble#242]
Yesterday I upgraded to GMS 2.3 and in turn updated Scribble to version 7.1.2. After carefully translating my old code to the new methods way of doing things my game was running almost perfectly as it was before I did this update. The one exception is that I often start many pages with one or more scribble typewriter events, something like:
											
```
+ "[/page][portrait,Charles]Indeed sir. Your devotion to this land knows no bounds."
+ "[/page][portrait,Nezel]As much as it disturbs me, you all are an extension of my position under the king. Serve me well as I serve him well. You will be my eyes, my ears, and my nose to the far reaches of the kingdom."
+ "[/page][portrait,Vant][callOutsideScribble,scr_outside_scribble_teleport_npc_in,Vant,"+inst_2EE2733C.flag+",-1,-1]Over the top as usual I see, eh Nezel?"
+ "[/page][portrait,Nezel]Hrmph... In either case, knowing your place and following orders is vastly important. The possibility of death is very real. Is it not Vant?"

```
In this excerpt of one of my dialog strings the portrait scribble event I made gets called twice. Once as the page ends and a second time when actually starting the next page. This issue happens for not only the immediate next typewriter event called just after the /page tag, but for all typewriter events immediately called after the /page tag. E.g. this line -

`+ "[/page][portrait,Vant][callOutsideScribble,scr_outside_scribble_teleport_npc_in,Vant,"+inst_2EE2733C.flag+",-1,-1]Over the top as usual I see, eh Nezel?"
`
- calls portrait(Vant) and callOutsideScribble(scr_outside_scribble_teleport_npc_in,Vant,"+inst_2EE2733C.flag+",-1,-1) twice each.

Thank you for Scribble and all of your other amazing contributions to the GameMaker community!

**Comment by JujuAdams** [comment]
Fixed in v8
