### ISSUE TITLE
typewriter_function's character position argument doesn't account for text formatting

### ISSUE THREAD

**Issue by stoozey** [JujuAdams/Scribble#243]
when using [`.typewriter_function()`](https://github.com/JujuAdams/Scribble/wiki/scribble()-Methods#typewriter_functionfunction) the text position argument can become wrong if any formatting is done in the string itself.
if my text is `scribble [wave]is[/wave] very very good`, 14 characters will not be passed in (instead you'll get the characters _from_ the format string). the final character to get put into the function would actually be " " (the space after is) instead of "d" (from "good").

**Comment by JujuAdams** [comment]
Not a bug - the typewriter position is not meant to be accurate compared to the input string.
