### ISSUE TITLE
Multiple separate scribble elements with the same text all will get overwritten if any of them use .overwrite

### ISSUE THREAD

**Issue by OminousGiggle** [JujuAdams/Scribble#247]
If multiple scribble elements ever have identical text and you use .overwrite on any one of the text elements, all of them will get overwritten. This includes if the initial text is stored in separate variables.

Repro:
1. In a single object, create two scribble elements with identical text
2. Use .overwrite to change one of the scribble elements
3. Note both scribble elements end up getting overwritten

[ScribbleOverwrite.zip](https://github.com/JujuAdams/Scribble/files/7494080/ScribbleOverwrite.zip)

**Comment by JujuAdams** [comment]
Not a bug. Use the unique ID feature to differentiate text elements.
