### ISSUE TITLE
8.0.0 Alpha 5 - typist does not actually have .associate() function

### ISSUE THREAD

**Issue by shdwcat** [JujuAdams/Scribble#250]
similar to the last one, `__associate` exists but the public version does not

**Comment by JujuAdams** [comment]
Documentation is in error, this is deliberate.

**Comment by shdwcat** [comment]
No, I was trying to use it to fix an issue, but it turned out to be the multiple `.draw()` calls with the same typist that were the cause of the problem

**Comment by JujuAdams** [comment]
Fab, thanks for getting back to me. I'll remove this function from documentation in that case.
