### ISSUE TITLE
scribble_cache_group_flush not flushing

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/scribble#29]
On the line (currently 39) where the script checks `_scribble_array[__SCRIBBLE.FREED]` as part of determining whether a scribble should be cleared or not, it looks like it should check the opposite `!_scribble_array[__SCRIBBLE.FREED]` instead, since the scribble otherwise won't enter the freed state to begin with and vertex buffers will never actually be deleted when you ask them to.

Next, the scribble doesn't get removed from the global cache map so if you try to create a scribble with a string that has already been flushed it will return an array with an already-deleted vertex buffer and nag you about drawing an invalid scribble. Adding `ds_map_delete(global.__scribble_global_cache_map, _list[| _i]);` to line 35 after the scribble has been fetched from the global map seems to take care of this, but I don't know if there are any other parts to this I'm missing so far.

**Comment by JujuAdams** [comment]
Thanks for the error, even if it's a stoopid mistake. I'll try to get this fixed tomorrow evening.

**Comment by JujuAdams** [comment]
Implemented a bunch of fixes off the back of this ticket, hopefully it doesn't break anything!
