### ISSUE TITLE
typist.get_state() returns value 2.0 when text is still fading out

### ISSUE THREAD

**Issue by NagaseIori** [JujuAdams/Scribble#303]
When text is fading out but still visible the function `get_state()` returns value 2.0, which should be smaller than 2.0 according to [Scribble Docs](https://www.jujuadams.com/Scribble/#/latest/typist-methods?id=get_state)?

**Comment by JujuAdams** [comment]
Thanks for reporting this, I'll take a look when I get the chance.

**Comment by JujuAdams** [comment]
Cannot reproduce. Could you share some code please?

**Comment by ajcxsu** [comment]
Sure.
GMS2 version IDE v2.3.7.606 Runtime v2.3.7.476
Scribble version 8.0.1 beta 4
I created a new project and managed to reproduce this problem using this object.
```
#event properties (no comments/etc. here are saved)
parent_index = -1;
uses_physics = false;

#event create 
typist = scribble_typist();
text = "test test test test.!!!"

typist.out(0.2, 10);

#event step 

if(typist.get_state() == 2.0)
	instance_destroy();

#event draw 


scribble(text)
.align(0, 0)
.starting_format("fTest", c_white)
.draw(x, y, typist);
```

**Comment by ajcxsu** [comment]
> Cannot reproduce. Could you share some code please? Please also tell me what version of GameMaker and what version of Scribble you are using.

Sure.
GMS2 version IDE v2.3.7.606 Runtime v2.3.7.476
Scribble version 8.0.1 beta 4
I created a new project and managed to reproduce this problem using this object.
```
#event properties (no comments/etc. here are saved)
parent_index = -1;
uses_physics = false;

#event create 
typist = scribble_typist();
text = "test test test test.!!!"

typist.out(0.2, 10);

#event step 

if(typist.get_state() == 2.0)
	instance_destroy();

#event draw 


scribble(text)
.align(0, 0)
.starting_format("fTest", c_white)
.draw(x, y, typist);
```

**Comment by JujuAdams** [comment]
Fixed https://github.com/JujuAdams/Scribble/commit/fc690a95aef54094ffdddc625ca51878bb6f4757
