### ISSUE TITLE
fa_middle vertical alignment causes some fonts to turn spooky

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/Scribble#304]
It seems that scribble shares my opinion that i's never too early to be getting into the Halloween spirit.

![image](https://user-images.githubusercontent.com/7087495/150172254-079d0547-059a-4f04-bee7-430f684f39db.png)

Setting the vertical alignment to `fa_middle` causes some characters in some fonts (although apparently not all) to be misaligned. This seems to be caused by rounding errors in the positions of certain glyphs. `floor`ing (...or `ceil`ing, or `round`ing) the bounds of the area scribble lives in (lines 7 and 8 of the `__SCRIBBLE_GEN_PAGE_POP` macro) seem to fix the issue.

    _page_data.__min_y       = (__valign == fa_middle)? -floor(_line_y/2) : ((__valign == fa_bottom)? -_line_y :       0);\
    _page_data.__max_y       = (__valign == fa_middle)?  floor(_line_y/2) : ((__valign == fa_bottom)?        0 : _line_y);\

I haven't seen the same issue with horizontal alignment, although to be fair I don't use horizontal alignment nearly as much as vertical, so maybe it's got a similar issue buried somewhere.

**Comment by JujuAdams** [comment]
Thanks for reporting this, I'll take a look when I get the chance.

**Comment by JujuAdams** [comment]
Note to self: noticeable using Segoe UI at pt 12

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/259e31f1eb39a258e78a6e06d341b7e9e08138c5
