### ISSUE TITLE
Add outline functionality

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#31]
Outlining text is a common operation for both pixel art and hires fonts. Scribble should support this.

There are many ways to achieve the effect including:

1. Layered draw calls (in our case, layered quads)
2. Pre-outlining a spritefont
3. Caching text onto a surface and layering the draw call
4. Signed-distance field font
5. Edge detection shader

**Comment by DragoniteSpam** [comment]
Funny you mention this, I was thinking about this approximately . . . this morning. Neat.

**Comment by JujuAdams** [comment]
A few people have requested but honestly I'm not sure what the best option is. They all have drawbacks!

**Comment by JujuAdams** [comment]
I think generating our own texture page for each outlined font would be the best option. This means fonts would need to be processed on boot.

**Comment by JujuAdams** [comment]
Planned for v6

**Comment by JujuAdams** [comment]
Implemented for v6

**Comment by JujuAdams** [comment]
Reopening becaue v6 has been indefinitely delayed. 2.3.0 doesn't seem to help Scribble much in its current form and I'd like to get features slated for v6 out before 2.3.0 goes into stable.

**Comment by JujuAdams** [comment]
Backported to GMS2.2.5
