### ISSUE TITLE
Applying any formatting option to a hebrew string which contains a hyphen makes the sentence render out of order

### ISSUE THREAD

**Issue by ThePounceThatWasPromised** [JujuAdams/Scribble#312]
Say I have a hebrew string containing a hyphen (rather common in hebrew for instance in the word for human בן-אדם) if I just render this text using scribble normally it works fine and appears in sequence, but if I add any bracketed option (and it doesn't matter which, or even if it's a valid one, I tested it) the sentence will be rendered with the part coming before the hyphen showing up after the end of the word, so say the string "[wave]בן-אדם" will show as "אדם- בן"

**Comment by JujuAdams** [comment]
I can see the cause of this bug. Please use the `.right_to_left()` text element method in the meantime to work around the issue.

**Comment by JujuAdams** [comment]
I fixed the issue last night and it'll be included in the next beta. In the meantime, [this simple fix](https://github.com/JujuAdams/Scribble/commit/d3fdc21869009c9c65d61df2522c23af21ac9bdf) might also work for you.
