### ISSUE TITLE
on_last_page Crash

### ISSUE THREAD

**Issue by JonathanHackerCG** [JujuAdams/Scribble#314]
``on_last_page()`` crashes due to reference to ``get_pages()`` which is deprecated. Should be ``get_page_count()`` instead.

This is v8.0.1 Beta 7. Maybe this feature is still incomplete.

**Comment by JujuAdams** [comment]
Whoops... thank you! I shall look into this now.

**Comment by JujuAdams** [comment]
Fixed https://github.com/JujuAdams/Scribble/commit/51ca49d91bb661a5445e61056b821e331fc00d8b
