### ISSUE TITLE
Events not triggering if no other text present.

### ISSUE THREAD

**Issue by okocim** [JujuAdams/Scribble#319]
If a string contains only an event, and no other characters, typist will not trigger the event. Spaces do not work either, there must be some sort of typeable character present.

**Comment by JujuAdams** [comment]
Thanks for reporting this bug. I'll take a look when I can (probably over the weekend)

**Comment by okocim** [comment]
I had a bit time to investigate - it seems like __uses_standard_font isn't being set to true which is causing the issue. A quick fix for me is initializing it as true  (__uses_standard_font = true; in __scribble_class_model).

Hoping this helps you save some time and thank you!

**Comment by JujuAdams** [comment]
That was indeed very useful!

The "proper" fix can be found here: https://github.com/JujuAdams/Scribble/commit/6f788e166fd020e7b63ae5c97764b07dc3e69bc3

What was happening was that typists weren't executing their tick code if no printable glyphs were found in the input string. Fun little bug that one, congrats on finding it
