### ISSUE TITLE
Error when using [cycle] in latest version

### ISSUE THREAD

**Issue by austensatterlee** [JujuAdams/Scribble#323]
When using `[cycle,...]txt[/cycle]` with the latest version, a crash occurs on this line: https://github.com/JujuAdams/Scribble/blob/c62b5a6655b7277984a7de4567776fbbbae006dd/scripts/__scribble_gen_2_parser/__scribble_gen_2_parser.gml#L551
It looks like it's trying to access `__scribble_effects_slash[? "cycle"]`, where it should probably be accessing `__scribble_effects_slash[? "/cycle"]`. I was able to confirm making that change fixed the issue for me.

The specific failure occurred for me when calling `scribble(_str).get_width()`, where `_str` was `[wave][shake][cycle,40,90,150,190]Vanessa Bench[/cycle][/shake][/wave][delay,500]`.

Apologies if this is somehow on my end, but let me know your thoughts or if you're able to reproduce.

And I feel it's obligatory to thank you for this awesome library. This and Chatterbox have made development so much easier and more fun for me.

**Comment by JujuAdams** [comment]
Whoops, yep, that's a typo. If you know how, could you make a pull request for that please?

**Comment by JujuAdams** [comment]
Fixed #325
