### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by nickmuse** [JujuAdams/Scribble#326]
Scribble imports with some Syntax Errors

![scribble_syntax_errors](https://user-images.githubusercontent.com/17624833/157113520-1c4e760b-773e-4500-98e3-f10d64bb7c27.PNG)

They're all "only referenced once" errors, so they really don't impact anything.

However, I find that they do make the Syntax Errors tab harder to use for keeping an eye on my own code.

**Comment by JujuAdams** [comment]
This is due to those methods not being used in your project. There are a handful of font data-related variables that also exhibit the same problem.

Regardless, this is a GameMaker issue and not one that is solvable my end.
