### ISSUE TITLE
Scribble_autotype_set_sound script only working once and not playing the sound again 

### ISSUE THREAD

**Issue by OmegaGamingHunters** [JujuAdams/scribble#33]
I have scribble being used in a text object that is called on whenever the player hits the enter key near an NPC. When I call Text object the first time the scribble_autotype_set_sound script works and the sound plays but when scribble is called for the second time the text object the scribble_autotype_set_sound script won't work, it just stays silent, even though its being called. It only works the first time I boot the game up.

**Comment by JujuAdams** [comment]
Heya, thanks for reporting this bug. It's been a busy week but hopefully I can find time to address this tomorrow.

**Comment by JujuAdams** [comment]
Fixed in 5.4.3
