### ISSUE TITLE
Callback when typist is finished

### ISSUE THREAD

**Issue by CarsonKompon** [JujuAdams/Scribble#344]
Would be cool if you could do something like
```gml
typist = scribble_typist();
typist.function_on_finish(function(){
    show_debug_message("The textbox finished!");
    // Advance the next dialogue box automatically in 4 seconds
    alarm[0] = room_speed * 4;
});
```

A `function_on_finish(func)` would make automating things SUPER easy :)

**Comment by FaultyFunctions** [comment]
Was about to make a feature request for this, but saw this first! For my use case, I would use this for when to let a portrait know to switch out of its "talking" sprite. This is still pretty easily accomplished without a callback, but would be much easier with.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/08c5c1c23faf0b2447ecafe248825ef04b930500
