### ISSUE TITLE
Add support for sound pitches

### ISSUE THREAD

**Issue by glitchroy** [JujuAdams/scribble#35]
As it stands now, with the new sound feature, we can provide an array of sounds from which scribble will pick one. I think another feature where you could also provide a pitch range for the played sound would be great.  
Something like `audio_sound_pitch(sound_index, random_range(range_lower, range_upper))` should be pretty simple and could be incorporated great into `scribble_autotype_set_sound`, e.g. `scribble_autotype_set_sound(element, sound_array, overlap, pitch_array)` or even `scribble_autotype_set_sound(element, sound_array, overlap, pitch_lower, pitch_upper)`. Or maybe even a `pitch_offset` which would generate a range +- the offset, e.g. `[0.8, 1.2]` from offset `0.2`.

I can provide a PR in the following days if you are too busy to implement that. Thanks!

**Comment by JujuAdams** [comment]
Thanks for the suggestion, I'll definitely put this in for the next version!

I think I'll go for an lower/upper bound for pitches as that feels most transparent.

**Comment by JujuAdams** [comment]
Planned for v6

**Comment by JujuAdams** [comment]
In v6
