### ISSUE TITLE
Android effects lost

### ISSUE THREAD

**Issue by davidzvlc** [JujuAdams/Scribble#356]
Hello, I am speaking to comment on an error that I have found in Android, if for example you put effects such as rainbow or wave and minimize the game, when you return to the game, the effects have been lost and you will only see the plain text. (I don't think it's a very serious error but I'll mention it in case it helps) Greetings :D

**Comment by JujuAdams** [comment]
Ah! That's annoying. What version of Scribble are you using?

**Comment by JujuAdams** [comment]
Fixed https://github.com/JujuAdams/Scribble/commit/e722be9c9d434537dc0895a6e839d9eb692ce0f1
