### ISSUE TITLE
Text automatically wrapped by fit_to_box is still being shrunk, despite having adequate space.

### ISSUE THREAD

**Issue by OminousGiggle** [JujuAdams/Scribble#362]
Additional bug encountered after update from https://github.com/JujuAdams/Scribble/issues/360

A similar issue encountered with fit_to_box after the patch.

If I put \n in manually into my strings, it works correctly.
If fit_to_box has to wrap text itself, such as a sentence longer than the width, then the text gets shrunk again, even if it should fit in the box.

[fit_to_box_v2.zip](https://github.com/JujuAdams/Scribble/files/9041796/fit_to_box_v2.zip)

**Comment by JujuAdams** [comment]
Likely the same issue with newlines being counted twice. Shall check it out when I can.

**Comment by OminousGiggle** [comment]
Looks like both line 224 and line 235 are the culprits.
224 causes it to squash horizontally when it wraps.
235 causes it to squash vertically when it wraps.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/39684964ea65082f0d9c0017f47dbce71eed1ea7
