### ISSUE TITLE
Scribble may purge or ignore spaces when a string is wrapped across multiple pages

### ISSUE THREAD

**Issue by OminousGiggle** [JujuAdams/Scribble#366]
**Observed:**
If text is wrapped and creates multiple pages, scribble may purge spaces in the middle of lines of text, even if the text is not near the end of a line or page.

**Expected:**
The wrapped text would not purge spaces that should still be present.

[ErrorInvestigation.zip](https://github.com/JujuAdams/Scribble/files/9186200/ErrorInvestigation.zip)

**Comment by JujuAdams** [comment]
Workaround is to set `SCRIBBLE_FLEXIBLE_WHITESPACE_WIDTH` to `false`

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/c78f29f2bc9f0eada1c8163d5e7cb19058a0ada5
