### ISSUE TITLE
Sprites are still colorized when SCRIBBLE_COLORIZE_SPRITES set to false.

### ISSUE THREAD

**Issue by Psycho-Male** [JujuAdams/Scribble#368]
![image](https://user-images.githubusercontent.com/5340197/184492641-f390dd15-779c-4e7c-8e2d-ff61d3ad9ff8.png)

**Comment by JujuAdams** [comment]
How are you applying the colour?

**Comment by Psycho-Male** [comment]
> How are you applying the colour?

scribble(text).blend(c_black,1).draw(x,y);

**Comment by JujuAdams** [comment]
The `.blend()` method will colourize everything; this is by design. If you want to colourize specific parts of an input string use inline formatting.
