### ISSUE TITLE
SCRIBBLE_FIT_TO_BOX_ITERATIONS 0 _line_count(100509) not set

### ISSUE THREAD

**Issue by efeberku** [JujuAdams/Scribble#376]
When you set SCRIBBLE_FIT_TO_BOX_ITERATIONS to 0. (Release Version 8.0.8)

local variable _line_count(100509) not set before reading it.
 at gml_Script___scribble_gen_6_build_lines (line 319) -         repeat(_line_count)
############################################################################################
gml_Script___scribble_gen_6_build_lines (line 319)
gml_Script___scribble_class_model (line 324) -     __scribble_gen_6_build_lines();
gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_41158___scribble_class_element_gml_GlobalScript___scribble_class_element (line 1378)
gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_4568___scribble_class_element_gml_GlobalScript___scribble_class_element (line 164) -         var _model = __get_model(true);
gml_Object_obj_intrologo_Draw_0 (line 18) - scribble(sword).msdf_border(c_outline, 1.5*scribble_hs).transform(0.5*hs, 0.5*hs, 0).draw(x, y-7.5*hs);

**Comment by JujuAdams** [comment]
I'll of course protect against this crash, solution is to not set `SCRIBBLE_FIT_TO_BOX_ITERATIONS` to 0 as this is never an appropriate value.

**Comment by efeberku** [comment]
I just wanted to let you know.
