### ISSUE TITLE
get_width does not give the correct width if the text element has its font changed

### ISSUE THREAD

**Issue by OminousGiggle** [JujuAdams/Scribble#381]
**Observed**
If .get_width() or string_width_scribble is called on a string/text element, the font is changed, and then is called again, it will continue to spit out the original string width, instead of the width of the string based on the new font.

**Expected**
string_width_scribble would always return the width of the string with the currently used font.

[StringWidth.zip](https://github.com/JujuAdams/Scribble/files/9650502/StringWidth.zip)

**Comment by JujuAdams** [comment]
This issue is fixed upon updating to [version 8.0.8](https://github.com/JujuAdams/Scribble/releases/tag/8.0.8)

**Comment by JujuAdams** [comment]
...or not, fix here: https://github.com/JujuAdams/Scribble/commit/330124b5b4d8e6faae2b681bd8ff5bab26e55f6b
