### ISSUE TITLE
[help]About Chinese Display

### ISSUE THREAD

**Issue by Nanyuting** [JujuAdams/Scribble#382]
text = scribble("JUJU is best,但是没有中文[spr_gold]");

text.draw(x,y)

you will see:
JUJU is best,□□□□□□[spr_gold]

Could you find a way to support Chinese?
Thanks!

**Comment by Nanyuting** [comment]
Thanks Juju for your reply.
I re-established the project and tested it without problems.
It must be my own setting that conflicts.
I will make a Chinese guide later to reduce the information that disturbs you.

**Comment by Nanyuting** [comment]
Just a report:
The reasons for the previous misunderstanding are:
I've set the font color to be dark,
The sprite turned black,
I rewrote the way:
text = scribble("chinesetext[spr_gold]")
sprite is normal but  that Chinesetext cannot be displayed.
so，“draw_set_color“ caused the accident.
Thank you again for your help.

**Comment by JujuAdams** [comment]
You're welcome Nanyuting
