### ISSUE TITLE
Superfonts having issues with scribble_font_scale() and scribble_font_bake_shadow()

### ISSUE THREAD

**Issue by TandyRum1024** [JujuAdams/Scribble#385]
G'day -- I have found out that if I apply `scribble_font_scale()` operation to superfonts with fonts containing CJK characters for its range, some of the characters in that range seem to be ignoring the scaling operation:
![image](https://user-images.githubusercontent.com/26671673/194745117-dd4a569a-7c50-40e8-ae68-b456dbc3dac7.png)

(notice how the character `술` and `す` is bigger than the rest of the pre-scaled glyphs.)

At the same time, I also noticed that `scribble_font_bake_shadow()` messes up some of the texture UVs for CJK characters:
![image](https://user-images.githubusercontent.com/26671673/194745160-76be79b5-b8ca-49ba-afb4-a778b2058b8d.png)

---

I'm currently using Gamemaker runtime v2022.6.1.40, on Windows 10 machine with Intel i3 and Nvidia GTX 750Ti.

---
Here's the code snippet to reproduce the issue consistently (at least from my machine):
```GML
//-----<@ Create event or wherever I'm initializing the stuffs>-----
/// Set up the Superfonts
scribble_super_create("fntSuper");
scribble_super_glyph_copy_all("fntSuper", "fntEnglish", true);
scribble_super_glyph_copy_all("fntSuper", "fntJapanese", false);
scribble_super_glyph_copy_all("fntSuper", "fntKorean", false);
// ... //

// (Superfonts, but bigger font sizes -- The ones above uses 42pt sized font, and the ones below are 64pt each)
scribble_super_create("fntSuperBig");
scribble_super_glyph_copy_all("fntSuperBig", "fntEnglishBig", true);
// notice the order of the CJK fonts copied to the superfont;
// seems like the order also affects on what characters that gets their sizes wangjangled.
scribble_super_glyph_copy_all("fntSuperBig", "fntKoreanBig", false);
scribble_super_glyph_copy_all("fntSuperBig", "fntJapaneseBig", false);
// ... //

/// Add in the drop shadow
scribble_font_bake_shadow("fntSuper", "fntSuperShadow", 6, 6, c_black, 1, 0, false);
scribble_font_bake_shadow("fntSuperBig", "fntSuperBigShadow", 6, 6, c_black, 1, 0, false);

/// Scale the fonts
scribble_font_scale("fntSuperBigShadow", 0.3);

//-----<@ Draw UI event>-----
var _text = "키스의 조건은, 두 입술이 피튀기는 난투극을 펼친 뒤에야 다람쥐 헌 쳇바퀴 타고파 키키키키킥.\nA quick brown fox singlehandedly exterminated 3 different Universes\nUnder the supervision of a lazy dog. -- 私のホバークラフトは鰻でいっぱいです ";

/// 1] Using superfont per usual
scribble(_text)
	.starting_format("fntSuperShadow", c_white)
	.align(fa_left, fa_top)
	.transform(_scale, _scale, 0)
	.draw(_text_x, _text_y1);

/// 2] Some glitchy texture page UV stuff occuring on superfonts with bigger font sizes
scribble(_text)
	.starting_format("fntSuperBigShadow", c_white)
	.align(fa_left, fa_top)
	.transform(_scale, _scale, 0)
	.draw(_text_x, _text_y3);
```

---
### ***NOTE: I also provided the sample project's .yyz file ([ScribbleKoreanBugDemo.zip](https://github.com/JujuAdams/Scribble/files/9741057/ScribbleKoreanBugDemo.zip)) for you to test it on your machine for your convenience.***

In the provided project, I have modified the Scribble's default text shader (`__shd_scrible`) to make each characters region highlighted with the magenta colour for ease of debugging aswell.

![image](https://user-images.githubusercontent.com/26671673/194746066-4faf33ef-27fd-4bb7-bb5a-59cde002f886.png)
Also, I have put the fonts in a separate texture groups; One group each for big/small fonts. If you set those as the default texturegroup, then you may also obsersve that some of the non-font textures are also bleeding into the rendered text.

**Comment by JujuAdams** [comment]
Fixed by https://github.com/JujuAdams/Scribble/commit/0353ab4475223f7869eb1ecaffb311cc9aaf82c6 and https://github.com/JujuAdams/Scribble/commit/5704adfc59d940b2692764c9b6b3ade21b160bc7
