### ISSUE TITLE
Add example for typewriter delay and pause

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#39]
One of the most common requests for the typewriter is to include a `[delay]` and/or `[pause]` command. This ends up being quite complex to implement in a general way. It's possible to use the event system to this yourself, but that's quite complicated for new users.

The solution is just to add an example for delay/pause commands built with the events system. This could also include a tutorial on the wiki.

**Comment by AvioxArcade** [comment]
If/when  you add this, I'd also love an "automagically delay/pause on punctuation" option in the config file, or something similar.
(typing `[pause,10]` after every period, comma, etc could get old fast.)

**Comment by JujuAdams** [comment]
Noted!

**Comment by glitchroy** [comment]
+1 for this! At the moment, I'm using a custom made `autotype_set_speed` function to set the `__SCRIBBLE.AUTOTYPE_SPEED` when the event is triggered and setting it back after the specified time using a timer variable, but I'm always scared it'll break because the system is not designed for changes like this on the fly.

**Comment by JujuAdams** [comment]
If I recall correctly (afk), `__SCRIBBLE.AUTOTYPE_SPEED` gets multiplied by the tick size and then increments an internally held variable. It shoooould be ok to fiddle with that value (provided it's not negative...!) until I get round to making proper support for `[pause]` and `[delay]`.

**Comment by JujuAdams** [comment]
Implemented `[pause]` and `[delay]` for [5.5.x](https://github.com/JujuAdams/scribble/releases/edit/5.5.0.pre)

**Comment by AvioxArcade** [comment]
Looks great! Using `string_replace_all()` is a good workaround.

Sorry if this opens the ticket back -- the correct link to the 5.5.x pre-release is
[here](https://github.com/JujuAdams/scribble/releases/5.5.0.pre). (above link requires edit access)

**Comment by JujuAdams** [comment]
LOL sorry
