### ISSUE TITLE
Feature Request: draw part and/or scroll support

### ISSUE THREAD

**Issue by AvioxArcade** [JujuAdams/Scribble#396]
I realize this can be accomplished with surfaces and supporting code, but:

One common requirement of text in games is to have it fit to whatever amount of screen space is available, and also support varied resolutions/text sizes. 
One common solution to that issue is to have text automatically scroll up and down slowly  if it's larger/longer than the provided box. 
built-in support (as an alternative option/behavior to pages, probably) for this would be neat.

I picture it behaving similar to the typewriter in usage, where you define some parameters and it does the work for you.

Just a thought! Thanks.

**Comment by JujuAdams** [comment]
Duplicates #334 and #318
