### ISSUE TITLE
Regions bounds extend further beyond the bottom of the text

### ISSUE THREAD

**Issue by squishyb** [JujuAdams/Scribble#397]
As above, the bounds of regions seem to extend a little further beyond the bottom of where they should. This causes some issues in detection in the following examples: 

[Video showing two examples](https://i.gyazo.com/c36294c96866d37d062d607f163ff949.mp4)

To investigate further, I drew the bounds of regions to the screen. This is what led me to believe it maybe the issue, as you're still technically hovering over the other region: 
[Image showing Bounds drawn to screen](https://i.gyazo.com/da5e8d9da4f6f4c078407f5b4fc45184.png)

Let me know if you'd like anymore details! Thank you :) 

Edit: The font I'm using in the above example is "Teko", found here: 
[Google Fonts: Teko](https://fonts.google.com/specimen/Teko)

**Comment by JujuAdams** [comment]
Not possible to fix this fully as GameMaker is giving me some UVs for each character so I can't get the actual visual bounding box. Instead, if I scan backwards then this mostly works around the issue. Work around is here and will be released in v8.2: https://github.com/JujuAdams/Scribble/commit/d54104d05afaab0e1804b7b14429caab5b3b25ed
