### ISSUE TITLE
When I have a font with a range of 65535

### ISSUE THREAD

**Issue by yunzlp** [JujuAdams/Scribble#399]
I will split it into three sections for generation
32-25000
25000-40000
40000-65535
![image](https://user-images.githubusercontent.com/13077757/211165553-0361fdd3-390f-4e13-9cc6-0b591a9d9e7c.png)

I tried using the scribble_super_glyph_copy_all function to merge it into one font, but it got stuck
So is it possible to have a new feature to simulate merging fonts, where baking from multiple sources when drawing can be baked, for example, fnt_0 does not try to read from fnt_1
I have to say, Chinese glyphs are really too too too too too many, it would be great if one day Scribble can support font_add

**Comment by JujuAdams** [comment]
Do not set your font range so high. It is completely unnecessary. You should only be adding the glyphs you need, typically using the "Add From File" feature in GameMaker's glyph range editor.
