### ISSUE TITLE
Interrupted Effect

### ISSUE THREAD

**Issue by Boonani** [JujuAdams/Scribble#421]
Was thinking of this Katana Zero effect where someone gets interrupted and recreating it in scribble.

https://thumbs.gfycat.com/CreamyInconsequentialGermanspaniel-size_restricted.gif

I was thinking to do this in scribble, I probably just need to get the glyph x and y position, translate that to room coordinates. Figure out the blend mode and then if I'm using a sprite font then you can easily access the sprite data and make them fly offscreen.

At the moment, is it possible to get the glyph x and y position of each character? Wanted to see the challenges of implementing a system like this.

**Comment by JujuAdams** [comment]
Answered of Discord, but for future reference use `.get_glyph_data()`
