### ISSUE TITLE
Unable to change colors on the fly

### ISSUE THREAD

**Issue by ZigZaggh** [JujuAdams/Scribble#435]
Hi

I just updated from version 8.0.9 to 8.5.0, and discovered that the way colors are set has changed in __scribble_config_colours, before I changed the global scribble colors when the user selected night/day theme or just an other color theme, that worked perfectly, what would be the easiest way to do this with the new function, have I just overlooked something?

Sincerely

**Comment by JujuAdams** [comment]
What you were doing was not intentionally supported, nor was it a feature that was ever documented.
