### ISSUE TITLE
feature request for adding colours

### ISSUE THREAD

**Issue by jjg27** [JujuAdams/Scribble#437]
Thank you for the awesome work on Scribble, it's been incredibly helpful :)

To my knowledge, there's no simple way of using colours that I have previously defined as (global) variables in scribble.
It would be great to have some kind of `scribble_add_colour(_name, _colour)` function I can use in a script that runs on starting the game (or anywhere else at a later point too, I guess).

In short, I'd love to be able to go from something like this: `c_world_colour=make_colour_rgb(0,170,235);`
and then `scribble_add_colour("c_world_colour",c_world_colour);`
and then `draw_text_scribble(x,y,"Hello [c_world_colour]World![/c]");`

Many thanks!

**Comment by JujuAdams** [comment]
Implemented for [version 8.6](https://github.com/JujuAdams/Scribble/releases/tag/8.6.0)
