### ISSUE TITLE
Occasionally spritefonts will be rendered with some characters garbled

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#44]
Spritefonts are rendered under the assumption that all characters lie on the same texture page. Due to GameMaker's texture packing behaviour, sometimes individual images of the source sprite might lie on another texture page. At this time, it is not clear if GameMaker gives us sufficient tools to detect and mitigate this problem.

Observed:
![Observed](https://user-images.githubusercontent.com/3970480/77066511-38356880-69db-11ea-9fbc-8afefa63f332.png)

The current workaround is to put the spritefont in its own texture group and I've updated the wiki accordingly.

**Comment by DragoniteSpam** [comment]
Does it actually not? This seems rather inefficient from the point of view of game maker's own text renderer :P

**Comment by JujuAdams** [comment]
I don't know if GM internally builds its own texture page for spritefonts at runtime, but sprites can definitely have images across different pages.

**Comment by JujuAdams** [comment]
This isn't possible to solve without additional functionality in the GameMaker runtime: https://help.yoyogames.com/hc/en-us/requests/167813

**Comment by JujuAdams** [comment]
'lil bit hasty in giving this the `nope` label because a work-around *does* exist - a spritefont must sit on its own texture page. A suggestion for this has been added to the documentation (both in-project and on the wiki)
