### ISSUE TITLE
Changing color of the name dont work.

### ISSUE THREAD

**Issue by davidzvlc** [JujuAdams/Scribble#443]
I have tried to change the color of the name and it does not work, it always looks white.
I say it in case it helps to debug the code. Thanks anyway for your script :)

**Comment by JujuAdams** [comment]
There's not enough information here. What exactly are you trying to do?

**Comment by davidzvlc** [comment]
In your demo you have text and the name of the speaking character, I have tried to change the color of the character's name but it always looks white. 

I have tried draw_set_colour(c_red); before drawing and also "[c_black][portrait,spr_portrait][name,Juju]" on the create event.

**Comment by JujuAdams** [comment]
`[name,Juju]` is a command that sets the name of the portrait elsewhere. This string is not responsible for actually _drawing_ the name of the character, this happens at line 43 in the Draw event for  `obj_example_big_textbox`.

**Comment by davidzvlc** [comment]
yes, that's 1 of the 2 options i've tried, i've written 
draw_set_colour(c_black);
_element.draw(_x + textbox_width + 10, _y - 20);
and the name of the character continues to be white.

**Comment by JujuAdams** [comment]
`draw_set_colour()` doesn't inherently change the colour of text drawn using Scribble. `draw_set_colour()` only affects `draw_text_scribble()` - if you look inside that script you'll see how it works.

If you want to change the blending for a text element, you should use `.starting_format()` `.blend()` or inserting a colour using a command tag into the string that is being drawn.

**Comment by davidzvlc** [comment]
Oh okey thanks, that works!!!

**Comment by JujuAdams** [comment]
Great! Good luck with your games.
