### ISSUE TITLE
Finishing dialogue

### ISSUE THREAD

**Issue by ghost** [JujuAdams/Scribble#444]
Hi, I'm new with scribble and I have a question. How can I close a dialogue and not restart them when the last message is finished?. I have seen that all the demo file examples are a loop and I don't know how to end the dialogue. I ask here because I have searched YouTube videos and I have not found anyone who does it, everyone gives examples that are loops.

**Comment by JujuAdams** [comment]
This isn't a question that I can answer in detail. Scribble is just a text renderer. The logic that you're using to control where, and why that text is being drawn is out of scope.
