### ISSUE TITLE
Per character delay will ignore the last character in string by default

### ISSUE THREAD

**Issue by NagaseIori** [JujuAdams/Scribble#445]
However, the delay of the last character may sometimes be useful. :)
If developers want to add a per-character delay to the last character, they should modify the code in `_scribble_class_typist` as follows for now:
```gml
if (SCRIBBLE_ALLOW_GLYPH_DATA_GETTER
    && !__ignore_delay
    && __character_delay
    && (__last_character >= 1)
    && ((__last_character < _page_character_count) || (_found_size > 0))) { // Not ignoring the last character
    var _glyph_ord = _page_data.__glyph_grid[# __last_character-1, __SCRIBBLE_GLYPH_LAYOUT.__UNICODE];
    // ...
}
```

I wonder if it's possible to add a macro to the behaviour configuration that controls this behaviour.

**Comment by JujuAdams** [comment]
Originally, the last character would delay as you request but that was changed by someone else's request. A macro is indeed required here.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/c2d2aa244394aa4c1573688f456a42f5eab14b91
