### ISSUE TITLE
Flooded [Feather Messages] tab 

### ISSUE THREAD

**Issue by sydist** [JujuAdams/Scribble#467]
Hey, I recently started a project and decided to incorporate both Scribble and Input.
I use Feather. - SyntaxErrors profile only beacause I'm not a maniac - And my Feather Messages tab is filled with Errors, Warnings, and Suggestions. So much so that it's getting quite difficult seperating them from my project's own.

I'd like to know if this is planned to be fixed, if so, <ins>**I'd gladly submit a pull request doing as much as I can to help!**</ins>
If not, i'd like to know if there is a way to disable the messages coming from the libraries and only keep my project's.

**Comment by JujuAdams** [comment]
Features in Feather that should allow us to turn off messages don't seem to work. We have explored options in the past and none are helpful.
