### ISSUE TITLE
Effects exaggerated with small fonts

### ISSUE THREAD

**Issue by AvioxArcade** [JujuAdams/scribble#47]
Not sure if this is a bug or not.
But when using effects, it seems they are very exaggerated with small font sizes:

[example](https://drive.google.com/file/d/1RW1jMXVWt3XYMmopIZ05lF51Rsx8k9Ee/view?usp=sharing)
It's especially obvious with `[shake]`
This font is 12x9 pixels per character.

It might be nice if there's a simple way to tweak those settings, unless I'm just missing it.
Thanks!

**Comment by JujuAdams** [comment]
Does the wiki page on [`scribble_draw_set_animation(...)`](https://github.com/JujuAdams/scribble/wiki/(5.4.3)-scribble_draw_set_animation) answer your question?

**Comment by AvioxArcade** [comment]
oops! It sure does!
Sorry about that. I'll read the wiki before I post next time.

**Comment by JujuAdams** [comment]
Nah, it's a legit question. Editing the parameters of the in-built effects is super opaque and I really want to improve on that.
