### ISSUE TITLE
Expand the scribble_font_scale() to easier scale fonts globally

### ISSUE THREAD

**Issue by vaantti** [JujuAdams/Scribble#471]
I was looking into resizing my UI in an easy way. I thought giving the user a setting for e.g. "Normal, Larger, Largest" then using scribble_font_scale() to scale all the fonts.

The trouble is the function takes the existing size and scales relative to that. So there would need to be a way to reset to the initial font size value first and then rescale from that.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/b151b936d5740b08541e621496e5f796d1bd14c1
