### ISSUE TITLE
scribble_kerning_pair_set breaks html5 text

### ISSUE THREAD

**Issue by gameSaute** [JujuAdams/Scribble#474]
a single call of scribble_kerning_pair_set() breaks all html5 text.
Before- 
![image](https://github.com/JujuAdams/Scribble/assets/133373712/8953237d-7dda-4e1f-8b84-e43ff28bb9ac)
after- 
![image](https://github.com/JujuAdams/Scribble/assets/133373712/0fc752c6-e2de-4a2a-8bd1-de1818f97f5d)

**Comment by JujuAdams** [comment]
Upstream bug in GameMaker

**Comment by gameSaute** [comment]
Are they aware of the bug? Does it need to be reported?

**Comment by JujuAdams** [comment]
I don't know what the issue is specifically at this time, but there's nothing in Scribble that shouldn't, in principle, work everywhere. If HTML5 is the only platform with this specific issue then it's certainly a GameMaker runtime bug.
