### ISSUE TITLE
"__SCRIBBLE_BIDI" has already been defined

### ISSUE THREAD

**Issue by MarSterGames** [JujuAdams/Scribble#477]
I have _updated_ Scribble, from **8.0.3** to **8.7.0**
and when I run the game it shows this VVV

**Script: __scribble_system_glyph_data at line 28 : enum "__SCRIBBLE_BIDI" has already been defined**

![image](https://github.com/JujuAdams/Scribble/assets/83412462/1d085f46-04d4-4481-9e90-12ff5879abc7)

I have no idea what happen, Could you help me with this 😅🙏
(My GM2 is the lastest version)
(It's run perfectly fine in blank projects)

Thanks in advance, Mr.jujuAdams

**Comment by JujuAdams** [comment]
You have likely updated incorrectly. You must delete the previous version before importing the new version.

**Comment by MarSterGames** [comment]
Thank you so much!!

🥰🥰🥰🥰

**Comment by JujuAdams** [comment]
I hope you enjoy the library. Best of luck with your projects.
