### ISSUE TITLE
Arabic Typewriter bug

### ISSUE THREAD

**Issue by DevTRUCKer** [JujuAdams/Scribble#484]
I think you know this bug already and you are fixing it now right?

The issue is when using Arabic typewriter it shows word after word not character after character!
i think that because of Arabic is still Beta so i hope you fix it as soon as possible.

Keep up hard work am really looking forward to what you gonna make next. （*＾-＾*）

**Comment by JujuAdams** [comment]
This is a deliberate choice. Showing Arabic letter by letter would lead to visually unpleasant results due to the way Arabic glyp shaping works.

**Comment by DevTRUCKer** [comment]
Oh okay thanks
