### ISSUE TITLE
Request for colors! (file included)

### ISSUE THREAD

**Issue by DevTRUCKer** [JujuAdams/Scribble#487]
How am i missing something...?

- 🥇
[Scribble New Request.zip](https://github.com/JujuAdams/Scribble/files/12294060/Scribble.New.Request.zip)

**Comment by JujuAdams** [comment]
Please describe your issue.

**Comment by DevTRUCKer** [comment]
Oh sorry for very late response (～￣▽￣)～

Ok the request is in the normal GM draw text color functions there are four color options
so you can make your text blended with four colors, in Scribble its just one color using commands [c_white]
if i tried to do that [c_blue, c_red, c_maroon, c_aqua] it will not be blended with four colors it will only pick the first one
if you take a look into my example [Scribble New Request.zip] you will understand what i mean
so yeah that's all i hope its not too hard request keep up hard work with all of your projects and Thanks
-♪(^∇^*)

**Comment by JujuAdams** [comment]
Not a feature I am looking to implement.

**Comment by DevTRUCKer** [comment]
Okey Thanks :D
