### ISSUE TITLE
Multiple colors for text, like draw_text_colo(u)r?

### ISSUE THREAD

**Issue by Moonman327Dev** [JujuAdams/Scribble#491]
I've finally decided to just use scribble for my game project after trying to figure out how to draw text with sprites (and make it not look like a mess) for damage numbers in my game, and after trying for about 9-10 hours (and not counting the amount of time I've put into UI and string messing-withs before this for that) it finally broke me, and I wish I just went through with it earlier (instead of getting scared off by how big this library is) because it works amazingly.

The only issue I've encountered so far that I couldn't find others talking about (from quick searches in this issue's open/closed ones and google) is where you can't use multiple colors for text like gamemaker's base "draw_text_color" function, letting you use 4 colors (one for each corner), instead of being limited to just one.
I might be the only one having this "issue" since the 4 colors are a thing I like to use sometimes, like for this:
![image](https://github.com/JujuAdams/Scribble/assets/115742751/cbe9550e-557a-451b-b946-60256f30f9c1)
![image](https://github.com/JujuAdams/Scribble/assets/115742751/0d03e30f-ad1a-4047-ba19-677679589c05)

Usually I just use this for 2 colors, top and bottom color drawing, and it's not something I'm really missing out on fully and can just swap to using one color, but I do love the slight mix between them.

Let me know if this is something that's even possible (and doesn't take a you a year of frustration to figure out how) or if there is a way to do it and it's just not listed under "colors" in the documentation search. Should've used this library sooner instead of trying to reinvent the wheel for so long though...

**Comment by JujuAdams** [comment]
Use the gradient feature.

**Comment by Moonman327Dev** [comment]
![image](https://github.com/JujuAdams/Scribble/assets/115742751/fb356151-1c3f-4b5a-9725-bf61e49d29f6)
Looks like it was me missing it under colo(u)rs, thanks!
