### ISSUE TITLE
Allow `[typistSoundPerChar,...]` to take an array as an argument, like the base function

### ISSUE THREAD

**Issue by curryswirl** [JujuAdams/Scribble#495]
I asked about this a bit ago in the discord and came to the conclusion that when setting the typist sound via a text formatting tag, you can only set one sound rather than an array like when using `.typistSoundPerChar` on your typist element. It'd be cool if we could use an array here somehow as well.

**Comment by JujuAdams** [comment]
Not possible with the current parser.
