### ISSUE TITLE
Being able to ban/allow assets for Scribble

### ISSUE THREAD

**Issue by Camille-Leon** [JujuAdams/Scribble#497]
I have some scribble text I'm pulling from an external file that is meant to be modified, and I don't want players being able to add sprites from the game in the midst of their text, so I would love to be able to tell Scribble that certain assets should not be allowed to be used as inline sprites or sounds for typist-drawn text.

**Comment by JujuAdams** [comment]
`scribble_whitelist_sprite()` available in 9.1.0.

I'll make a separate issue for audio whitelisting.
