### ISSUE TITLE
ds_map_find_value argument 1 invalid reference to (ds_map)

### ISSUE THREAD

**Issue by efeberku** [JujuAdams/Scribble#501]
obj_intrologo_Draw_0 line 14 is scribble(sword).msdf_border(c_outline, 1.5*scribble_hs).transform(0.5*hs, 0.5*hs, 0).draw(x, y-7.5*hs);
Github is not showing the multiply sign there is no syntax problem with the line.

Non-fatal Exception: java.lang.Throwable: ---------------------------- GML ERROR REPORT START ----------------------------------

{ message : "ds_map_find_value argument 1 invalid reference to (ds_map)", longMessage : "ERROR in
action number 1
of Draw Event
for object obj_intrologo:

ds_map_find_value argument 1 invalid reference to (ds_map)", script : "gml_Script___scribble_gen_2_parser", line : 0, stacktrace : [ "gml_Script___scribble_gen_2_parser (line 244)","gml_Script___scribble_class_model (line 311)","gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_44798227___scribble_class_element_gml_GlobalScript___scribble_class_element (line 1513)","gml_Script_anon___scribble_class_element_gml_GlobalScript___scribble_class_element_4974154___scribble_class_element_gml_GlobalScript___scribble_class_element (line 179)","gml_Object_obj_intrologo_Draw_0 (line 14)" ] }
-------------------------------- GML ERROR REPORT END -------------------------------

**Comment by efeberku** [comment]
I am using monthly version 2023.8.2

**Comment by JujuAdams** [comment]
I've seen this issue a lot and it is down to you destroying an internal Scribble ds_map by accident. Check any and all code that is destroying ds_maps.
