### ISSUE TITLE
There was an error whilst reading "sprite_font: spr_sprite_font"

### ISSUE THREAD

**Issue by theinfamousmrmeow** [JujuAdams/Scribble#503]
Hello, I'm getting the following error while trying to use a sprite font in Scribble in a HTML5 build (this does not occur in Windows builds).

This is version 8.7.0, 2023-03-13

I am reporting it as ordered.

![image](https://github.com/JujuAdams/Scribble/assets/10565548/20400da9-fbcb-49cf-87e6-e6227e375bc4)

```
There was an error whilst reading "sprite_font: spr_sprite_font"
Please reimport the font into GameMaker and reset characters ranges
if this issue persists, please report it.

```

**Comment by JujuAdams** [comment]
What version of GameMaker are you using? Could you post the whole of your output log please?

**Comment by theinfamousmrmeow** [comment]
Will do after it builds (This project can take an extraordinarily long time to build in JS, not sure why), but I failed to report some very important context and updated the original comment:
`only happens in an HTML5 build (this does not occur in Windows builds).`

**Comment by JujuAdams** [comment]
Likely this is a YYG bug and unfixable, but we'll do our best.

**Comment by theinfamousmrmeow** [comment]
`"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148/bin/igor/windows/x64/Igor.exe"  -j=8 -ac=/cins -options="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- HTML5 Run

Loaded Macros from C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA\macros.json
Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148\bin\platform_setting_defaults.json
Options: C:\Users\alex\AppData\Roaming/GameMakerStudio2\alexander.d.macey_140548\local_settings.json
Options: C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA\targetoptions.json
Setting up the Asset compiler
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8 /cins /gn="bunnygunner" /td="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148" /zpuf="C:\Users\alex\AppData\Roaming/GameMakerStudio2\alexander.d.macey_140548"  /ffe="d3t+fjZrf25zeTdwgjZ8eXZ2bGttdTZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII=" /wt /m=html5 /tgt=32 /nodnd /cfg="Default" /nocache_html5  /o="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\bunnygunner_7DBCE308_Javascript" /HTMLRunner="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148/html5/scripts.html5.zip" /sh=True /optionsini="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\bunnygunner_7DBCE308_Javascript\options.ini" /obob=False  /obpp=False
  /obru=False  /cvm  /obfuscate /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148\BaseProject\BaseProject.yyp" "D:\GMS2\bunnygunner\bunnygunner\bunnygunner.yyp" /preprocess="C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA"
Found Project Format 2
D:/GMS2/bunnygunner/bunnygunner/particlelib/pt_dust/pt_dust.yy: D:/GMS2/bunnygunner/bunnygunner/particlelib/pt_dust/pt_dust.yy(65,2): GMSC Error: Field 'emitDelayMax' missing in YoYoStudio.Resources.GMPSEmitter.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 1866.5752ms
Loaded Project: bunnygunner
finished.
Found Project Format 2
(42,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 38.8526ms
Loaded Project: __yy_sdf_shader
finished.
Found Project Format 2
(43,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 34.3672ms
Loaded Project: __yy_sdf_effect_shader
finished.
Found Project Format 2
(43,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 27.451ms
Loaded Project: __yy_sdf_blur_shader
finished.
Found Project Format 2
(44,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 26.3754ms
Loaded Project: _filter_ripples
finished.
Found Project Format 2
(3,114): GMSC Error: Unexpected JSON property 'order'.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 40.6024ms
Loaded Project: _effect_blend
finished.
Found Project Format 2
(3,111): GMSC Error: Unexpected JSON property 'order'.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 23.1461ms
Loaded Project: _effect_glow
finished.
Found Project Format 2
(45,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 23.6769ms
Loaded Project: _filter_vignette
finished.
Found Project Format 2
(40,2): GMSC Error: Field 'templateType' missing in YoYoStudio.Resources.GMProject.
+++ ORIGINAL SERIALISATION SUCCESSFUL LOAD AND LINK TIME: 25.9926ms
Loaded Project: GMPresetParticles
finished.
Debug build
Options: C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA\ExtensionOptions.json
OptionsIni
Options: C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA\PlatformOptions.json
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8 /cins /gn="bunnygunner" /td="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148" /zpuf="C:\Users\alex\AppData\Roaming/GameMakerStudio2\alexander.d.macey_140548"  /ffe="d3t+fjZrf25zeTdwgjZ8eXZ2bGttdTZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII=" /wt /m=html5 /tgt=32 /nodnd /cfg="Default" /nocache_html5  /o="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\bunnygunner_7DBCE308_Javascript" /HTMLRunner="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148/html5/scripts.html5.zip" /sh=True /optionsini="C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\bunnygunner_7DBCE308_Javascript\options.ini" /obob=False  /obpp=False
  /obru=False  /cvm  /obfuscate /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148\BaseProject\BaseProject.yyp" "D:\GMS2\bunnygunner\bunnygunner\bunnygunner.yyp" /dbgp=6509 /debug /bt=run /rt=javascript
Looking for built-in fallback image in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148\bin\BuiltinImages
Saving HTML5 file... C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\bunnygunner_7DBCE308_Javascript\html5game\bunnygunner.js
Looking for built-in particle images in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148\bin\assetcompiler\ParticleImages
Looking for built-in font images in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148\bin\assetcompiler\BuiltinFonts
Fonts - Texture group not found in FONT_builtin.yy
Texture Group - __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_
Texture Group - Default
Rebuild cache file C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA\bunnygunner\Default\TextureGroups\_2048_0\__YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_.texturePreview.xml due to changed texture format
Rebuild cache file C:\Users\alex\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\bunnygunne_7DB5C393_E2A316EA\bunnygunner\Default\TextureGroups\_2048_131\Default.texturePreview.xml due to changed texture format
Warning : reference to extension macro IMGUI_GM_VERSION which is not available for this target - macro is in extension ImGui_GM and file imgui_gm.dll
0 Compressing texture... writing texture bunnygunner_texture_0.png... 
1 Compressing texture... writing texture bunnygunner_texture_1.png... 
2 Compressing texture... writing texture bunnygunner_texture_2.png... 
3 Compressing texture... writing texture bunnygunner_texture_3.png... 
4 Compressing texture... writing texture bunnygunner_texture_4.png... 
5 Compressing texture... writing texture bunnygunner_texture_5.png... 
6 Compressing texture... writing texture bunnygunner_texture_6.png... 
7 Compressing texture... writing texture bunnygunner_texture_7.png... 
8 Compressing texture... writing texture bunnygunner_texture_8.png... 
9 Compressing texture... writing texture bunnygunner_texture_9.png... 
10 Compressing texture... writing texture bunnygunner_texture_10.png... 
11 Compressing texture... writing texture bunnygunner_texture_11.png... 
12 Compressing texture... writing texture bunnygunner_texture_12.png... 
13 Compressing texture... writing texture bunnygunner_texture_13.png... 
14 Compressing texture... writing texture bunnygunner_texture_14.png... 
15 Compressing texture... writing texture bunnygunner_texture_15.png... 
16 Compressing texture... writing texture bunnygunner_texture_16.png... 
17 Compressing texture... writing texture bunnygunner_texture_17.png... 
18 Compressing texture... writing texture bunnygunner_texture_18.png... 
19 Compressing texture... writing texture bunnygunner_texture_19.png... 
20 Compressing texture... writing texture bunnygunner_texture_20.png... 
21 Compressing texture... writing texture bunnygunner_texture_21.png... 
D:\GMS2\bunnygunner\bunnygunner\extensions\ImGui_GM\iOSSource\..\post_textures.bat
D:\GMS2\bunnygunner\bunnygunner\extensions\Extension1\iOSSource\..\post_textures.bat
Debug version skipping obfuscation...
Done! 
Stats : GMA : Elapsed=2210579.3581
Stats : GMA : sp=361,au=72,bk=5,pt=1,sc=598,sh=47,fo=3,tl=0,ob=127,ro=8,da=18,ex=2,ma=453,fm=0xD040B39D7FFE7EB4
[Deploy] Copy Assets/Included files to target dir
PlatformOptions
DoIndexFile
DoSplash
DoCodeInjection
DoIcon
Igor complete.
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.8.1.148/bin/webserver/windows/x64/GMWebServer.exe  -v -root "C:\Users\alex\AppData\Local\GameMakerStudio2\GMS2TEMP\bunnygunner_7DBCE308_Javascript" -port 51264 -cidr 192.168.12.0/24
[GMWebServer] GMWebServer Starting........
[GMWebServer] GMWebServer started successfully on port 51264
Attempting to open browser - "" with URL "http://127.0.0.1:51264/index.html" 
Igor complete
[GMWebServer] Connecting to Client 127.0.0.1
[GMWebServer] 127.0.0.1 : 3.50 KB : /index.html
[GMWebServer] Connecting to Client 127.0.0.1
[GMWebServer] 127.0.0.1 : 9.18 MB : /html5game/bunnygunner.js
`

**Comment by theinfamousmrmeow** [comment]
> Likely this is a YYG bug and unfixable, but we'll do our best.

Absolutely all good, I know HTML5 is barely supported by YYG these days, just doing the due diligence to report it in case somewhere else needs to google :D

Looks like `GameMaker_Init` fails in the browser log.  Maybe scribble is just trying to find something that doesn't exist at that point.
![image](https://github.com/JujuAdams/Scribble/assets/10565548/a5686d43-f92e-4315-9192-af6b83999f38)

**Comment by JujuAdams** [comment]
That's a bit of a weird error. Looks like GM is falling over immediately. If possible, could you send me your project?

**Comment by theinfamousmrmeow** [comment]
Here's the `.js` file in question,   I can shoot you the whole project if that's useful, no problem, exporting now.

here's the offending line `42876:`

![image](https://github.com/JujuAdams/Scribble/assets/10565548/69d2a0e2-9682-44de-8db1-1555cdeddea0)

It is like that for every font in the project though, not just the `scribble_fallback_font`

[bunnygunner.zip](https://github.com/JujuAdams/Scribble/files/13257421/bunnygunner.zip)

**Comment by JujuAdams** [comment]
No idea why that's `"/""` instead of `"\""` but that is certainly not a fixable thing our end. I'd report that to YYG.

**Comment by theinfamousmrmeow** [comment]
Makes sense, I fixed those by hand but then immediately got a fresh new set of errors about it being confused I have Filter Layers in a room: 
![image](https://github.com/JujuAdams/Scribble/assets/10565548/0dc3227f-ba50-4c95-9c12-2ffe47f17d00)

Thanks for talking this through with me, I'll submit to YYG.  Last few times I've submitted JS errors I got mostly `that sux bro`, we'll see if they're any more interested in the platform these days.

In any case, not related to scribble :D

**Comment by JujuAdams** [comment]
Same issue isn't it ... Looks like whatever quote-escaping function they have is broken af. Best of luck!

**Comment by JujuAdams** [comment]
Can't see bug reports made by other users, also that's the legacy bug reporting feature. You should submit bugs via https://github.com/YoYoGames/GameMaker-Bugs/

Incidentally, it looks like someone else is experiencing the same issue: https://github.com/YoYoGames/GameMaker-Bugs/issues/2094

**Comment by theinfamousmrmeow** [comment]
Thanks for the heads up.  Submitted a new one:

https://github.com/YoYoGames/GameMaker-Bugs/issues/2121
