### ISSUE TITLE
Can't run the project with scribble, it returns compile errors

### ISSUE THREAD

**Issue by Valcoran** [JujuAdams/Scribble#513]
Hello! I wanted to try out Scribble but looks like that's not going to happen. 

IDE is v2023.11.1.129 I'm using the latest version of Scribble.

Trying to compile my very small project after adding scribble fails to compile and returns this,

Script: scribble_font_rename at line 4 : unknown function atribute _new
Script: scribble_font_rename at line 4 : variable name expected
Script: scribble_font_rename at line 4 : Symbol ) expected
Script: scribble_font_rename at line 4 : got ')' expected '{'
Script: scribble_font_duplicate at line 4 : variable name expected
Script: scribble_font_duplicate at line 4 : Symbol ) expected
Script: scribble_font_duplicate at line 4 : unknown function atribute _new
Script: scribble_font_duplicate at line 4 : got ')' expected '{'

**Comment by JujuAdams** [comment]
Likely the case that you've got a macro set up that's interfering with Scribble. Might be called `_old`.

At any rate, this is not reproducible my end and no one else has reported such a serious compilation error so I'm confident say this is your end.
