### ISSUE TITLE
Blurry Text on Scribble Draw

### ISSUE THREAD

**Issue by kt-altyn** [JujuAdams/Scribble#517]
default text functions of gamemaker works fine;
![image](https://github.com/JujuAdams/Scribble/assets/92668715/2660717f-85a8-43c1-b453-79c85f88ae7a)
![image](https://github.com/JujuAdams/Scribble/assets/92668715/dab4fe29-e23d-46d8-bdeb-551f94e9a755)

however when i use scribble functions to draw, it looks like this;
![image](https://github.com/JujuAdams/Scribble/assets/92668715/c8eedc07-9d98-4183-81b6-978cfbbb3efb)
![image](https://github.com/JujuAdams/Scribble/assets/92668715/f0e5c37d-17c1-4f61-9fb9-70027dc95cfd)

**Comment by JujuAdams** [comment]
Is this an SDF font?

**Comment by kt-altyn** [comment]
solution: turn off SDF tick here: 
![image](https://github.com/JujuAdams/Scribble/assets/92668715/4e9720f1-42c5-4e92-bfa6-1d2b355a5f7c)
