### ISSUE TITLE
Feather: Functions with "string" params are expecting "struct" type

### ISSUE THREAD

**Issue by sanjar-dev** [JujuAdams/Scribble#519]
I used GameMaker 2024.2 project and imported beta Scribble 9.0.

In the draw event of an empty object I tried to use the `draw_text_scribble` function which gave an error `GM1041 - The type 'String' appears when the type 'Struct' is expected.`

```gml
draw_text_scribble(x, y, "hello, world!");
```

Adding parameter types to JSDoc script comments ([GameMaker Docs](https://manual.gamemaker.io/monthly/en/The_Asset_Editors/Code_Editor_Properties/JSDoc_Script_Comments.htm)) in `scripts/draw_text_scribble/draw_text_scribble.gml`

```gml
/// @param {real}   x            The x coordinate of the drawn string
/// @param {real}   y            The y coordinate of the drawn string
/// @param {string} string       The string to draw
/// @param {real}   [charCount]  The number of characters from the string to draw. If not specified, all characters will be drawn
```

and retyping the function seemed to remove the issue. This issue comes up at all functions I've tried that require string as a parameter (`draw_text_scribble`, `draw_text_scribble_ext`, `scribble` etc).

![image](https://github.com/JujuAdams/Scribble/assets/26625340/dc660497-f82f-43c3-88b9-1f1de358e8e6)

**Comment by JujuAdams** [comment]
Feather is not supported by this library, or any of my libraries.
