### ISSUE TITLE
sprite-font crash

### ISSUE THREAD

**Issue by susususus44** [JujuAdams/Scribble#521]
weird bug
i have first added a spritefont, and this error popped up
when i deleted the line which adds the spritefont, the error didn't dissapear
only fix i found is to reinstall scribble entirely

![Снимок экрана 2024-04-03 165800](https://github.com/JujuAdams/Scribble/assets/117569931/51e7e9aa-6b65-4627-9333-39188a41a31b)

**Comment by JujuAdams** [comment]
Seems to be an import issue of some kind.
