### ISSUE TITLE
scribble_font_add_all_from_project will stop working soon

### ISSUE THREAD

**Issue by GameDevTosh** [JujuAdams/Scribble#522]
Its come to my attention that this function currently brute forces the checking of all fonts by looping 1000 times in a repeat loop and finding font indices as reals. This method will soon stop working entirely, as assets have been changed to refs/handles. Currently the reals method still works, but not for long. 

Talking to a few people, its been suggested that it would be better to switch the code to use the newer function **_asset_get_ids_** to replace this brute force method, and any brute forcing done to find asset id's for any of scribbles functions.
![image](https://github.com/JujuAdams/Scribble/assets/85319605/580ba155-93fc-4029-a041-84ccfe4128a8)

**Comment by tabularelf** [comment]
Was talking to Tosh about this just now, future versions of Scribble (presumably v9)
```gml
var _fonts = asset_get_ids(asset_font);
var _i = 0;
repeat(array_length(_fonts)) {
    var _tags = asset_get_tags(_fonts[_i]);
    // proceed from here
}
```
