### ISSUE TITLE
font_bake_shadow() dY stretches top pixel of letters

### ISSUE THREAD

**Issue by KingDevyn** [JujuAdams/Scribble#526]
Using font_bake_shadow() with a large dY value can be seen stretching the top pixel of letters in the shadow equal to the drop shadow height.

**Comment by JujuAdams** [comment]
How large is "large" in this situation?

**Comment by KingDevyn** [comment]
I think any size technically, it's just not visible until the shadow extents below the bottom of the topmost line in any given letter. Specifically I got this error using spritefonts with hard shadows. I'm unsure if it applies under other circumstances.

**Comment by JujuAdams** [comment]
Fix here: https://github.com/JujuAdams/Scribble/commit/cbebc0431eb027926a3ce4e2a53a971ba8b3edbb
