### ISSUE TITLE
Kerning and shadow issues in SDF rendering

### ISSUE THREAD

**Issue by tthrelfo** [JujuAdams/Scribble#529]
Version: scribble_9_0_0_beta.yymps
Example project, with font included: [font test.yyz.zip](https://github.com/JujuAdams/Scribble/files/15425528/font.test.yyz.zip)

Screenshot of the problematic behaviour:

<img width="914" alt="image" src="https://github.com/JujuAdams/Scribble/assets/111235581/77340f56-e4d5-4a62-8889-0ce85fcc3725">

Issue 1:

This project draws two lines of text to the screen. The first line is written with `draw_text()`, while the bottom line is drawn with Scribble. The top line has appropriate spacing, while the Scribble version has slightly odd-looking spacing.

Issue 2:

Strange cross hatching effects when using the drop shadows for this font. It's worth noting that in my main project this appears solely when using Scribble, but while making this example project, it started popping up for the `draw_text()` version, too. For this reason I'm not sure if it's actually a Scribble problem, but I'm mentioning it here just in case.

**Comment by JujuAdams** [comment]
I took a look at the SDF that GameMaker generated and it's very messy. Seems like this problem is up-stream to me!
