### ISSUE TITLE
Remove SCRIBBLE_Z from macros?

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#53]
`SCRIBBLE_Z` currently passes in a uniform into the default Scribble shader to control the eventual vertex z-position of text. We do this because Scribble hijacks the z-coordinate of the vertex position to communicate other data (specifically the character/line index).

Passing around `SCRIBBLE_Z` as a uniform has a non-zero cost for rendering text and it adds clutter to the library in general. I feel like if someone was using GM for 3D they'd understand enough about shaders (the graphics pipeline in general) to make this edit themselves.

**Comment by DragoniteSpam** [comment]
I've never used the macro, even in 3D. I feel like if I were to draw a scribble in 3D space I'd probably slap it on a 2D surface first or something.

**Comment by JujuAdams** [comment]
I'll take it out for 5.5.0 then
