### ISSUE TITLE
Is there a way to detect a specific character in a scribble text?

### ISSUE THREAD

**Issue by KitMakesGamesIGuess** [JujuAdams/Scribble#530]
Self explanatory, is there a scribble equivelent to string_char_at to get a specific character from a string excluding the scribble tags?

As an example of what im talking about
String = "[rainbow]Mama mia Luigi this isn't weed [/rainbow]"

scribble_get_character(1) [As the hypothetical function]

You'd get M as the output (instead of [)

I know Scribble has the functionality since draw_text_scribble_ext has a charCount argument, but I dont know if there's a command for it :<

**Comment by JujuAdams** [comment]
You will need to use the full API like so:

`scribble("[rainbow]Mama mia Luigi this isn't weed [/rainbow]").get_text() => "Mama mia Luigi this isn't weed"`
