### ISSUE TITLE
Question / Feature Req: Arguments for effects tags

### ISSUE THREAD

**Issue by spacebake** [JujuAdams/Scribble#532]
I'm moving over to scribble from my own text tag system and one thing that I immediately miss is the ability to set shake power on the fly.
Like for example, sometimes I want to shake two different words by different amounts in the same string.
So it'd be like ` "The <shake, 1>quick</> brown fox <shake, 3>jumps</> over the lazy dog"`

I will find a way to get this working for my project, but i think it would be a useful default feature if it isn't already planned.

**Comment by JujuAdams** [comment]
Not possible.
