### ISSUE TITLE
Text not displayed when alpha test is enabled

### ISSUE THREAD

**Issue by Rokkimanda** [JujuAdams/Scribble#533]
This text is posted after AI translation of Japanese.
Sorry if it is difficult to read.

The object containing the text drawn with scribble()
I wrote the code according to the following article, but when I execute it, the text is blacked out and cannot be displayed properly.

https://gamemaker.io/en/blog/dynamic-rendering-masks

![スクリーンショット 2024-06-02 16 06 51](https://github.com/JujuAdams/Scribble/assets/153979532/cf1c6d7d-16b9-42e4-b1ea-1d42deeb8903)

![スクリーンショット 2024-06-02 16 02 26](https://github.com/JujuAdams/Scribble/assets/153979532/e7f5ed73-4783-4595-bb73-79529e353f07)

If I change the blendmode back to bm_normal
It is depicted correctly, but now it is not.
mask will no longer function.

![スクリーンショット 2024-06-02 16 09 48](https://github.com/JujuAdams/Scribble/assets/153979532/accfa593-a614-4271-9c4a-06be5bd3f34b)

Please let me know the solution.

**Comment by JujuAdams** [comment]
Scribble doesn't support alpha testing. You're better off using a surface to clip text.

**Comment by Rokkimanda** [comment]
Thank you for answering my question.
 I will try using surfaces.
