### ISSUE TITLE
Is there a way to adjust the texts position relative to the draw origin for each alignment, per font?

### ISSUE THREAD

**Issue by SpookySquidGames** [JujuAdams/Scribble#534]
A common problem I run into with pixel fonts is that the text draw position for various halign and valign settings is a little off, or in some cases wildly off.  I'm wondering if Scribble has a way to adjust these positions font wide so I can set them and forget them.  Some examples of the issue with the font Silver (I come across this sort of thing with LOTS of fonts but it's a good illustration of the issue)

![silver-very-strange-vertical-alignment](https://github.com/JujuAdams/Scribble/assets/96712187/eebba22b-759f-4a54-b2a0-6bc5ef95bfb1)

The red dot is the x,y coordinate I'm drawing the text to.  These are all single lines of text drawn to the same spot, the valign is just VERY weird.  Subtler issue with right aligned text, where it's a few pixels away from where it should be relative to the origin. 

![silver-halign-right-offset](https://github.com/JujuAdams/Scribble/assets/96712187/6a985646-12ca-48a3-bdd6-f5e63225819a)

Is there a way in scribble to say "if I'm using this font, with this alignment, adjust x by 3, adjust y by 1"?

In the past when coming across these sorts of issues, particularly when swapping fonts for localization, my approach has been to have some form of global variables I set per font / per language like so.

![font-offset-variables-example](https://github.com/JujuAdams/Scribble/assets/96712187/385c2e55-d365-4069-8722-6c02813051d7)

 and then always include these variables in any code that draws text:
 
 `_window.label_scrib.align(_h_align,_v_align).draw(_x+TEXT.h[_h_align],_y+TEXT.v[_v_align]);`

In this case TEXT is a singleton object I'm storing these offset variables in. 

This approach works but I've found it to be error prone and kinda messy. Hoping scribble has a better way! 
Oh also I'm currently using Scribble version 8.7.1 because I'm in GM LTS.

**Comment by JujuAdams** [comment]
You mention you're using the (famous) Silver font. Are you using this as a spritefont or as a standard GM native font? Is the vertical alignment problem also apparent when using the native `draw_text()` function(s)?

**Comment by SpookySquidGames** [comment]
It's a standard GM native font, not a sprite font. The vertical alignment problem is also apparent when using native `draw_text()` so this isn't something Scribble is introducing, I'm just using it as an example of the sort of problem I'm trying to solve. While this is an extreme example, I've had to do this sort of compensating with other fonts and for other reasons in the past so hoping there's an easy solution for it in Scribble!

**Comment by JujuAdams** [comment]
I'll need to check the parser to see what I can do.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/b5f5b8b6ce141209086a4f36df82222a4a9169b9  https://github.com/JujuAdams/Scribble/commit/adf8a2250d8b1d4e79ff3f59f645f6a7221773f9

**Comment by JujuAdams** [comment]
Fix available in 8.8.0: https://github.com/JujuAdams/Scribble/releases/tag/8.8.0
