### ISSUE TITLE
Best way to set default line height for a font? 

### ISSUE THREAD

**Issue by SpookySquidGames** [JujuAdams/Scribble#535]
I'm currently doing this to set the default line height for a font:

`scribble_glyph_set("fnt_silver", " ", SCRIBBLE_GLYPH.FONT_HEIGHT, 15, false);`

Feels like a bit of a weird hack, wondering if this is the intended method or if there's another way I should be doing this.
Using Scribble version 8.7.1 because I'm in LTS.

**Comment by JujuAdams** [comment]
You can use `all` in place of `" "` as well, but this is otherwise correct.
