### ISSUE TITLE
Scribble not drawing text in same location as Game Maker's native text drawing in 8.7.1

### ISSUE THREAD

**Issue by SpookySquidGames** [JujuAdams/Scribble#536]
Noticed that Scribble is drawing text two pixels lower than the native Game Maker text render.  That doesn't seem to be the intended behavior from what I read in the documentation?  This example image is 8.7.1 running in GM LTS. 

![scribble-not-drawing-in-same-place-as-native-text-rendering](https://github.com/JujuAdams/Scribble/assets/96712187/953703a5-d35d-44c5-bf6d-ae7167a83f7d)

**Comment by JujuAdams** [comment]
Will need to take a look at a project to determine the cause here.

It is unlikely that this can be fixed for 8.7.x because this would be a breaking change for people who are reliant on a (potentially incorrect) vertical offset. However, I can suggest a workaround if this turns out to be a Scribble bug.

**Comment by SpookySquidGames** [comment]
Decided to run some tests using other fonts on a hunch and this only seems to effect Silver. Still weird that Scribble and native GM are handling it differently, but at least it seems to not be a larger issue that affects all fonts. Let me know if you'd still like a test project to figure out what's going on here. Thanks! 

Going to test the kerning function bug I reported on other fonts as well in case that's also Silver specific.

**Comment by JujuAdams** [comment]
I thhhink I know what this is (ascender offset) but I'd need to see it in situ to be sure.

**Comment by SpookySquidGames** [comment]
Ok! I'll put together a little test project and post it here as soon as I have chance. Thanks!

**Comment by JujuAdams** [comment]
Thank you kindly.

**Comment by SpookySquidGames** [comment]
Ok example file attached!
[silver and scribble test.zip](https://github.com/user-attachments/files/15746038/silver.and.scribble.test.zip)

While making this I found an _"interesting"_ GameMaker quirk. Silver's vertical alignment in native GameMaker text rendering changes depending on what characters you've included in the range. After having a random assortment of Japanese and Korean characters added to the range it started rendering text one pixel lower than before (at least when vertical alignment is set to the top). Extra weird. Removing those characters after doesn't fix it, even making a completely new font from Silver without those characters didn't fix it. It somehow permanently changes the position for the font across all versions. Since I could not find a way to undo this change I wasn't able to test if adding those characters had the same effect in Scribble or on other vertical alignments for native text rendering. _Fun!_

**Comment by JujuAdams** [comment]
Thank you for the example project. I will take a look soon.

**Comment by JujuAdams** [comment]
Was indeed the ascender offset: https://github.com/JujuAdams/Scribble/commit/2c464fcaad368e725932c4e2b1705c8e9e1ef3d8

This will not go into v8.7.x but I will put out a v8.8 today with this fix.

**Comment by JujuAdams** [comment]
Fix available in 8.8.0: https://github.com/JujuAdams/Scribble/releases/tag/8.8.0
