### ISSUE TITLE
Scribble_kerning_pair_set effecting the space after the kerning pair not the space between them in 8.7.1

### ISSUE THREAD

**Issue by SpookySquidGames** [JujuAdams/Scribble#537]
Basically what the description says. 
If you do something like this to increase the spacing between the "I" and "G" :
`scribble_kerning_pair_set(fontName, I, G, 10,true)`

and then draw the word "SIGN"
You get: SIG  N
Instead of: SI GN

Whether your doing "relative" or not doesn't have an effect. In both cases it's the character after the kerning pair that's affected.

Scribble 8.7.1 in GM LTS 2022

**Comment by JujuAdams** [comment]
Odd ... haven't run into this one and I've used the kerning feature quite a lot. I will take a look.

**Comment by SpookySquidGames** [comment]
Just tested this with a few different fonts and saw the issue in all of them. Here's an image showing it in action. 

![scribble-kerning-issue](https://github.com/JujuAdams/Scribble/assets/96712187/b4e98925-4cd8-4b17-97df-af0b6dec7e36)

This was the code: `scribble_kerning_pair_set("fnt_arial", "E", "S", -1 ,true);`

Instead of the E and S touching, the S and T are.

**Comment by JujuAdams** [comment]
Silly off-by one https://github.com/JujuAdams/Scribble/commit/3cd7bc0e33b38c7ae8dfb08da7e3056a9c363e66

Don't know how this crept in consider it worked fine in previous versions but oh well.

**Comment by JujuAdams** [comment]
Fix available in 8.8.0: https://github.com/JujuAdams/Scribble/releases/tag/8.8.0
