### ISSUE TITLE
Chance Text Shaking & Letter Spacing

### ISSUE THREAD

**Issue by SoupTaels** [JujuAdams/Scribble#538]
Ayy! This is probably _too_ hyperspecific to even be worth a feature, but I was wondering how I could recreate Undertale's random letter shaking effect shown here:
![Runner_8JKrE6vJcR](https://github.com/JujuAdams/Scribble/assets/105392027/bdd54ce2-a768-4b0a-9220-e0b562168a82)

Basically, each letter would have a random chance to shake for just a moment. Additionally, there's functions for changing the line spacing, but nothing for changing letter spacing.

**Comment by JujuAdams** [comment]
Letter spacing is changed at the font level, see `scribble_glyph_set()`. Random shaking of the kind demonstrated by your GIF is not aupported at this time.
