### ISSUE TITLE
Small typo making scribble_font_set_valign_offset() use scribble_font_set_halign_offset's settings

### ISSUE THREAD

**Issue by SpookySquidGames** [JujuAdams/Scribble#539]
Line 81 of __scribble_gen_2_parser needs to be changed from:
`var _state_valign_offset = _font_halign_offset_array[__valign ?? _starting_valign];\`
to:
`var _state_valign_offset = _font_valign_offset_array[__valign ?? _starting_valign];\`

It's causing the valign settings to be ignored and use the halign ones instead. 

Also thanks so much for adding this feature! It's going to be a major quality of life upgrade for working with pixel fonts, especially for localization!

**Comment by JujuAdams** [comment]
lmao sorry. Could you make a PR for that?

**Comment by SpookySquidGames** [comment]
So, I've never done a Pull Request but I'll see if I can figure it out tomorrow.

**Comment by SpookySquidGames** [comment]
Ok hopefully did this correctly 😅 had a friend with more git experience walk me through it.
