### ISSUE TITLE
Scribble equivalent of string_width and string_height

### ISSUE THREAD

**Issue by brady-goldsworthy** [JujuAdams/scribble#54]
I'm curious if there's a way to get the width and height of a string that would be drawn using scribble_draw.  Something like the build in string_width and string_height functions, but using the scribble draw state.

Is there a way to do this? If not, consider this to be a possible feature request :)

**Comment by DragoniteSpam** [comment]
You can use [scribble_get_quad](https://github.com/JujuAdams/scribble/wiki/(5.4.3)-scribble_get_quad) or [scribble_get_bbox](https://github.com/JujuAdams/scribble/wiki/(5.4.3)-scribble_get_bbox) to get the bounds of a scribble element.

A higher-level way to get the dimensions would be nice, all you really need to do for that is get the left and bottom bounds of the array for width and height, though.

**Comment by brady-goldsworthy** [comment]
That's exactly what I was looking for, thank you! Closing this as my question was answered.

**Comment by JujuAdams** [comment]
I can add width/height to the output array (/struct in the future?)
