### ISSUE TITLE
In-line pin commands crashing game?

### ISSUE THREAD

**Issue by AMZYoshio** [JujuAdams/Scribble#542]
I'm trying to integrate Scribble into a fairly large project and have a question about how the pin commands [pin_right], [pin_left] and [pin_center] function, as they seem to be crashing things. Most likely a case of me missing a small detail.

I have a function called createbook() that stores a bunch of strings into a large ds_grid for reference later, then a ds_list called choicelist that is used universally for most menus (named because it was "choices" a player had in dialogue, which was the first menu type I made).  The strings are loaded out of the grid and into choicelist upon opening a book, and those strings are displayed on the screen. What it currently looks like:

![Scribble1](https://github.com/JujuAdams/Scribble/assets/172154011/07e78ff2-f20b-4707-977a-7ba75ade61c2)

I am attempting to create headers in the book by centering the text, then left aligning text on subsequent lines. When using [fa_center] and [fa_left] tags, they behave as they would naturally in Game Maker, which is to say the text is centered on the .draw coordinate, which is not the middle of the page. I figured pin commands would solve this, but when attempting to use any to see how they even work, I get this:

![Scribble2](https://github.com/JujuAdams/Scribble/assets/172154011/27f5c999-dbf2-4f39-b930-f7bac684af9d)

I am unsure how to proceed and no amount of using other methods with scribble() seems to do the trick, unless I simply am unaware of the proper one to use, or if I should even be using pin inline commands to achieve this effect.

Also, as a side note, I'm aware I shouldn't be changing fonts to change colors, but this is exactly why I'm trying to implement Scribble; I plan on getting rid of most of those fonts once I can properly grasp how to use it. I originally had all these because I have typable sprites as special characters and I didn't want them colorized whenever I blended the white version of the font.

**Comment by JujuAdams** [comment]
Ha! This is a bug accidentally introduced alongside a new feature in v8.8. I can probably hotfix that tonight but if I get delayed by something then downgrading to v8.7.x will likely fix the problem.

**Comment by JujuAdams** [comment]
Fixed for 8.8.1 (https://github.com/JujuAdams/Scribble/releases/tag/8.8.1)
