### ISSUE TITLE
Illegal use of undefined crash on dev-9 branch

### ISSUE THREAD

**Issue by AtlaStar** [JujuAdams/Scribble#545]
Just loading the root project causes the below crash on line 333 inside the `__SCRIBBLE_PARSER_SET_FONT` macro of `__scribble_gen_2_parser`

![image](https://github.com/JujuAdams/Scribble/assets/3477783/8d04c1ec-4de9-41ef-a2af-c72d700a1570)

Looking at the macro it appears related to line 81 of the parser   `var _state_valign_offset = _font_valign_offset_array[__valign ?? _starting_valign];;`, as manually replacing the macro with inline code shows that the error is that both `__valign` and `_starting_valign` are undefined, and cannot be converted into an array index.

GMS runtime version tested on is a slightly older monthly release of 2024.4.0.168

This seems related to the fact that the element itself is not defining a `__starting_valign` value for a default, suggesting that the fix is to either provide a default alignment in the element, or to do on line 81 of the gen 2 parser.
```gml
 var _state_valign_offset = _font_valign_offset_array[(__valign ?? _starting_valign) ?? 0];
 ```

**Comment by JujuAdams** [comment]
I agree with your proposed solution. Thank you.
