### ISSUE TITLE
Compile Error - Malformed Delcaration of Static

### ISSUE THREAD

**Issue by MistorRonan** [JujuAdams/Scribble#547]
![image](https://github.com/JujuAdams/Scribble/assets/163997356/a887e70b-6f6a-4a29-889f-b0e9be55bd06)

**Comment by JujuAdams** [comment]
This is an unhelpful ticket. What is the actual problem here?

**Comment by MistorRonan** [comment]
basically, I used scribble in my gamemaker project since the very start. Its worked fine for it throughout the majority of the development of it. However when I imported a local asset package I made into the project, suddenly I started getting this compile error related to scribble even though the asset package does nothing to scribble. 

So when I try to boot up my game, I get these compile errors

![image](https://github.com/JujuAdams/Scribble/assets/163997356/4eb9a103-c2f2-4ca5-bc9a-6f97a376ecca)

**Comment by MistorRonan** [comment]
okay, I releaised the error. I had an object with the same name as a scribble function

**Comment by MistorRonan** [comment]
apologies, I was really stressed about this bug and didn't think about how that was the issue until now. Thank you so much for the libraries you provide

**Comment by JujuAdams** [comment]
Glad you got it sorted 🙂
