### ISSUE TITLE
"In-line sprites cannot have more than 64 frames" warning occurs at >= 64 frames rather than >64 frames.

### ISSUE THREAD

**Issue by Jakeb89** [JujuAdams/Scribble#551]
This warning exists in the file `__scribble_gen_9_write_vbuffs.gml`, line 304.

Code should check if  `_sprite_number > 64` rather than `_sprite_number >= 64`

**Comment by JujuAdams** [comment]
Not entirely sure if the docs are wrong or the code is wrong! Limit is based on integer packing so I'll need to investigate and test.

**Comment by JujuAdams** [comment]
Limit was 63 images in reality so the code was right but the warning was wrong.

Since I was in the area, I bumped up the limit to 127 and reduced the accuracy of the image speed to compensate.

Available in 9.1.0
