### ISSUE TITLE
scribble recgonizes tag once and tag never works again

### ISSUE THREAD

**Issue by Cuewot** [JujuAdams/Scribble#552]
i added 2 tags to my scribble installation, they're called [player] and [/player], i use them to update my textbox system on the fly using only text, but for some reason they stop working after using them one time

they work by setting a global variable named "global.whoIsSpeaking" to either "player" or "self" when they're mentioned on a text

here's their source:
![image](https://github.com/user-attachments/assets/df48302c-2681-4994-bead-1de068db8b07)
![image](https://github.com/user-attachments/assets/71114d11-ab66-44ca-aa68-f9ee37c44ff5)

https://github.com/user-attachments/assets/2b78b3f2-819b-4af5-bd4f-d95ee5372771

so...why doesn't it work when i make another text?

**Comment by Cuewot** [comment]
also i'm sorry if this is missing anything, this is my first github issue that i've ever issued

**Comment by JujuAdams** [comment]
This is not how you should add tags. You should not be modifying internal Scribble code at all and you should use the provided function to add tags. You will need to undo your modifications before proceeding.

You should use [`scribble_typists_add_event()`](https://www.jujuadams.com/Scribble/#/latest/misc-functions?id=scribble_typists_add_eventname-function) to add event tags. These events will only be executed when using a typist.

**Comment by Cuewot** [comment]
OHHHHHHH

i see

**Comment by Cuewot** [comment]
"there are no dumb questions" is a lie

**Comment by Cuewot** [comment]
so like, does it work with `draw_text_scribble_ext()` or do i need to use typists for this one?...

**Comment by JujuAdams** [comment]
These events will only be executed when using a typist.
