### ISSUE TITLE
Inconsistent Text Rendering when Positions Not Floored

### ISSUE THREAD

**Issue by nykotik** [JujuAdams/Scribble#553]
Just starting using Scribble, and text rendering seems to be inconsistent when using draw_text_scribble() vs GM's default draw_text().  In the first image below I'm using draw_text_scribble() with raw positions for each of the button text elements.  You can see between "1a", "1b", and "1c" that the "1"s are rendered inconsistently.
![image](https://github.com/user-attachments/assets/b2e53e9a-7686-496b-8a1f-672267bcb53f)

When using draw_text() or when using draw_text_scribble() with floored positions, I get the following consistent result:
![image](https://github.com/user-attachments/assets/a48ce195-5249-4e1e-a386-8b0efe5964ba)

Is this intended behavior?  Is it best practice to floor the text positions before drawing?  Is it a bug?

**Comment by JujuAdams** [comment]
Not a bug. If you draw anything at non-integer positions with bilinear texture filtering turned off then you will encounter graphical glitches. That GameMaker appears to round off text positions is odd and, quite honestly, it shouldn't be doing this.

**Comment by nykotik** [comment]
That makes a ton of sense and seems easy to correct for now that I know it's normal.  Appreciate your time and the libraries.  ^^
