### ISSUE TITLE
"Source font `font` not found." But it's in the asset browser.

### ISSUE THREAD

**Issue by thehirou** [JujuAdams/Scribble#556]
I imported the new 9.1.0 scribble to this project which used the previous version of scribble, the only things I changed were a couple macro settings (Either way it didn't even work before that)

The font is in the asset browser and it works normally using vanilla GameMaker functions.

(Needless to say, this worked in the previous scribble version.)

```
{ message : "ScribbleDX:
Source font "fntApfelPreload" not found
"fntApfelShadow" will not be available
 ", script : "gml_Script___scribble_error", line : 145, longMessage : "ERROR in action number 1
of Create Event for object manFlashingLights:
ScribbleDX:
Source font "fntApfelPreload" not found
"fntApfelShadow" will not be available
 
 at gml_Script___scribble_error (line 145) -     show_error("ScribbleDX:\n" + _string + "\n ", true);
", stacktrace : [ "gml_Script___scribble_error (line 145)","gml_Script_scribble_font_bake_shader (line 40) -         __scribble_error("Source font \"", _source_font_name, "\" not found\n\"", _new_font_name, "\" will not be available");
","gml_Script_scribble_font_bake_shadow (line 39) -     scribble_font_bake_shader(_source_font_name, _new_font_name, __shd_scribble_bake_shadow,
","gml_Object_manFlashingLights_Create_0 (line 9) - scribble_font_bake_shadow(global.fontStringDependingLanguage,"fntApfelShadow",2,2,c_black,1,0,false)
" ] }
```

**Comment by thehirou** [comment]
Reimporting the library fixed this, sorry for opening an unnecesary issue.

**Comment by JujuAdams** [comment]
That's ok, I'd prefer people come running whenever there's an issue in case it's something I can smooth out.

**Comment by acrinews** [comment]
> Reimporting the library fixed this, sorry for opening an unnecesary issue.

hey, how do you "reimport the library"? im having the same issue you did

**Comment by thehirou** [comment]
> hey, how do you "reimport the library"? im having the same issue you did
Import it again, like, just import it.

**Comment by acrinews** [comment]
> > hey, how do you "reimport the library"? im having the same issue you did
> 
> Import it again, like, just import it.

i need to reimport the scribble yymps file?

**Comment by thehirou** [comment]
> > > hey, how do you "reimport the library"? im having the same issue you did
> > 
> > 
> > Import it again, like, just import it.
> 
> i need to reimport the scribble yymps file?

...yes...

**Comment by acrinews** [comment]
hey, im still getting a error but know it's different.
this is what im doing:

scribble_glyph_set("fnt_astron", all, SCRIBBLE_GLYPH.Y_OFFSET, 4);

but i triggers an error:

function __scribble_get_font_data(_name)
{
    static _font_data_map = __scribble_get_font_data_map();
    var _data = _font_data_map[? _name];
    //the error is happening here:
    if (_data == undefined) __scribble_error("Font \"", _name, "\" not recognised");
    return _data;
}

the _font_data_map variable is just an empty ds map which causes the _data variable to be undefined, triggering the error.
can someone PLEASE help?

**Comment by thehirou** [comment]
> hey, im still getting a error but know it's different. this is what im doing:
> 
afaik this issue is closed, i'd recommend you to open a new one, i can't help

**Comment by acrinews** [comment]
> > hey, im still getting a error but know it's different. this is what im doing:
> 
> afaik this issue is closed, i'd recommend you to open a new one, i can't help

thanks, i'll open a new issue
