### ISSUE TITLE
Getting position of characters in `scribble_typist_add_event`

### ISSUE THREAD

**Issue by JustYourAverageUTFan** [JujuAdams/Scribble#558]
Is there a way to return the position of the first character and current character (`characterIndex`) of the current typist / scribble instance inside `scribble_typist_add_event`? Thanks in advance.

**Comment by JujuAdams** [comment]
Please use [`.get_glyph_data()`](https://www.jujuadams.com/Scribble/#/latest/scribble-methods?id=get_glyph_dataglyphindex-page)
