### ISSUE TITLE
getting height of the drawn text?

### ISSUE THREAD

**Issue by penpenyan** [JujuAdams/Scribble#559]
hi there! is there any way to get the height of the string that the scribble already managed to draw via typist? like, only height of the text that already appeared on the screen?  
`.get_height() `counting the whole, already wrapped text, and unfortunately it's not what i need.

**Comment by JujuAdams** [comment]
[`.get_bbox_revealed()`](https://www.jujuadams.com/Scribble/#/latest/scribble-methods?id=get_bbox_revealedx-y-typist) if you're using a typist, [`.get_glyph_data`](https://www.jujuadams.com/Scribble/#/latest/scribble-methods?id=get_glyph_dataglyphindex-page) if not.
