### ISSUE TITLE
Problems drawing to different surface

### ISSUE THREAD

**Issue by brady-goldsworthy** [JujuAdams/scribble#56]
I am attempting to draw to a separate surface, then draw that surface in the draw gui event.  When doing this the text that I'm drawing using scribble is being distorted.  

When only drawing in draw_gui
---
![good_text](https://user-images.githubusercontent.com/34688945/81338149-c049fd00-9071-11ea-90c4-fb5d52273c62.png)

When drawing from separate surface in draw_gui layer
---

![blurry_text](https://user-images.githubusercontent.com/34688945/81337782-313ce500-9071-11ea-9570-57dfbeca9754.png)

Any ideas what could be causing this? Does scribble_draw support targeting different surfaces?

P.S. -- Loving scribble so far!

**Comment by JujuAdams** [comment]
Wow, that's a strange one. Could you give some code examples?

**Comment by brady-goldsworthy** [comment]
I was experimenting with this some more.  Scaling up the resolution of the GUI and font resolves this issue.  

Before I was scaling down my text while drawing, after scaling up the GUI I'm no longer scaling the text down as much.

So it seems like this issue is maybe tied to scaling down/drawing small fonts to a separate surface? Would that make sense? I'm not too familiar with how scribble handles things in the background.

I'm happy with my fix, but I can post actual code if you did want to look into it more.

Thanks for your help.

**Comment by JujuAdams** [comment]
Basically the litmus test is "does the same thing happen with `draw_text_ext()`?" Do you see similar behaviour if you use GM's native text rendering?
