### ISSUE TITLE
Trying to use a shadow with a non-white text value.

### ISSUE THREAD

**Issue by Konlet** [JujuAdams/Scribble#567]
I'm trying to apply colour to a font with a baked shadow which needs to be a different colour. When applying a hexcode, the entire draw including the shadow is the applied colour. The expected behaviour would be that the shadow remains the baked colour regardless.
`scribble_font_bake_shadow("font", "white_shadow", 0, 1, #f2f0e5, 1, 0, false);`
`scribble("[#f32b2b][white_shadow]This should be red with a white shadow, but it's all red.");`

**Comment by JujuAdams** [comment]
Scribble bakes the shadow into the font graphic itself. Colour blending is performed by multiplying the colour with the source font. This means the shadow is affected by the blend colour.

This is inteded behaviour insofar as it is a known side effect of the feature.

**Comment by JujuAdams** [comment]
[Update 9.2 addresses this ticket.](https://github.com/JujuAdams/Scribble/releases/tag/9.2.0)
