### ISSUE TITLE
scribble_typist fade delay

### ISSUE THREAD

**Issue by Konlet** [JujuAdams/Scribble#568]
With scribble_typist is there a way to add a delay between fading in and out using the native scribble_typist functions?

**Comment by JujuAdams** [comment]
I don't know what you mean by "between fading in and out" as this implies an automatic process that you don't have control over. Typists don't type in or type out unless you explicitly call a method.

**Comment by Konlet** [comment]
To resolve my issue I setup a time source to add an out method to the typist after a few seconds. I'm guessing you'd recommend having a statement check whether or not to draw with a typist? Regardless my issue is solved, ty!

**Comment by JujuAdams** [comment]
The solution you have there is what I'd recommend.
