### ISSUE TITLE
Correct inter-word spacing prior to a manual newline when using fa_justify

### ISSUE THREAD

**Issue by tibisoft007** [JujuAdams/Scribble#571]
Last line of paragraph is "stretched" if the paragraph is closed by \n, or in case the text is assembled from 2 (or more) strings, eg. 
`var _txt = _txt1 + _txt2;`
Like in example attached:
![image](https://github.com/user-attachments/assets/73e13292-e13f-4f7e-a475-1a3bd55adaf1)
Both in 'normal' and in 'typist' mode.
Yellow color is only for in-line command test, but no issue with that. :)

Thanks for any suggestion for workaround or improvement.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Scribble/commit/60e44530e3afeb90f18a2db781dd1397bfc4ab75

Available in [9.3.0](https://github.com/JujuAdams/Scribble/releases/tag/9.3.0)
