### ISSUE TITLE
Scribble system not implicitly booting on many function calls

### ISSUE THREAD

**Issue by acrinews** [JujuAdams/Scribble#573]
I don't know if I'm doing something wrong, but whenever I try to use the function scribble_glyph_set, I get an error.
I'm using it like:

scribble_glyph_set("fnt_astron", all, SCRIBBLE_GLYPH.Y_OFFSET, 4);

I found out that the error is being triggered in this function:

function __scribble_get_font_data(_name)
{
static _font_data_map = __scribble_get_font_data_map();
var _data = _font_data_map[? _name];
if (_data == undefined) __scribble_error("Font "", _name, "" not recognised");
return _data;
}

Debugging this code, I also discovered that the static _font_data_map is always empty because the __scribble_get_font_data_map just returns an empty ds map.
The _data is the _font_data_map (which is just an empty ds map) at the _name position, so the _data is also empty (undefined), which triggers the scribble error function.

What do I do?
(Also, English is not my first language so sorry if I misspelled something)

**Comment by JujuAdams** [comment]
You're doing great with your English.

What error are you seeing specifically? When/where are you calling `scribble_glyph_set()`? What type of font is `"fnt_astron"`?

**Comment by acrinews** [comment]
> You're doing great with your English.
> 
> What error are you seeing specifically? When/where are you calling `scribble_glyph_set()`? What type of font is `"fnt_astron"`?

Thanks!

The error I'm getting is the Font fnt_astron not recognised. I'm calling cribble_glyph_set() on a script.
I don't understand your last question, what do you mean by type of font?

**Comment by JujuAdams** [comment]
When you say "calling `scribble_glyph_set()` on a script" do you mean in the root of the script i.e. the function is.called when the game boots?

There are multiple types of fonts in GameMaker. There are regular font assets, SDF fonts, spritefonts, `font_add()` fonts etc.  With that in mind, what kind of font is `"fnt_astron"`?

**Comment by acrinews** [comment]
> When you say "calling `scribble_glyph_set()` on a script" do you mean in the root of the script i.e. the function is.called when the game boots?
> 
> There are multiple types of fonts in GameMaker. There are regular font assets, SDF fonts, spritefonts, `font_add()` fonts etc. With that in mind, what kind of font is `"fnt_astron"`?

The function is being called when the game boots.

The fnt_astron is a regular font asset, I just imported the font normally.

**Comment by JujuAdams** [comment]
mmyep ok you're calling the function before Scribble has itself booted up. This is a bug in Scribble and one that is time-consuming to fix.

You can fix this crash by moving the code into the Create event of an object that you create when the game starts.

**Comment by acrinews** [comment]
> mmyep ok you're calling the function before Scribble has itself booted up. This is a bug in Scribble and one that is time-consuming to fix.
> 
> You can fix this crash by moving the code into the Create event of an object that you create when the game starts.

alright tysm

**Comment by JujuAdams** [comment]
Fixed by version 9.3.1 https://github.com/JujuAdams/Scribble/releases/tag/9.3.1
