### ISSUE TITLE
Possible bug with the typist when consecutive pages contains the same string

### ISSUE THREAD

**Issue by phablix** [JujuAdams/Scribble#576]
![image](https://github.com/user-attachments/assets/d73dbd90-8ea8-456d-b4c1-9cf9900766f7)
If I set the same text in different pages, when changing pages using .page(); the typist state will always be 1.
In the case of the first image the typist will only work for the first line (first page). In the next consecutive pages that share the same text the typist animation won't run and typist.get_state() will return 1.

However if the text is different the typist animation will work as normal.
![image](https://github.com/user-attachments/assets/f72b096b-b6a0-4ec7-8414-a93cd0ee3f66)
In the case of this image it will work for each page.

Seems that the animation don't run if two or more consecutive pages share the same string

**Comment by JujuAdams** [comment]
This'll be due to the cached string being the same. You should reset the typist (using the `.reset()` method) when changing to a new string and not rely on Scribble doing that for you.

**Comment by phablix** [comment]
That worked, thank you!
