### ISSUE TITLE
Using scribble with blend modes causes weird rendering issues.

### ISSUE THREAD

**Issue by carbondog-x86** [JujuAdams/Scribble#577]
I'm using blend modes to mask text inside of my textboxes, and It's causing some weird rendering issue with scribble. Like, its drawing the empty space of the characters and.

![Scribble issue](https://github.com/user-attachments/assets/01bfec53-94bb-47aa-9f82-7ee864a541cf)

Here's the relevant code that draws the text relative to the mask.

```
gpu_set_blendmode_ext(bm_dest_alpha, bm_inv_dest_alpha);
gpu_set_alphatestenable(true);

text.draw(text_x, text_y);
	
gpu_set_alphatestenable(false);
gpu_set_blendmode(bm_normal);
```
I don't know if this is a problem that's already been asked, or if there is a solution in the manual I haven't read yet?

**Comment by JujuAdams** [comment]
Scribble uses its own shader. Alpha testing is a feature of the default native GameMaker shader. As such, alpha testing is not supported by Scribble. Alpha testing in general is expensive on the GPU and I am not inclined to provide support for it.

Instead, if you're using more recent versions of GameMaker you should looking into the new native GPU scissor functions. These will help you further with content masking. If you want to clip your text using more complex shapes then you should use the stencil buffer.
