### ISSUE TITLE
Characters Move In Circles

### ISSUE THREAD

**Issue by AtomixxGAMES** [JujuAdams/scribble#58]
Hi, I’d like a way for the text to move in circles. I really want this because I’m making  a game and I really want my text’s characters to move in circles. It’s like the text in Pet the Pup at the Party. So please, if you are reading this Adam, can you add something like “[circle]” for the text to move circles by character.

**Comment by JujuAdams** [comment]
Implement for `5.5.0f` which can be downloaded here: https://github.com/JujuAdams/scribble/releases/tag/5.5.0

PS. My name is "Juju" ; )
