### ISSUE TITLE
Scribble fails to compile with String not found:  at line 1 : HLSL11 compiler failed with exit code -1

### ISSUE THREAD

**Issue by pajaritia** [JujuAdams/Scribble#583]
Hello, I'm using GameMaker-LTS version.
Scribble version 8.8.3 and earlier work when importing to my project.
Scribble version 9.1.0 and higher show this error when pressing Play.
![SCRIBBLE ERROR](https://github.com/user-attachments/assets/af1ca359-1158-49c2-9f9e-fa440623b720)

this is the log

"C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49/bin/igor/windows/x64/Igor.exe"  -j=8 -options="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\build.bff" -v -- Windows Run

Loaded Macros from C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\project_340977EF\macros.json
Options: C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49\bin\platform_setting_defaults.json
Options: C:\Users\user\AppData\Roaming/GameMakerStudio2-LTS\user_4671723\local_settings.json
Options: C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\project_340977EF\targetoptions.json
Setting up the Asset compiler
C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="project" /td="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP" /cd="C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\project_340977EF" /rtp="C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49" /zpuf="C:\Users\user\AppData\Roaming/GameMakerStudio2-LTS\user_4671723"  /ffe="eXpvfGtxgjeDg202c3h+b3Z2c31veH1vNnh/dnZzfXI2dnlxc3hpfX15Nn5vfX4=" /m=windows /tgt=64 /nodnd /cfg="Default" /o="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\project_3011AD1F_VM" /sh=True /optionsini="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\project_3011AD1F_VM\options.ini"  /cvm /baseproject="C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49\BaseProject\BaseProject.yyp" "C:\Users\user\GM\project\project.yyp" /preprocess="C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS
2CACHE\project_340977EF"
Found Project Format 2
ProjectFileWatcher:StartWatching:C:\Users\user\GM\project
Started: 11/04/2024 23:53:47
Finished: 11/04/2024 23:53:47
Diff: 00:00:00.3526947
Loaded Project: project
finished.
Release build
Options: C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\project_340977EF\ExtensionOptions.json
OptionsIni
Options: C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\project_340977EF\PlatformOptions.json
[Compile] Run asset compiler
C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="project" /td="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP" /cd="C:\Users\user\AppData\Roaming\GameMakerStudio2-LTS\Cache\GMS2CACHE\project_340977EF" /rtp="C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49" /zpuf="C:\Users\user\AppData\Roaming/GameMakerStudio2-LTS\user_4671723"  /ffe="eXpvfGtxgjeDg202c3h+b3Z2c31veH1vNnh/dnZzfXI2dnlxc3hpfX15Nn5vfX4=" /m=windows /tgt=64 /nodnd /cfg="Default" /o="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\project_3011AD1F_VM" /sh=True /optionsini="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\project_3011AD1F_VM\options.ini"  /cvm /baseproject="C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49\BaseProject\BaseProject.yyp" "C:\Users\user\GM\project\project.yyp" /debug /bt=run /rt=vm /64bitgame=true
Looking for built-in fallback image in C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49\bin\BuiltinImages
Compiling Shader Shader___shd_scribble_bake_outline_4dir... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_outline_4dir... compiled with ps_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_outline_8dir... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_outline_8dir... compiled with ps_4_0_level_9_1 (optimised)
Error compiling fragment shader:
Error : [F]Shader___shd_scribble(49) : 'GL_OES_standard_derivatives' : extension is disabled
Error : [F]Shader___shd_scribble(56) : 'GL_OES_standard_derivatives' : extension is disabled
Error : [F]Shader___shd_scribble(66) : 'GL_OES_standard_derivatives' : extension is disabled
Error : Shader___shd_scribble : HLSL11 compiler failed with exit code -1
Compiling Shader Shader___shd_scribble_bake_shadow... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_shadow... compiled with ps_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_outline_8dir_2px... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___shd_scribble_bake_outline_8dir_2px... compiled with ps_4_0_level_9_3 (optimised)
Compile Constants...finished.
Remove DnD...finished.
Compile Scripts...finished.
Compile Rooms...finished.
Compile Objects...finished.
Compile Timelines...finished.
Compile Triggers...finished.
Compile Extensions...finished.
Global scripts...finished.
finished.
collapsing enums.
Final Compile...finished.
Saving IFF file... C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\project_3011AD1F_VM\project.win
Writing Chunk... GEN8 size ... -0.00 MB
option_game_speed=60
Writing Chunk... OPTN size ... 0.00 MB
Writing Chunk... LANG size ... 0.00 MB
Writing Chunk... EXTN size ... 0.00 MB
Writing Chunk... SOND size ... 0.00 MB
Writing Chunk... AGRP size ... 0.00 MB
Writing Chunk... SPRT size ... 0.00 MB
Writing Chunk... BGND size ... 0.00 MB
Writing Chunk... PATH size ... 0.00 MB
Writing Chunk... SCPT size ... 0.00 MB
Writing Chunk... GLOB size ... 0.02 MB
Writing Chunk... SHDR size ... 0.00 MB
Writing Chunk... FONT size ... 0.11 MB
Writing Chunk... TMLN size ... 0.00 MB
Writing Chunk... OBJT size ... 0.00 MB
Writing Chunk... FEDS size ... 0.01 MB
Writing Chunk... ACRV size ... 0.00 MB
Writing Chunk... SEQN size ... 0.00 MB
Writing Chunk... TAGS size ... 0.00 MB
Writing Chunk... ROOM size ... 0.00 MB
Writing Chunk... DAFL size ... 0.00 MB
Writing Chunk... EMBI size ... 0.00 MB
Writing Chunk... TPAGE size ... 0.00 MB
Texture Group - __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_
Texture Group - Default
Writing Chunk... TGIN size ... 0.00 MB
Writing Chunk... CODE size ... 0.00 MB
Writing Chunk... VARI size ... 0.76 MB
Writing Chunk... FUNC size ... 0.09 MB
Writing Chunk... FEAT size ... 0.04 MB
Writing Chunk... STRG size ... 0.00 MB
Writing Chunk... TXTR size ... 0.43 MB
0 Compressing texture... writing texture __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME__0.yytex... 
1 Compressing texture... writing texture Default_0.yytex... 
Writing Chunk... AUDO size ... 0.69 MB
Writing Chunk... SCPT size ... -0.00 MB
Writing Chunk... DBGI size ... 0.01 MB
Writing Chunk... INST size ... 0.40 MB
Writing Chunk... LOCL size ... 0.00 MB
Writing Chunk... DFNC size ... 0.02 MB
Writing Chunk... STRG size ... 0.04 MB
Stats : GMA : Elapsed=2477.6661
Stats : GMA : sp=13,au=5,bk=0,pt=0,sc=1604,sh=7,fo=2,tl=0,ob=17,ro=1,da=8,ex=0,ma=423,fm=0xD840B2BD7FBE66B4
C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49/bin/assetcompiler/windows/x64/GMAssetCompiler.dll exited with non-zero status (1)
elapsed time 00:00:03.9413216s for command "C:\ProgramData/GameMakerStudio2-LTS/Cache/runtimes\runtime-2022.0.2.49/bin/igor/windows/x64/Igor.exe" -j=8 -options="C:\Users\user\AppData\Local\GameMakerStudio2-LTS\GMS2TEMP\build.bff" -v -- Windows Run started at 11/04/2024 23:53:46
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

**Comment by JujuAdams** [comment]
Scribble 9.x does not support GM LTS 2022. I realise this isn't called out properly in documentation so I will address that now. The earliest version of GM that Scribble supports I believe in 2023.1. For the record, Scribble 9 has mostly been developed using GM2024.8,

**Comment by aqc438** [comment]
Perfect, then I guess this is not really an issue.
I will consider using GM2024, thanks for the clarification.

**Comment by pajaritia** [comment]
Perfect, then I guess this is not really an issue.
I will consider using GM2024, thanks for the clarification.

**Comment by JujuAdams** [comment]
You're welcome, best of luck with your game.
