### ISSUE TITLE
Scribble Audio Crash

### ISSUE THREAD

**Issue by JustAGuyAFAIK** [JujuAdams/Scribble#587]
Scribble crashes on the latest GM 2024.11 update due to GM being more strict with checking for audio that doesn't exist. I fixed it going into `__scribble_play_sound()` and change `if ((not SCRIBBLE_USE_SOUND_WHITELIST) || (_sound_whitelist_map[? _sound] ?? false) )` to `if ((not SCRIBBLE_USE_SOUND_WHITELIST) || (_sound_whitelist_map[? _sound] ?? false) || ( _sound != undefined || _sound != -1 ) )`

**Comment by JujuAdams** [comment]
Thanks for updating this ticket because I wasn't looking forward to rolling out another update lol
