### ISSUE TITLE
Split box alignment function into h/v parts

### ISSUE THREAD

**Issue by batblaster** [JujuAdams/scribble#62]
Hi,
at the moment the alignment can be done in a single function but if you just need to change the H or the V you need to change both, maybe would be good to have also the 2 separate functions.

Thanks.

**Comment by JujuAdams** [comment]
Thanks for your feature request!

I'll allow use of `undefined` or a negative number to not set a value when using `scribble_draw_set_box_align()`

**Comment by JujuAdams** [comment]
In 6.0.2
