### ISSUE TITLE
Simple call for get width and height of a string.

### ISSUE THREAD

**Issue by ajrdesign** [JujuAdams/scribble#66]
After using scribble for a bit I noticed it was a bit of a pain to use scribble_get_bbox every time i wanted either the width or the height of a string (which is quite often). So I made these simple scripts, they probably could be optimized but they are very useful and could be helpful to others as part of the main add on:

scribble_get_width
`/// @arg string
var b = scribble_get_bbox(argument0,0,0)
return b[2]-b[0];`

scribble_get_height
`/// @arg string
var b = scribble_get_bbox(argument0,0,0)
return b[3]-b[1];`

**Comment by JujuAdams** [comment]
I'll open this one up for discussion. I'm not keen on adding functions for every little thing when they're this easy to make yourself, but I'd like to hear other opinions too.

PS. `SCRIBBLE_BBOX` has dedicated `W` and `H` members!

**Comment by AvioxArcade** [comment]
IMO, since these scripts exist in the standard GML string_get series, I'd say it makes sense to add them into scribble (even if they are fairly simple), for ease of use for beginner users.

**Comment by JujuAdams** [comment]
Feature accepted! I'll implement this for v5 and v6

**Comment by JujuAdams** [comment]
In v6.0.5
