### ISSUE TITLE
Line breaks reset halign

### ISSUE THREAD

**Issue by ajrdesign** [JujuAdams/scribble#67]
I noticed that when I add a line break to a string (mostly with \n) it breaks the alignment setting in scribble. Is there a way to avoid that?

**Comment by JujuAdams** [comment]
Oh! It shouldn't do that. I'll test and fix that tonight.

Thank you for raising this issue.

**Comment by JujuAdams** [comment]
Hmm, I can't reproduce this issue. Could you give me some more detail on what's happening your end?

**Comment by squishyb** [comment]
Hey! Just jumping in to add to this, as per our conversations elsewhere @juju-adams ! 

Here's an image showing the issue I'm having right now : 

[Image link](https://imgur.com/a/RI8WZtl)

Here's the code I'm using to write the text description: 

`
scribble_draw_set_box_align(fa_center,fa_middle)
scribble_draw_set_wrap(0,sprite_get_width(sprite_index)-110)
scribble_draw_set_transform(image_xscale,image_yscale,image_angle)
scribble_draw(text_x,text_y,string(descString))
`

One of the things that may also be a separate issue, but I can't get the line-height to tighten up at all either on this. In the `draw_set_wrap` I've tried setting 0, negative numbers, other numbers greater than 0 but I can't get it to go any tighter than what it is right now. 

Thanks for your help with this one! Hopefully it's not just me being a moron and missing a parameter somewhere!

**Comment by JujuAdams** [comment]
Thank you for the extra info, very illuminating.

Could you show me what string you're drawing?

**Comment by squishyb** [comment]
No problem, in those examples they are: 
`
"Inflict #a damage.";
"Gain 2 Energy.";
"Block #d.";
"Inflict #a damage. Suffer 1 Daze.";
`
The #a and #d are string replaced before being sent to the draw command.

**Comment by squishyb** [comment]
I managed to uncover some more information also, re: the line height issue. I don't know if they're connected, but as you can see, I have my `draw_set_wrap` first argument set to 0, but there is quite a lot of spacing. However on this card: 

[Image Link](https://i.gyazo.com/b9534f57f9a6155d8f076e3e4e53df1b.png)

It looks like that last line is having its line height correctly set to 0 for some reason. The string being written in that instance is : 

`"Inflict #a damage.\nOpener: Gain 2 Strength.";`

That one does have a force linebreak in there, however I have a good 50+ cards with the force line break that don't suffer the same issue. Here is an example of a card with 4 lines of text:

[Image link](https://i.gyazo.com/037d770842450fb403117530a541b6ea.png)
`"This turn, all Attack cards played apply Bleed 3. Gain 1 Volatile [i]Hidden Blade[/i].";`

Let me know if anything else would be helpful! Thank you so much!

And just incase its helpful, heres 4 lines of text with line breaks included:

[Image link](https://i.gyazo.com/7a101a04e628cac97be8982b01079dfb.png)
`"Remove up to 2 Vulnerable.\nApply Weak 1 to target creature.\nRebound.";`
