### ISSUE TITLE
Drawing a scribble twice in one frame, but with different autotype parameters

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/scribble#69]
Edge cases are fun.

If you want to draw the same scribble at two different places on the screen, setting the autotype settings of one will also affect the autotype settings of the other. Which makes perfect sense, but probably isn't what you'd hope for if you did that.

In the gif, both NPCs have the same text string if you try to read their mind. Reading the mind of one (i.e. creating a new thought bubble containing a scribble, and firing off its autotype) while another one already exists also resets the autotype of the existing one.

![scribble-autotype-issues](https://user-images.githubusercontent.com/7087495/82470732-b40f6800-9a93-11ea-8fd4-67a0a878539e.gif)

I should just be able to append a unique ID (probably the `get_timer()` of when the scribble was created) to each thought bubble scribble so that they don't hash to the same value, but an official solution might be nice since I imagine I'm not the only person who's going to do this eventually.

**Comment by JujuAdams** [comment]
This is an issue I'm aware of. The 2.3.0 port has (had?) a solution for this but that won't see the light of day for some time, if ever. If you dive into `scribble_draw()` (for 5.x.x) or `scribble_cache()` (for 6.x.x) you'll be able to modify the cache string to create a new Scribble text element with a slightly different cache string.

**Comment by DragoniteSpam** [comment]
That's what I ended up doing, for now. What was your 2.3 solution?

**Comment by JujuAdams** [comment]
Separated the autotype state from the parsed/cached vertex buffer data. This means you can have multiple occurances of text with different autotype states whilst referencing back to the same cached data. It's the parsing that's the really expensive bit, creating new autotype state containers (which are just arrays at the end of the day) is cheap.

**Comment by DragoniteSpam** [comment]
I suppose I could squash that in too - although for the time being these scribbles are only a line or two long, and they can only be created as fast as the player can press a button, so it's probably not worth the time to optimize for me.

**Comment by JujuAdams** [comment]
Note: Planned for v6.x.x

**Comment by JujuAdams** [comment]
Implemented for v6.0.4
