### ISSUE TITLE
Some character pixels are disappearing in spritefont

### ISSUE THREAD

**Issue by ajrdesign** [JujuAdams/scribble#72]
I had an issue with a period character that was only 1 pixel that I brought up to @JujuAdams and the latest version seems to have fixed that one but broken others for some reason.
<img width="534" alt="Screen Shot 2020-05-26 at 6 19 25 PM" src="https://user-images.githubusercontent.com/2229401/82965819-1a0d5b00-9f7e-11ea-978e-fb18d6e3fa08.png">

Notably commas as you can see in the screenshot.

This is the string being displayed: 
`"Woah... didn’t expect you to show up in "+ string(name) + "...[delay,400] shit...[delay,400] just in time too. Your assistance would be fucking grand. Hold for more info."`

**Comment by JujuAdams** [comment]
The missing characters here are often ones that text editors (commonly Google Docs) replace with more visually appealing versions. Three dots in a row might get replaced with [ellipsis](https://www.fileformat.info/info/unicode/char/2026/index.htm), an apostrophe might get replaced with [single right quotation mark](https://www.fileformat.info/info/unicode/char/2019/index.htm). Please check your string input for these Unicode characters. Scribble should also put warnings into the console output.

**Comment by ajrdesign** [comment]
ahh yeah it was a substitution. I swapped out some characters and it's working fine now. Thank you!

**Comment by JujuAdams** [comment]
You're welcome.
