### ISSUE TITLE
Events not firing sometimes (5.5.0)

### ISSUE THREAD

**Issue by AvioxArcade** [JujuAdams/scribble#73]
I'm trying to move from version 5.4.5 to 5.5.0 for a large project I'm working on, and something in the update caused several (but not all) custom scribble events to not fire off. 

What do you recommend I do to debug? I couldn't find any major changes in source control that gave me an idea why they'd stop working.  
I also tried moving to 6.x out of curiosity, with the same issue -- some custom events don't fire off.

My best guess with minimal debugging effort is it has something to do with multiple events being at the end of a string, or possibly skipping autotype.

I can mess around more, just wanted to check in with you first.

**Comment by JujuAdams** [comment]
Hmm... can't think of anything off the top of my head. Talk me through what you're expecting, what you're seeing, and what code you're using

**Comment by AvioxArcade** [comment]
After moving things around some, it looks like it's specifically custom events that don't have any characters after them.
For example, one custom event I use is `"[pathfind, obj_id]"` to get an npc to move to a location. 
`"Follow me![pathfind,mark_red]"` doesn't work.
`"Follow me![pathfind,mark_red] "` (whitespace after the event) doesn't work.
`"Follow me![pathfind,mark_red]."` (period after the event) works.
`"[pathfind,mark_red]Follow me!"`  (event before string) works.

The weird part is built-in events at the end of a string DO work. For example, drawing a sprite named "sprite_circle",
`"Follow me![pathfind,mark_red][sprite_circle,0]"` Both draws the sprite and causes the `pathfind` event to fire off. 

As you might expect from the above exmples, 
`"Follow me![sprite_circle,0][pathfind,mark_red]" will draw the sprite, but not fire off the `pathfind` event. 

I hope that helps!

**Comment by JujuAdams** [comment]
Just checked the release .yymp and it is labelled as 5.5.0, date is 2020-05-05. Please could you re-import the [package](https://github.com/JujuAdams/scribble/releases/tag/5.5.0) and try to reproduce the bug

**Comment by AvioxArcade** [comment]
No worries! I imported the linked version and verified it is also not working. 
As a note, the 6.x versions did the same thing, so whatever change was made since 5.4.5 has stayed in there.

**Comment by JujuAdams** [comment]
Uploaded [5.5.0g](https://github.com/JujuAdams/scribble/releases/tag/5.5.0) which should fix the problem. Working on v6 now

**Comment by JujuAdams** [comment]
Fixed in 6.0.5
