### ISSUE TITLE
Change scribble_add_color() to scribble_add_inline_color()?

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#74]
I feel like the current name is perhaps not as clear as it could be.

**Comment by DerJulien** [comment]
+ 1
though id probably prefer if it were called scribble_initialize_new_inline_color() because adding might just be a little misleading

**Comment by AvioxArcade** [comment]
I like the name as-is.

I think a name change would be warranted if there are color features available in scribble other than inline colors, and `scribble_add_color()` colors couldn't be used in those situations.

For example, I remember seeing something about pre-baked outlines in 6.x. If a color option is available there, and you can't use added colors, then a name change might be warranted. But if you support passing strings to reference these colors, then scribble_add_color() is actually more appropriate, right?

**Comment by DragoniteSpam** [comment]
I like "add" because it looks most like a lot of the other built-in drawing functions. "inline" would be pretty arcane to people who don't know what that word means.

**Comment by DerJulien** [comment]
> I like "add" because it looks most like a lot of the other built-in drawing functions. "inline" would be pretty arcane to people who don't know what that word means.

At the same time most people who lack the skill/knowledge to look up what that means and use it effectively probably won't be using a dedicated text renderer I think

**Comment by DragoniteSpam** [comment]
> At the same time most people who lack the skill/knowledge to look up what that means and use it effectively probably won't be using a dedicated text renderer I think

You'd be surprised how many people find it because they think the built-in text renderer to be lacking.

**Comment by JujuAdams** [comment]
> If a color option is available there, and you can't use added colors, then a name change might be warranted.

_sweating.jpg_

I hadn't considered custom colour custom for the outline functions!
