### ISSUE TITLE
Add warning when using scribble_draw() outside a Draw event?

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#77]
Proposal: Use the in-built GM variable `event_type` to detect when `scribble_draw()` is used outside of a Draw event, and then show a warning message

&nbsp;

The intention with Scribble v6 is that `scribble_cache()` should be used when you want to instantiate a text element without drawing it. This will be a bit faster than `scribble_draw()`, and more to the point, `scribble_draw()` does all kinds of extra processing that might break things

Previous examples did use `scribble_draw()` instead (alongside the ill-advisied `scribble_draw_set_cache_group()` function _\*shudder\*_) and I'd like to encourage people to kick the habit. I also don't want to remove `scribble_draw()`'s return value because 1) that's super useful 2) that'll break a ton of existing stuff.

However, I can see occasions where one might want to use `scribble_draw()` outside of a Create event, especially for drawing to surfaces. This means any warning that's put in will need to be tied to a macro.

**Comment by SpicyMelonCrab** [comment]
Personally I do not think it's necessary. If someone uses scribble_draw incorrectly it will still work, correct? I don't think you need to enforce best practices so stringently. A reminder in the readme is enough IMO, or even just a show_debug_message that shows the first time you do it.

**Comment by JujuAdams** [comment]
> it will still work, correct? 

Not unnecessarily! It's undefined behaviour

**Comment by DragoniteSpam** [comment]
> alongside the ill-advisied scribble_draw_set_cache_group() function *\*shudder\**

Oh come on, it wasn't *that* bad!

I do use `scribble_draw` for one or two surfaces in Create events. Maybe you could also add a `scribble_suppress_next_warning()` or something to let people explicitly disable the warning for individual scribbles.

**Comment by JujuAdams** [comment]
Thanks for your input! I think I'll hold off on implementing this for now
