### ISSUE TITLE
"[delay]" and autotype_character_delay() don't function after using autotype_skip()?

### ISSUE THREAD

**Issue by madmalletmover** [JujuAdams/scribble#80]
Disclaimer: This may just be my misunderstanding scribble's functionality. If so, please accept my apologies and disregard.

To reproduce:
In the example project, open obj_test.  Before executing `scribble_cache(),` insert `scribble_add_autotype_character_delay(",",500)`. Then make rm_test the first room in the rooms list and run, using the space bar to advance pages. 

This delay works properly until you use the space bar to skip to the end of a page, and after that, delays do not occur with commas (or any character) anymore on any subsequent page and even after looping back to the first page. The same thing happens if using "[delay]" instead of the character_delay script.

Other effects like text color don't seem to be affected at all, but delays implemented with [delay] or `autotype_character_delay()` no longer function.

**Comment by JujuAdams** [comment]
Hiya! Thanks for reporting this issue, I'll look into it tomorrow

**Comment by madmalletmover** [comment]
This is on version 6.0.5. As far as I can tell, once [delay] stops functioning, it no longer works for any additional elements (such as an NPC that only says one thing, but you can speak to several times).

**Comment by JujuAdams** [comment]
Thanks for your detailed bug report. This will be fixed in 6.0.6 (hopefully released in a couple hours from now)

**Comment by JujuAdams** [comment]
Fixed in [6.0.6](https://github.com/JujuAdams/scribble/releases/tag/6.0.6). Please re-open if this issue reoccurs
