### ISSUE TITLE
Provide a way to get the text of the current page

### ISSUE THREAD

**Issue by JulianDicken** [JujuAdams/Scribble#81]

**Comment by JujuAdams** [comment]
Would you want the "text" to include command tags/event tags etc.?

**Comment by DerJulien** [comment]
By default yes, maybe make it an optional argument not to include those ?

**Comment by JujuAdams** [comment]
Hmm, ok. I shall have a think about how best to do this as it isn't trivial

**Comment by JujuAdams** [comment]
Would you want the string to include linebreaks/page breaks inserted by Scribble?

**Comment by JujuAdams** [comment]
Implemented for v8. Including command tags is not possible due to the structure of text parsing, that information is lost during the text layout process.
