### ISSUE TITLE
Add [b] [i] [bi] tags to quickly change between font variants within the same family

### ISSUE THREAD

**Issue by TheFatBastid** [JujuAdams/scribble#84]
Use of bold, italics, bold italics and regular font would be handy.

GM handles each as its own font so instead of using [font name] all the time could there be a macro or something to bind a font to [b] [i] and [bi]? basically just a shortcut

Gamemaker does have a drop down for style in the font resource but  ,internally, it is just separate files, not bundled in any way
so for a more auto-magic answer Scribble needs to understand some sort of connection between files, this probably can be extracted from the .yy / JSON or, if needed, forcing the user to use fnt_main and fnt_main_bold or something

**Comment by JujuAdams** [comment]
Implemented for v6.0.8. Currently available on the `dev` branch
