### ISSUE TITLE
Add [cycle] tag to allow for cycling between different custom colours

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#85]
The [`[rainbow]`](https://github.com/JujuAdams/scribble/wiki/(6.0.0)-Text-Formatting) effect cycles the blend colour of a specific portion of text through the entire hue-space.

Sometimes, however, it's useful to cycle through a specific selection of colours. The `[cycle]` tag should take a variable number of arguments (up to some maximum e.g. 8) and then pass this data to the shader. Each argument is a value from 0 - 255 and describes a hue. The shader then cycles between these hues by interpolating through RGB space.

**Comment by JujuAdams** [comment]
...could also interpolate through YUV space?

**Comment by DragoniteSpam** [comment]
I foresee using this to make text of the default color flash to red or blue or something periodically. This should be interesting.

**Comment by JujuAdams** [comment]
Implemented for v6.0.8
