### ISSUE TITLE
Updating from 5.3.1 to 6.0.7e causes macro errors

### ISSUE THREAD

**Issue by AlexQ3D** [JujuAdams/scribble#89]
Trying to compile throws up a bunch of macro (foo) is already defined messages. 

![image](https://user-images.githubusercontent.com/14838700/86698963-9efb8380-bfc4-11ea-9b70-644a4a3f3a90.png)

I think this is because one version uses scribble_macros and the other uses scribble_config?

**Comment by AlexQ3D** [comment]
I fixed this by deleting scribble and just doing a clean install, is this the best way to update to a new version of scribble/is there a page detailing how to do that? If not, could be a good addition to the docs.

**Comment by JujuAdams** [comment]
Updating packages in GM can be a little dicey and the best method is always to do a clean re-import

I'll add this advice where suitable and I'll also add a `scribble_macros` script in future releases the hopefully avoid macro conflict issues if people don't do a full re-import
