### ISSUE TITLE
Compiler issues when imported into a GameMaker Studio 2.3 Beta project

### ISSUE THREAD

**Issue by lukehollenback** [JujuAdams/scribble#91]
I tried using Scribble in a project that I have been playing around with in GameMaker Studio 2.3 Beta. When I tried to run the project, I got the following compiler errors ↝

<img width="414" alt="Screen Shot 2020-07-07 at 11 03 36 PM" src="https://user-images.githubusercontent.com/8144622/86878769-ebb78b00-c0a6-11ea-9c82-4d79fce2b83e.png">

All I had consumed at that point in the project was the following in a global initialization script ↝

```gml
scribble_init("", "fNovember", false)
```

And then the following in a `Draw HUD` event ↝

```gml
scribble_draw(128, 128, "Hello, world!")
```

**Comment by DragoniteSpam** [comment]
Using the `gms230_6_0_7e` release for 2.3 *should* fix compiler issues if you're not already using it, although different updates to 2.3 have different issues. In particular, if the error is the compiler complaining about a `++variable` right after an if statement, just wrap `{ }` around it to make it go away.

**Comment by lukehollenback** [comment]
Ah yes – using the correct package resolved my issue 🤦‍♂️. Thanks for the help!

**Comment by glitchroy** [comment]
Just to add to what @DragoniteSpam said - I just replaced `++var` with `var++` because I deemed it to do the same thing in the context it was reported it, but adding {} seems to be safer. Thanks!
