### ISSUE TITLE
scribble_autotype_fade_out just fades in text

### ISSUE THREAD

**Issue by AlexQ3D** [JujuAdams/scribble#95]
Example project included. Maybe I'm using this function incorrectly, in which case, sorry!
Seems to be no functional difference between scribble_autotype_fade_in and scribble_autotype_fade_out
[jujuplsfix.zip](https://github.com/JujuAdams/scribble/files/4906404/jujuplsfix.zip)

**Comment by JujuAdams** [comment]
Hiya, taking a look at this now

**Comment by JujuAdams** [comment]
I belieeeeve this is fixed for v6.0.8. Please could you retest at your leisure

**Comment by AlexQ3D** [comment]
Yep, this fixed it. Thanks!
