### ISSUE TITLE
Update the damn documentation, Juju

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Scribble#96]
I KNOW I'M SORRY

**Comment by DragoniteSpam** [comment]
[Closed: unfixable]

**Comment by JujuAdams** [comment]
It's why we have the `nope` tag :D

**Comment by nkrapivin** [comment]
Update the damn documentation, Juju

**Comment by sohomsahaun** [comment]
Documentation for `scribble_add_autotype_event`should be updated in the Wiki and the script itself to include the 3rd argument (characterIndex).

You are doing great Juju! Here, take some ✨✨ **positive energy** ✨✨

**Comment by tabularelf** [comment]
More!! ✨✨ **positive energy** ✨✨

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/ScribbleNewDocs/wiki
