### ISSUE TITLE
Add [scream] effect tag

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#99]
Chaotic/random scaling effect in a similar vein to `[shake]`

**Comment by DragoniteSpam** [comment]
this should have been the first formatting tag you added tbh

**Comment by JujuAdams** [comment]
https://www.youtube.com/watch?v=Grdev5ktOGw

**Comment by DragoniteSpam** [comment]
Relatable.

**Comment by JujuAdams** [comment]
Implemented as `[jitter]` in v6.0.9

**Comment by DragoniteSpam** [comment]
Can you at least alias it to `[scream]` for those of us who want to express our state of endless existential dread via our text markup?
